### PR TITLE
rocksdb: new package

### PR DESCRIPTION
**Pull request by filnet**
WIP as there are some issues:

1/ when packaging there is this warning:
`WARNING: Package contains reference to $(cygpath -m /)`

2/ when compiling rocksdb with more libraries (lz4, bz2, snappy) then osgearth fails to link.
osgearth does not pick up the additional "external" libraries needed by rocksdb.

### CODE REVIEW

**Comment by filnet** [comment]
Issues solved. Good to merge.

**Comment by filnet** [comment]
appveyor fails with:

```
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: msys2-runtime and catgets are in conflict
```

**Comment by Alexpux** [comment]
@filnet someone need to answwer the question)

**Comment by filnet** [comment]
Only [Kevin Flynn]( (https://fr.wikipedia.org/wiki/Tron)) can do that.

**Comment by filnet** [comment]
Back to WIP as I need to add licenses and build with jemalloc.

**Comment by filnet** [comment]
Added licenses.
Building with jemalloc is trickier than I expected, so not done.

Good to merge.

**Pull request merged**
