### PR TITLE
mpv: Update to 0.11.0

### PR DESCRIPTION
**Pull request by rossy**

### CODE REVIEW

**Comment by Alexpux** [comment]
Can't build this package version

**Comment by rossy** [comment]
Hmm, it built for me. I'll try the build on my other PC when it finishes updating.

**Comment by rossy** [comment]
I just compiled and ran it on my desktop PC with an up-to-date MSYS2 and it works fine, so I'm not sure what's wrong. What's the error?

**Comment by Alexpux** [comment]
http://pastebin.com/jJAANGUD

**Pull request merged**
