### PR TITLE
Add universal pkgbuild for cross-binutils

### PR DESCRIPTION
**Pull request by wirx6**
*multiple packages are generated from _targets array
*built tools can be used with clang or gcc in cross-compilation
*ccache can be used to speed up building this

### CODE REVIEW

**Comment by lazka** [comment]
Any reason this has x86_64 in the directory name?

**Comment by Alexpux** [comment]
@lazka I move it

**Comment by lazka** [comment]
@Alexpux ok, it needs a pkgbase matching the directory as well

**Comment by Alexpux** [comment]
@lazka done

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
