### PR TITLE
Add mingw-w64-python-keras package

### PR DESCRIPTION
**Pull request by smalltalkman**
Deep Learning for humans

### CODE REVIEW

**Comment by peterbud** [comment]
Hi @smalltalkman -  We currently do not have tensorflow or theano packages - how keras is working without them? Have you tried it?

PS: I have a draft theano package, but still need to do test before initiating a PR.

**Comment by smalltalkman** [comment]
Hi @peterbud, I'm testing my theano package which have some errors, and also have compiled tensorflow within msys2 which has not been tested because i have no Enough disk space. Still, I think the keras script is safe.

**Comment by peterbud** [comment]
> Still, I think the keras script is safe.

It's a bit vague. so let me be specific: Have you tried to use the compiled keras?

**Comment by smalltalkman** [comment]
> > Still, I think the keras script is safe.
> 
> It's a bit vague. so let me be specific: Have you tried to use the compiled keras?

@peterbud Yes, I have successfully run [the test code](https://github.com/smalltalkman/hppi-tensorflow/blob/master/examples/keras_first_network.py) within msys2+python3 . Just I need to make the following changes:

- theano\gof\cmodule.py:317
rval.__file__ = rval.__file__.replace('\\\\','/')
- theano\gof\cmodule.py:1645
libname = 'python' + python_version + '.dll'
- theano\gof\cmodule.py:1649
python_lib_dirs = [os.path.join(os.path.dirname(os.path.dirname(python_inc)), 'lib')]
- theano\tensor\blas.py:384
ldflags_str = '-L"D:/softwares/msys32/mingw32/lib" -lopenblas -lopenblas'

"D:/softwares/msys32" is my home dir of msys2.

**Comment by peterbud** [comment]
@smalltalkman : I have tried this and did not work.
I have compiled and installed `python3-keras_preprocessing`, `python3-keras_applications` and `python-keras` packages.

Then tried to import keras:
`from keras.models import Sequential`

which resulted the following error:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-cc4dbf6f4418> in <module>
      1 # Create your first MLP in Keras
----> 2 from keras.models import Sequential

C:/msys64/mingw64/lib/python3.7/site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

C:/msys64/mingw64/lib/python3.7/site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

C:/msys64/mingw64/lib/python3.7/site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

C:/msys64/mingw64/lib/python3.7/site-packages\keras\backend\__init__.py in <module>
     87 elif _BACKEND == 'tensorflow':
     88     sys.stderr.write('Using TensorFlow backend.\n')
---> 89     from .tensorflow_backend import *
     90 else:
     91     # Try and load external backend.

C:/msys64/mingw64/lib/python3.7/site-packages\keras\backend\tensorflow_backend.py in <module>
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.framework import ops as tf_ops
      7 from tensorflow.python.training import moving_averages

ModuleNotFoundError: No module named 'tensorflow'
```
As I have indicated in my first post, AFAIK `keras` requires `tensorflow `or `theano `backend, and our repo does not have any of them.

Pls prepare one of them, add to the repo, and then we can revise `keras `again.

**Comment by Alexpux** [comment]
@smalltalkman add theano as dependency for keras

**Comment by smalltalkman** [comment]
@Alexpux Have changed keras default backend to theano, and add theano as dependency for keras.

**Pull request merged**
