### PR TITLE
gitg: add missing deps

### PR DESCRIPTION
**Pull request by nacho**
See that it will still not build due to the gio-unix dep.
This will be fixed by patch later on.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Yup, Just `package 'gio-unix-2.0' found`. I'd rather merge when all working if that's ok now?

**Comment by nacho** [comment]
with this last patch it should start to work. As in builds and starts the app. But there are still bugs.

**Comment by mingwandroid** [comment]
It's getting there I think :-)

**Comment by nacho** [comment]
Finally done.

**Comment by mingwandroid** [comment]
Thanks @nacho.

**Comment by mingwandroid** [comment]
Oops.

**Comment by mingwandroid** [comment]
gitg is really nice, thank you for this @nacho.

**Comment by nacho** [comment]
Thanks to you too. I am pretty sure there are still bugs, so anything you find please report it and we will fix it asap.

**Comment by mingwandroid** [comment]
The commit option doesn't seem to pick up the details giving instead:

    Author name <email@example.com>
    Committed by Committer name <email@example.com>

.. but it looks work-in-progress generally so it may not be an MSYS2 problem.

**Comment by nacho** [comment]
Please file this in the gnome bugzilla.

**Pull request merged**
