### PR TITLE
Guess library path in ocaml, camlp4 and flexdll

### PR DESCRIPTION
**Pull request by eternalNight**
I've add some patches to allow flexdll, ocaml and camlp4 to guess the paths of their libraries. The patchset can be found at https://github.com/eternalNight/MINGW-packages/tree/for-alexpux.

By the way, flexdll has been updated to 0.34 to fix a bug on 64bit systems. The binary packages to kick off the build can be found at https://github.com/eternalNight/MINGW-packages/tree/master/_bin.

However, lablgtk is broken after the update. I have fired an issue to the flexdll developers and am waiting for their response. As a result, I have to remove coqide support from the coq package temporarily due to it dependency on lablgtk. Please ignore ocaml-lablgtk for now. Thanks!

### CODE REVIEW

**Comment by Alexpux** [comment]
It not work. I get:
````
** Fatal error: Cannot find file "C:\\msys64\\mingw64\\bin\\flexdll_mingw64.o"
File "caml_startup", line 1:
````

**Comment by eternalNight** [comment]
The package works on my side. What is the value of the environment variable FLEXDIR?

**Comment by Alexpux** [comment]
We need run without FLEXDIR

**Comment by eternalNight** [comment]
Exactly. The tool with my patches should look for its libraries in <current binary dir>/../lib/flexdll if FLEXDIR is empty. However, a defined FLEXDIR will override this behavior. Could you please check FLEXDIR is empty?

**Comment by Alexpux** [comment]
Ok, now I'm have troubles build camlp4:
````
mkdir 'C:\git\MINGW-packages\mingw-w64-ocaml-camlp4\src\build-x86_64-w64-mingw32\_build'
Warning: Won't be able to compile a native plugin
Failure: Cannot find "ocamlbuild.cmo" in ocamlbuild -where directory.
Makefile:11: recipe for target 'byte' failed
````

**Comment by Alexpux** [comment]
Running ````ocamlbuild -where```` in cmd I get:
````
c:\msys64\mingw64\bin>ocamlbuild -where
/mingw64/lib/ocaml\ocamlbuild
````

But it need to return windows path

**Pull request merged**
