### PR TITLE
Updated rust package to 1.13, rustc now compiles on i686

### PR DESCRIPTION
**Pull request by hcorion**
Do not merge this yet.
I've got rust building on 64-bit and 32-bit mingw, but cargo (rust's package manager) stubbornly won't listen to any flags I give it, so it won't compile on i686.
Is it okay if we just don't include cargo with the i686 version? If yes than wait on merging this, if not just merge it, it'll be useful to some people.

### CODE REVIEW

**Comment by mati865** [comment]
Tomorrow I'll look into cargo.

**Comment by mati865** [comment]
I think cargo could be moved to separate package (building it in `package()` section is awful hack).

**Comment by mati865** [comment]
Hold on.
Rust 32 bit is completely broken, it fails to build hello world (undefined references to pthread).

**Comment by hcorion** [comment]
I asked @Alexpux and he wanted cargo combined with rust. Perhaps there is a cleaner way to do it, I'm not sure.

I see you posted on the [rust issue](https://github.com/rust-lang/rust/issues/37409), pretty much any way right now is a dirty hack.

**Comment by mati865** [comment]
> I asked @Alexpux and he wanted cargo combined with rust. Perhaps there is a cleaner way to do it, I'm not sure.

If Alex want it this way then fine. I'll find better way to do it when rust is fixed.

> I see you posted on the rust issue, pretty much any way I can think of is a dirty hack.
I've also tried building with clang and using ninja to build, still doesn't work.

It's rust issue, to overcome it `-lpthread` must be added to rustc command.
My hack is unacceptable for release version but it shows that it can work with posix threading toolchain on windows. I wouldn't post this hack if I was able to fix it in rust sources.

**Comment by mati865** [comment]
Good news!
I've developed fix for 32 bit rust, now I need to test 64 bit version.

@Alexpux you can merge but don't build it yet.
I'll create PR with fix around Monday-Wednesday depending on my time.

**Comment by hcorion** [comment]
Awesome can't wait to see it!

**Comment by hcorion** [comment]
It would be great if you tagged me @mati865 when you do the new PR.

**Comment by mati865** [comment]
Sure, I'm waiting for @Alexpux to merge this one.

**Comment by mingwandroid** [comment]
@mati865 I can merge it for you if you want?

**Comment by mati865** [comment]
Ok, thanks. 
I'll open PR in the morning.

**Pull request merged**
