### PR TITLE
For utf8, fixes for #535

### PR DESCRIPTION
**Pull request by lygstate**
Referencing to https://github.com/git-for-windows/git/pull/83

gettext: always use UTF-8 on native Windows 
and also libiconv and recode

### CODE REVIEW

**Comment by mingwandroid** [comment]
I know very little about this stuff, but ..

Won't this break cmd.exe? I think you'd want to do this only when getenv("MSYSCON") returns "mintty.exe" (or other utf-8 expecting consoles), though I dislike the idea of changing output based on environment (would users of ConsoleZ end up with build failures that users of mintty don't end up with for example?)

Sorry to be a pain, but @Alexpux @dscho @sschuberth can I get you guys' take on this matter please?

**Comment by dscho** [comment]
Well, my take on this is:

- despite extensive counseling from my side, the commit messages leave a *lot* of room for improvement. Frankly, I am not surprised that *anybody* who was not involved directly in git-for-windows/git#83 would be puzzled and confused and would *wish* for *anything* in the way of helpful documentation why those changes were made, what problems they address, and how the fixes are supposed to be the best solution compared to alternative solutions.
- Apart from the commit messages, this Pull Request itself does *nothing* at all in the way to convince anybody that there is a problem, let alone a convincing argument why the chosen path is the correct one.
- I agree that this is most likely to do the wrong thing with anything else but `mintty` (in Git, we have the luxury of *knowing* that if we're connected to a Win32 console, we already have a "winansi" emulation layer that will handle UTF-8 correctly and translate it to whatever encoding the current Win32 console expects).

So unfortunately, I have to admit that I cannot look favorably on this PR.

**Comment by mingwandroid** [comment]
Can we come up with a way of detecting that the 'winansi' emulation layer is present, or more generally that utf-8 output is wanted? @elieux , you've looked at ansicon stuff I think; should all of this just be unified into a single env var (though lots of calls to getenv was recently determined to be the cause of very slow *printf in mingw-w64; so we should probably cache that result in each of the involved libraries).

**Comment by elieux** [comment]
Ansicon only handles ANSI codes, i.e. colors, cursor movement and stuff like that.

The Windows console actually supports UTF-8 (`chcp 65001`), but there's no GUI to set it as default. [`GetConsoleOutputCP`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683169.aspx) and [`GetConsoleCP`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683162.aspx) Windows APIs could be probably used to check the active codepage.

If I read the code for git's winansi correctly, they're converting the output from internal UTF-8 to `wchar_t[]` and send that to [`WriteConsoleW`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687401.aspx), so Windows handles the conversion to the console code page.

**Comment by dscho** [comment]
> Can we come up with a way of detecting that the 'winansi' emulation layer is present, or more generally that utf-8 output is wanted?

Oh, I was not talking about Ansicon, I was talking about this here emulation: https://github.com/git-for-windows/git/blob/master/compat/winansi.c

In other words, it is *very, very* specific to Git for Windows. Nobody else has it.

**Comment by dscho** [comment]
> lots of calls to getenv was recently determined to be the cause of very slow `*printf`

We also experienced this in Git for Windows, and cache the value of `getenv("GIT_TRACE")` for that reason.

> GetConsoleOutputCP and GetConsoleCP Windows APIs could be probably used to check the active codepage.

Unfortunately, that is not good enough because the offending code uses `GetACP()`, i.e. the *system-wide* encoding.

> If I read the code for git's winansi correctly, they're converting the output from internal UTF-8 to wchar_t[] and sending that to WriteConsoleW, so Windows handles the conversion to the console code page. Winansi also seems to handle colors and other console needs for git.

Precisely.

**Comment by lygstate** [comment]
@mingwandroid You are right, it's break cmd.exe, the ANSI is a really hard to deal things under Win32, 
I have a idea, Re-implement msvcrt's all ANSI related function in UTF8 mode, such as  file io, file name manipulation, anything with path,  so that we can happily use UTF8 under win32 and gain cross-platform support, cause Linux/Android are default to use UTF8.

And we create a layer to compatible with all ANSI executables.

**Comment by elieux** [comment]
>> `GetConsoleOutputCP` and `GetConsoleCP` Windows APIs could be probably used to check the active codepage.

> Unfortunately, that is not good enough because the offending code uses `GetACP()`, i.e. the system-wide encoding.

So if we patched to code to detect the console CP and only fall back to UTF-8 if it's outputting to a pipe, would that be a good solution?

**Comment by elieux** [comment]
To be thorough, my proposed change should make it work correctly in both cmd and mintty, but outputting to a file will be UTF-8 instead of the system CP. I'm not sure if there are other negative implications.

**Comment by dscho** [comment]
@elieux forcing UTF-8 when redirecting to a pipe would break backwards compatibility and I think it might also make it harder to let the user override our choice, but those are not really big problems for me.

I would just feel much more comfortable if we could have a definitive test that says: "okay, at this point we are 100% certain that mintty (or a compatible terminal) are visible and the output goes straight into that terminal and so we *want* to use UTF-8 encoding no matter what any of those `Get*CP()` functions say".

**Comment by lygstate** [comment]
@elieux At least in mingw ecosystem, it would works perfect, so for cmd.exe, we output system CP with WriteConsoleW, otherwise, output UTF-8. This is about console, and for file open fopen(filename
we always translate to the Wide version, that's will remove the system CP problems.

**Comment by dscho** [comment]
> we output system CP with WriteConsoleW

That statement makes no sense. `WriteConsoleW()` expects UTF-16, not system CP.

> fopen(filename

This is missing a closing parenthesis. And this is not the only loose end in this argument, I am afraid. For something as central as MSys2, on which many projects rely, and more will, it is just not a good idea to "push all the buttons and stop when the result seems to look good". A *profound* understanding of the issue is necessary first, and starting to even talk about possible solutions before that understanding is even remotely reached is just a really good Recipe For Disaster.

**Pull request closed without merging**
