### PR TITLE
Shared AND Static SFML

### PR DESCRIPTION
**Pull request by RobertBColton**
I need the SFML package fixed so that it has a shared and static build like OpenAL:
https://github.com/Alexpux/MINGW-packages/blob/77476b094688c0f0b688eaa3a43845ecc8f3fd39/mingw-w64-openal/PKGBUILD#L73

Would somebody be willing to assist?

### CODE REVIEW

**Comment by Alexpux** [comment]
@RobertBColton at least you need inrease pkgrel

**Comment by RobertBColton** [comment]
What?

**Comment by Alexpux** [comment]
@RobertBColton you must insrease ````pkgrel```` variable value for rebuilding

**Comment by RobertBColton** [comment]
Ok, thanks, I hope it works.

**Pull request merged**
