### PR TITLE
mingw-w64-gdb-git: Fix replaces.

### PR DESCRIPTION
**Pull request by fracting**
For https://github.com/Alexpux/MINGW-packages/pull/1077#issuecomment-186880520

### CODE REVIEW

**Comment by fracting** [comment]
Same git checkout error on both Appveyor CI and Drone CI:

```
fatal: Cannot update paths and switch to branch 'makepkg' at the same time.
Did you intend to checkout 'origin/users/palves/mingw-cxx-conversion' which can not be resolved as commit?
==> ERROR: Failure while creating working copy of mingw-cxx-conversion git repo
    Aborting...
 
[MSYS2 CI] FAILURE: mingw-w64-gdb-git: Installing dependencies failed.
 
Command exited with code 1
```

```
fatal: Cannot update paths and switch to branch 'makepkg' at the same time.\r
Did you intend to checkout 'origin/users/palves/mingw-cxx-conversion' which can not be resolved as commit?\r
==> ERROR: Failure while creating working copy of mingw-cxx-conversion git repo\r
    Aborting...\r
\r
[MSYS2 CI] FAILURE: mingw-w64-gdb-git: Installing dependencies failed.\r
\r
[info] build failed (exit code 1)
```

Anyone understand what's wrong?

**Comment by elieux** [comment]
`'origin/users/palves/mingw-cxx-conversion' which can not be resolved as commit`

Looking at `git branch` on the cloned repo, I see no `users/palves/mingw-cxx-conversion`, just `users/palves/cxx-conversion` -- maybe that's the right branch or maybe it got integrated already.

**Comment by fracting** [comment]
It's my fault, I was helping palves testing his mingw branch, and @mingwandroid helped me create gdb-git based on palves' branch. Now palves' patches are merged to master, we should switch to master as well. However, our old patcheset doesn't apply on master anymore.

@mingwandroid could you rebase/change your patchset based on gdb master branch when you have time?

Thanks!

**Comment by fracting** [comment]
Forgot to close this pull request, it has been fixed by @mingwandroid for a long time, thanks!

**Pull request closed without merging**
