### PR TITLE
mingw-w64-oce: use secure checksum (sha256)

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Is there any way to globally reject any submissions that are using MD5 or SHA1 checksums? These were proven insecure many years ago.

**Comment by mati865** [comment]
There are warnings like `warning: mingw-w64-oce: deprecated MD5 checksums` when CI builds package but probably not much more can be done.

**Comment by vszakats** [comment]
Can it be modified to be a fatal error instead of a warning?

**Comment by mati865** [comment]
Of course by adding `--strict` to https://github.com/Alexpux/MINGW-packages/blob/master/ci-library.sh#L200.
Quality is checked by @renatosilva script https://github.com/renatosilva/pactoys/tree/master/source/saneman

**Comment by vszakats** [comment]
Thank you for the pointers, @mati865.

**Comment by vszakats** [comment]
Created a PR, in the hope that `msys2.sane.sh` is honored:
https://github.com/renatosilva/pactoys/pull/1/files

This seems to cause less side effect than going for `--strict`, though the latter may be a better option, if feasible.

**Comment by vszakats** [comment]
Created a PR, in the hope that `msys2.sane.sh` is honored:
https://github.com/renatosilva/pactoys/pull/1

This seems to cause less side effect than going for `--strict`, though the latter may be a better option, if feasible.

**Comment by vszakats** [comment]
Failed due to timeout on CI limit.

**Pull request merged**
