### PR TITLE
gstreamer: upgrade to 1.8.3

### PR DESCRIPTION
**Pull request by filnet**
Just saw an (partial) upgrade to gstreamer 1.8.3 beeing merged.
I was working on a full upgrade to 1.8.2. Bit of duplicate effort here...

 Will update it to 1.8.3 asap. I have also worked with gstreamer to get some fixes pushed upstream.

### CODE REVIEW

**Comment by Alexpux** [comment]
Yesterday I'm push streamer 1.8.3. Adjust your pull request for this.

**Comment by filnet** [comment]
Doing it at this moment ;)

**Comment by filnet** [comment]
PS: you commented out "autoreconf -fi", should I do the same in the other gstreamer packages?

**Comment by filnet** [comment]
other gstreamer related packages have things like this in the prepare()

autoreconf -fiv
or
NOCONFIGURE=1 ./autogen.sh
or
WANT_AUTOMAKE=latest autoreconf -fiv

**Comment by filnet** [comment]
pushed 1.8.3 upgrade

**Comment by filnet** [comment]
ci errors are due to pkg-config package not being up to date.

**Pull request merged**
