### PR TITLE
enchant: update to 2.2.3

### PR DESCRIPTION
**Pull request by Adsun701**
This updates enchant to 2.2.3.

### CODE REVIEW

**Comment by Alexpux** [comment]
@Adsun701 why you remove all relocation patches?

**Comment by Adsun701** [comment]
I looked at the code and could not find anything that needed relocation. Version 2.2.3 is a large jump from 1.6.1, so I don't think the patches are needed anymore. I'll check this and see if this is the case.

**Comment by Adsun701** [comment]
Confirmed that built-in relocation support was added with version 2.2.0:

https://github.com/AbiWord/enchant/issues/172

**Comment by Ede123** [comment]
@Adsun701 Does enchant actually work for you with these changes?

At least the Aspell back-end is broken by this update (should report the "misspelled word "asdf"):
```
$ echo asdf > temp.txt && enchant-2 -l temp.txt && rm temp.txt
Couldn't create a dictionary for de_DE.UTF-8
```

I noticed this while attempting to fix gtkspell/gtkspell3 packages which are both broken by this update as well due to the library name change (enchant -> enchant-2).

**Comment by Ede123** [comment]
Seems not limited to the Aspell backend.

With mingw-w64-x86_64-enchant-1.6.1-1:
```
$ enchant-lsmod.exe
aspell (Aspell Provider)
ispell (Ispell Provider)
myspell (Myspell Provider)
```

With mingw-w64-x86_64-enchant-2.2.3-1:
```
$ enchant-lsmod-2.exe

```
(empty output i.e. no providers found)

**Comment by Adsun701** [comment]
@Ede123 I think aspell may have to be rebuilt against enchant version 2.2.3, as the current aspell package was definitely built with enchant version 1.6.1.

**Comment by Ede123** [comment]
Aspell does not depend on enchant, so a rebuild should not be required.

I suspect an issue with the relocation logic introduced / removed in enchant-2.

**Comment by lazka** [comment]
bt, this broke all reverse deps of enchant due to the so/dll version bump.

**Comment by lazka** [comment]
I've openend #4041

**Comment by Ede123** [comment]
Great, thanks @lazka! Now we only need to fix enchant itself...

**Comment by lazka** [comment]
yeah, just a start... :/

**Pull request merged**
