### PR TITLE
opencl: use system provided library

### PR DESCRIPTION
**Pull request by wirx6**
*Vulkan validation layers can be added later as separate [package](https://github.com/KhronosGroup/Vulkan-ValidationLayers)

### CODE REVIEW

**Comment by Alexpux** [comment]
@ why you remove all my patches? I build everything from source

**Comment by wirx6** [comment]
Building everything from source is generating additional dependencies and need more work to maintain, we can use system dll because it's provided anyway.

**Comment by wirx6** [comment]
@Alexpux would you accept only opencl commit(for now there is no library accessible)?

**Comment by mingwandroid** [comment]
> building everything from source is generating additional dependencies and need more work to maintain, we can use system dll because it's provided anyway

Please use chocolately or some other non-from-source distro if that's how you like your software.

**Comment by wirx6** [comment]
@mingwandroid so can you tell me why mingw is using `msvcrt.dll` and other system libraries(opencl is shipped with system, vulkan is installed with any graphic driver)?

**Comment by Alexpux** [comment]
@wirx6 if you want to use system installed libraries then create your own custom repo and use your own package. We prefere to use builded by our own if possible. If you dont know why we use msvcrt and other system libraries - read mingw site.

**Comment by wirx6** [comment]
As you wish, I only wanted to help

**Pull request closed without merging**
