### PR TITLE
openal: Update to 1.18.0

### PR DESCRIPTION
**Pull request by lazka**
* Refresh patches
* Disable building tool which depends on qt5

### CODE REVIEW

**Comment by Alexpux** [comment]
I think we don't need to rename libraries as it broke many packages depended on openal

**Comment by lazka** [comment]
I haven't changed any naming with this update.

**Comment by Alexpux** [comment]
Ok, I misunderstood

**Comment by lazka** [comment]
Hm, but the LIBNAME change seems indeed weird, I'll have another look just to be sure.

**Comment by lazka** [comment]
Looks good. It used LIBNAME as the library name in older versions and hardcodes it to OpenAL now. The output name gets explicitly forced to LIBNAME so there is no change in the result.

**Pull request merged**
