### PR TITLE
gstreamer: Remove unneeded Python 2 makedep

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by filnet** [comment]
Could you take care of -git packages ?

**Comment by lazka** [comment]
@filnet sure, do you use them?

**Comment by lazka** [comment]
> I did in the past and might need them again.

ok

> May I ask why you ask ? ;)

Just wondering as I haven't used them. And I played with the idea of trying to switch them to meson.

**Comment by lazka** [comment]
done

**Comment by filnet** [comment]
thanks!

**Pull request merged**
