### PR TITLE
gstreamer: update to 1.14.0

### PR DESCRIPTION
**Pull request by filnet**
see https://github.com/Alexpux/MINGW-packages/issues/3504

### CODE REVIEW

**Comment by lazka** [comment]
I just saw you posted to the gst mailing list about the missing directsoundsink. I've filed a patch for it recently: https://bugzilla.gnome.org/show_bug.cgi?id=795750

**Comment by lazka** [comment]
Maybe we should include it in msys2?

**Comment by lazka** [comment]
> I suggest we wait for your patch to be merged upstream.

ok, sounds good.

> In the meantime, there is a workaround::
> 
> Delete the registry file located here:
> C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCache\gstreamer-1.0
> Note that INetCache is a hidden directory.

yeah, problem is can't tell every user to do that when I ship 1.14.

**Comment by filnet** [comment]
Note that the d3dvideosink plugin was renamed to d3d. So same issue there.

**Comment by lazka** [comment]
Yeah. Maybe you can link to the bugzilla bug in the ML thread to give it some attention?

**Comment by filnet** [comment]
Will do.

It is a recurring issue : https://bugzilla.gnome.org/show_bug.cgi?id=785168

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
