### PR TITLE
mingw-w64-gcc 7.1.0 - update to latest release.

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by Alexpux** [comment]
Is its libstdc++ ABI compatible with GCC6?

**Comment by JPeterMugaas** [comment]
I did not see much in that regard.  There are some notes: https://gcc.gnu.org/gcc-7/porting_to.html .  There are some notes at https://gcc.gnu.org/gcc-7/changes.html .

**Comment by jtanx** [comment]
This errors out for me at:

```
==> Starting package_mingw-w64-x86_64-gcc()...
cp: cannot stat 'share/info/cpp.info*': No such file or directory
==> ERROR: A failure occurred in package_mingw-w64-x86_64-gcc().
    Aborting...
```

**Comment by bit2shift** [comment]
@jtanx you can fix that with the patch from #2139.
That PR shouldn't have been closed.

**Comment by mati865** [comment]
@bit2shift it wasn't real fix.
There must be some missing make dependency.

**Comment by Karlson2k** [comment]
Lost colors in errors and warnings after this update. #2660

**Pull request merged**
