### PR TITLE
qt5: updated sha256 for qtwebkit-opensource-src-5.6.0.tar.xz

### PR DESCRIPTION
**Pull request by emmenlau**
For update from Wed, 06 Apr 2016 08:55:14 GMT (Unix time: 1459932914)

### CODE REVIEW

**Comment by mati865** [comment]
Have you compiled it ourself?
@adrpo had error while compiling it https://github.com/Alexpux/MINGW-packages/issues/1283#issuecomment-206502282

**Comment by adrpo** [comment]
@mati865: that might have been my error as I removed the Qt5 debug dlls from my msys2 installation and strangely they are needed to compile Qt5. I'm trying to compile again now.

**Comment by emmenlau** [comment]
I think this patch is required, but it does not address the failing build. It only fixes the checksum, see https://tea-ci.org/Alexpux/MINGW-packages/566
```
...
==> Validating source files with sha256sums...
    qt-everywhere-opensource-src-5.6.0.tar.xz ... Passed
    qtwebkit-opensource-src-5.6.0.tar.xz ... Passed
...
```

**Comment by mati865** [comment]
Bots are buggy. And probably it would be better to see fail in 30 seconds than after 4 hours of compiling.

**Comment by emmenlau** [comment]
@mati865 ok I see your point. But at least minimal builds seem to work, whatever that's worth.

**Comment by DavidEGrayson** [comment]
I just built Qt5 myself a few days ago and the checksum (d5c4daac8eef1b24290cda59db432ccc390761af17661f64f3028482647521a1) for qtwebkit-opensource-src-5.6.0.tar.xz was correct.  It looks like it has indeed changed to 9ca72373841f3a868a7bcc696956cdb0ad7f5e678c693659f6f0b919fdd16dfe since then, as this pull request is implying.

That is kind of annoying; does anyone know why the Qt people would change their released tarball without updating its version number or something?

**Comment by DavidEGrayson** [comment]
Well, I still have the old version of qtwebkit-opensource-src-5.6.0.tar.xz on my computer so I was able to compare them.  The new version adds the `qtwebkit-opensource-src-5.6.0/include` directory, which contains a bunch of header files for QtWebKit and QtWebKitWidgets.  Other than that, `diff -ur` reports no differences between the two.  I wonder if the addition of that directory has any implications for our PKGBUILD script.

**Comment by Alexpux** [comment]
They update QtWebkit tar all because they forgot to synchronize with at headers. See my workaround in PKGBUILD where I run syncqt.

**Pull request closed without merging**
