### PR TITLE
conemu: New package

### PR DESCRIPTION
**Pull request by Haroogan**

### CODE REVIEW

**Comment by Alexpux** [comment]
It still not building:
````
compiling ConEmu.rc
linking ../../Release/ConEmu.exe
../../gcc/conemu/ConEmuApp.o:ConEmuApp.cpp:(.rdata$.refptr.CLSID_ShellWindows[.refptr.CLSID_ShellWindows]+0x0): undefined reference to `CLSID_ShellWindows'
../../gcc/conemu/ConEmuApp.o:ConEmuApp.cpp:(.rdata$.refptr.IID_IShellWindows[.refptr.IID_IShellWindows]+0x0): undefined reference to `IID_IShellWindows'
collect2.exe: error: ld returned 1 exit status
makefile_gcc:240: recipe for target '../../Release/ConEmu.exe' failed
make[1]: *** [../../Release/ConEmu.exe] Error 1
make[1]: Leaving directory '/build/mingw-w64-conemu-git/src/conemu/src/ConEmu'
makefile_all_gcc:13: recipe for target 'ConEmu' failed
make: *** [ConEmu] Error 2
````

**Comment by Haroogan** [comment]
It's a problem with current MinGW-w64.  Not enough symbols in `libuuid.a`.  I've already reported this.  As soon as they add them, we probably can build it.  Please, note that this ConEmu release is ~2000 commits ahead of the previous one, so a few things could still be fixed in future.

Also, the main goal of this commit is to introduce latest stable prebuilt versions of ConEmu (from Maximus5), i.e. without `-git` suffix.  They work very well.  I'm currently using it.

**Comment by Alexpux** [comment]
Ok, thanks!

**Comment by elieux** [comment]
The `mingw-w64-conemu` PKGBUILD only repackages binaries from upstream.

**Comment by Haroogan** [comment]
Yep.  Unfortunately, at the moment the only reliable way to have up-to-date and standalone ConEmu in both 32-bit and 64-bit variants.

**Comment by mingwandroid** [comment]
The "repackage binaries" thing shouldn't have been merged. Please don't submit binary packages to MSYS2 in future. If you want that stuff, use chocolatey.

**Comment by Haroogan** [comment]
Do you find it harmful that a good terminal emulator will be available as repackaged binary until the problem with MinGW-w64 is solved?  To add, I saw temporary repackaged binaries in MSYS2 before too.

**Comment by mingwandroid** [comment]
> To add, I saw temporary repackaged binaries in MSYS2 before too.

Two wrongs don't make a right. Your comment demonstrates the problem with allowing any wriggle room in our (admittedly unwritten) binary repackaging policy.

**Comment by mingwandroid** [comment]
Binary incompatibility between DLLs, the weird crashes they cause and the amount of time we've already spent tracking these issues down is the crux of the technical issue, so yes, it is harmful.

**Comment by Haroogan** [comment]
In this case, no crashes and incompatibilities between DLLs are not possible.  If you look carefully at what binaries are installed, then you will realize it yourself.  I get your point, it's good that you defend your policies, I have nothing against it.  My point here is purely practical.  There is always room for an elegant exception.

Current `comemu-git` has a terrible blocker-bug, that 64-bit instance of ConEmu signals errors about inability to inject hooks into 32-bit processes.  In other words, for example, it is literally impossible to build 32-bit packages from 64-bit ConEmu.  Latest ConEmu builds fix that.  Unfortunately, building it with MinGW-w64 is currently not possible, but the package is too essential for a normal workflow to give it up.  All in all, this is just a safe temporary solution.  Furthermore, not a single user will notice anything because the artifacts installed are identical to the ones which come from `conemu-git`.

Sometimes it is worth it to give up one's strict policy temporarily in order to stay user-friendly.  If you have any constructive reasons to reject exactly this package, then please, provide them.  My apologies, if that causes personal troubles to you.

**Comment by mingwandroid** [comment]
I'm not interested in installing binary packages so I won't look for any incompatibilities. People, myself included, expect MSYS2 to be *fully* open source.

We have our own patches on top of mingw-w64:

https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-crt-git

.. so please submit a patch for that (it's good that you've also notified upstream about the issue already), then a from-source PKGBUILD for conemu afterwards.

Thanks for contributing, I don't want to put you off in general but I must be completely clear on our stance on binaries, I hope you understand.

**Comment by Alexpux** [comment]
About problem building conemu-git need to see here:
https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-headers/include/exdisp.h#L914

**Comment by Alexpux** [comment]
need add declaration like
https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-headers/include/shobjidl.idl#L726-L768

**Comment by Haroogan** [comment]
I see.  How the `CLSID_ShellWindows` and `IID_IShellWindows` symbols will appear in `libuuid.a`?  Is `shobjidl.idl` somehow parsed before `libuuid.a`is built and then generates new symbols for it?

**Comment by Alexpux** [comment]
i'm talking with jack about it on IRC now.

**Comment by Alexpux** [comment]
jacek will fix it in few days. We talk about importing IDL file from Wine, that already contain all GUIDs.

**Comment by Haroogan** [comment]
I think MinGW-w64 developers already use Wine for that purpose too.  Should we rather ask them to add those GUIDs upstream?

**Comment by elieux** [comment]
I was following that discussion on IRC. The file in question was different between Wine and mingw-w64. After Jacek's pulls it to mingw-w64 (because Wine's version is a superset of mingw-w64's one), I assume it will be kept in sync.

**Comment by Alexpux** [comment]
I'm upload new mingw-w64 runtime that solve problem with GUIDs. But need more work on ConEmu itself.

**Comment by Haroogan** [comment]
Sure, no problem, is new runtime already available from `pacman` so that I can rebuild ConEmu and see further problems?

**Comment by Alexpux** [comment]
Yeah, mingw-w64 runtime already in repo.

**Comment by Haroogan** [comment]
Good then, I'll look into that as soon as I can.

**Pull request merged**
