### PR TITLE
Add coq and its dependencies

### PR DESCRIPTION
**Pull request by eternalNight**
Known issues:
* Flexdll and ocaml depends on each other and thus need prebuilt packages to kick off the build. My packages can be found at https://github.com/eternalNight/MINGW-packages/raw/master/_bin/mingw-w64-i686-flexdll-0.31-1-any.pkg.tar.xz and https://github.com/eternalNight/MINGW-packages/raw/master/_bin/mingw-w64-x86_64-flexdll-0.31-1-any.pkg.tar.xz.
* When OCaml toplevel is killed by Ctrl-C, bash stops responding after displaying the "$" prompt. A normal quit from the toplevel does not trigger the issue.

### CODE REVIEW

**Comment by Alexpux** [comment]
I'm fix PKGBUILD's and simplify them. But now I have errors with using OCAML while it try to load it's dlls from ````/mingw*/lib/ocaml/stublibs````. I think we need fix ````flexdll```` and ````ocaml```` to get proper paths by default without exporting variables ````FLEXDIR```` and ````OCAMLLIB````.
I'm not use OCAML so can't do it myself.
Looking into ````flexdll```` sources I see (reloc.ml):
````
let flexdir =
  try
    let s = Sys.getenv "FLEXDIR" in
    if s = "" then raise Not_found else s
  with Not_found ->
    Filename.dirname Sys.executable_name
````

Here we need by default get ````flexdir=Filename.dirname Sys.executable_name + ../lib/flexdll````
For ocaml I think it looks similar.
Can you fix it?

**Comment by eternalNight** [comment]
Sure. I should be free at the end of this week and will try providing a fix to the default library paths.

**Comment by eternalNight** [comment]
I've add some patches to allow flexdll, ocaml and camlp4 to guess the paths of their libraries. The patchset can be found at https://github.com/eternalNight/MINGW-packages/tree/for-alexpux.

By the way, flexdll has been updated to 0.34 to fix a bug on 64bit systems. The binary packages to kick off the build can be found at https://github.com/eternalNight/MINGW-packages/tree/master/_bin.

However, lablgtk is broken after the update. I have fired an issue to the flexdll developers and am waiting for their response. As a result, I have to remove coqide support from the coq package temporarily due to it dependency on lablgtk. Please ignore ocaml-lablgtk for now. Thanks!

**Comment by Alexpux** [comment]
Create pull request please.

**Pull request merged**
