### PR TITLE
PyWikiBot 3.0.20181203: added package

### PR DESCRIPTION
**Pull request by tallero**
Added PyWikiBot package.

### CODE REVIEW

**Comment by Alexpux** [comment]
@tallero I dont see any reason to add this package to repository. Feel free to do it in your own repo

**Comment by tallero** [comment]
@Alexpux is not this the official MSYS2/MinGW repository? Is there a policy about what packages get in?
I would simply like to have Pywikibot and Daty (when it is released) to be easily installable from MinGW.

**Comment by Alexpux** [comment]
@tallero I'm only one who build and upload packages for MSYS2. This is why I dont want to increase packages count without good reason. "I would like to see it" from one user is not reason for me. I spend too many time on packages. Seems it take too much my free time.

**Comment by tallero** [comment]
@Alexpux I am sorry, I thought the process was automated through Azure (I saw the "publishing packages" line in the logs) and package mantainers did take the burden to make the upgrades work.

**Pull request closed without merging**
