### PR TITLE
mingw-w64-thrift: use newer than WinXP as default build target

### PR DESCRIPTION
**Pull request by emmenlau**
Use newer than WinXP as default build target

### CODE REVIEW

**Comment by Ede123** [comment]
Why?

**Comment by emmenlau** [comment]
I found a thread that lead me to believe that the WinXP code is inferior to the code path
for newer targets. Since the default target for MSYS2 is anyways newer than XP, I think it
makes sense to default to the newer code path.

See i.e.:
  * http://www.mail-archive.com/dev@thrift.apache.org/msg32675.html
  * https://github.com/apache/thrift/blob/master/lib/cpp/README.md (section "Windows Compatibility")

**Comment by Ede123** [comment]
@emmenlau: Thanks!

It always helps *a lot* if commit messages specify *why* some changes are done, otherwise it's often impossible to understand the reasoning behind such a change in future (I stumbled across some of these lately).

**Comment by emmenlau** [comment]
@Ede123 yes what you say makes sense, I will try to be more explicit in the future. The package is
pretty new, so I assumed to be the only user, and admittedly I was a bit sloppy :-)

**Pull request merged**
