### PR TITLE
mingw-w64-gcc-git: Add gcc-7-branch.

### PR DESCRIPTION
**Pull request by lhmouse**
GCC 7.1 was released yesterday. I think it is time for us to add it into our repository, no?

### CODE REVIEW

**Comment by Alexpux** [comment]
I think it also will be good to add patch to support  std::filesystem on windows from @niXman mingw-builds repo : https://github.com/niXman/mingw-builds/blob/develop/patches/gcc/gcc-7-filesystem.patch

**Comment by lhmouse** [comment]
WTF is GitHub doing? 
I will open a new PR for this.

**Comment by Alexpux** [comment]
I'm merge pull requests, so you need just rebase to current head

**Comment by lhmouse** [comment]
@Alexpux  
Yes I pulled, rebased then force-pushed. But since you were merging PRs I again fell behind the `master` branch. Yuck.

**Pull request closed without merging**
