### PR TITLE
latexila: new package - WIP.

### PR DESCRIPTION
**Pull request by KrullKorg**
it builds, but it doesn't start because it doesn't find some resource file (icons, ui, etc.)

but the files it says to want there are in right locations

can someone help me?

thanks

### CODE REVIEW

**Comment by Alexpux** [comment]
Try to inspect problem using Procmon to see where it try to get files.

**Comment by KrullKorg** [comment]
it says that it wants /mingw32/share/latexila/ui/ui.xml but procmon says that it tries to open C:\mingw32\share\latexila\ui\ui.xml

**Comment by mingwandroid** [comment]
right, this is standard filesystem namespace issue then. that path is an MSYS2 path, and your package is native Windows. You probably need to add relocation support.

**Comment by Alexpux** [comment]
Your patch with calling "cygpath" not solve problem. You just hardcode paths into executables. You need create patch to relocate paths. See for example: ldns, p11-kit, cyrus-sasl, enchant and other packages with such patches.

**Comment by KrullKorg** [comment]
right :-(
i'll do it ASAP

**Comment by mingwandroid** [comment]
Look at mingw-w64-pathtools for some reference code to import. We'd rather you used that than any bespoke stuff. If you want/need to make any improvements to pathtools then that's great, but make them in that (virtual!) package.

**Comment by KrullKorg** [comment]
latexila is a glib software; can i use glib functions to do relocation, as alexpux did for eog? or is it preferable use mingw-w64-pathtools?

i think that also virt-viewer has the same problem; i'll try on the weekend

**Comment by mingwandroid** [comment]
I don't mind which you use, probably go for the glib ones then, not much point adding extra code.

**Comment by KrullKorg** [comment]
if it works, could you commit it? thanks

**Pull request merged**
