### PR TITLE
Adding LFC C++ Base Package

### PR DESCRIPTION
**Pull request by bjlemke**
This is the definition to deploy LFC C++ base classes

### CODE REVIEW

**Comment by Alexpux** [comment]
@mingwandroid  wrote in other pull request
````
Hi, please squash these commits using git rebase -i HEAD~6 then follow the on-screen instructions (basically add s infront of the 5 last commits then work on the commit message).

Then use git push origin master --force to update this pull request.

Many thanks!
````

Please do it too

**Comment by bjlemke** [comment]
So I think I have to create a local git repository on my desktop and can not just use the web frontend ....

**Comment by bjlemke** [comment]
done

**Comment by Alexpux** [comment]
Don't see. At the end we need to see one commit instead 6 your commits

**Comment by bjlemke** [comment]
Sorry, commit was still missing. Done it ...

**Comment by bjlemke** [comment]
In fact, just one files has changed ( PKGBUILD ).
All other commits just have been done to deal with this git stuff.
Sorry for that

**Comment by Alexpux** [comment]
Right now I see now also my yesterday's commits there

**Comment by bjlemke** [comment]
I guess this is, because I just cloned a local repository today from the fork.
So I commited all changes now from the local repository.

**Comment by bjlemke** [comment]
Added also PKGBUILD files for packages lfcxml and cego

**Comment by Alexpux** [comment]
Can you close this pull request and create new one with clear history and more useful messages than "initial pkgbuild"

**Comment by mingwandroid** [comment]
Hi @bjlemke I think `git` is giving a little trouble (don't worry it gives us all a lot of trouble at first I think, IMHO it's wonderful though). Feel free to jump into ITC OFTC #msys2 if you want any of us to try to help out.

As an emergency measure, until you find your feet, keeping your PKGBUILD files on another directory might give you extra confidence, but in general, git won't eat your files (even though sometimes it appears it has!)

**Pull request closed without merging**
