### PR TITLE
new package: python-bsddb3

### PR DESCRIPTION
**Pull request by bpisoj**

### CODE REVIEW

**Comment by bpisoj** [comment]
How i do "resubmit"?
I try to fix thing in:
https://github.com/bpisoj/MINGW-packages/commit/f89983c6c18594902ec6afcea13a5d0db980d5f4
Do i have to make new "pull request" or what?

**Comment by mingwandroid** [comment]
Commit the fix then squash them commits using git rebase -i HEAD~2 then push to github with --force

**Comment by mingwandroid** [comment]
Also change the commit message to 'python-bsddb3: Added' if you don't mind

**Comment by bpisoj** [comment]
Hope i do everything right this time.

**Comment by mingwandroid** [comment]
I changed some minor formatting issues (lined things up better and removed whitespace and trailing spaces). Thanks for the contribution.

**Pull request merged**
