### PR TITLE
glib: Update to 2.54.1 v2

### PR DESCRIPTION
**Pull request by lazka**
* Fix wrong python exe wrapper for glib-gettextize
* Move to mingw gtk-doc
* Add gtk-doc patch for https://bugzilla.gnome.org/show_bug.cgi?id=787768

### CODE REVIEW

**Comment by Alexpux** [comment]
Well glib2 not building as pango too:
````
make[4]: Entering directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference/gio'
  DOC   Preparing build
  DOC   Building XML
  DOC   Scanning header files
  DOC   Introspecting gobjects
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x229): undefined reference to `g_desktop_app_info_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x235): undefined reference to `g_desktop_app_info_lookup_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x2a1): undefined reference to `g_file_descriptor_based_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6b5): undefined reference to `g_unix_connection_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6c1): undefined reference to `g_unix_credentials_message_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6cd): undefined reference to `g_unix_fd_list_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6d9): undefined reference to `g_unix_fd_message_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6e5): undefined reference to `g_unix_input_stream_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6f1): undefined reference to `g_unix_mount_entry_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6fd): undefined reference to `g_unix_mount_monitor_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x709): undefined reference to `g_unix_mount_point_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x715): undefined reference to `g_unix_output_stream_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x721): undefined reference to `g_unix_socket_address_get_type'
collect2.exe: error: ld returned 1 exit status
WARNING:root:Linking of scanner failed: 1
make[4]: *** [Makefile:960: scan-build.stamp] Error 1
make[4]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference/gio'
make[3]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference'
make[3]: *** [Makefile:487: all-recursive] Error 1
make[2]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs'
make[2]: *** [Makefile:487: all-recursive] Error 1
make[1]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared'
make[1]: *** [Makefile:1279: all-recursive] Error 1
make: *** [Makefile:900: all] Error 2
==> ERROR: A failure occurred in build().

````

**Comment by lazka** [comment]
Yeah, many packages still fail with "--enable-gtk-doc" and I haven't looked yet. I suspect it's upstream fallout from the perl->python port.

**Comment by peterbud** [comment]
@lazka, where could we get debug symbols for glib? Recently we experienced crashes with glib (a month ago build is just fine) and would be good to debug where the problem might be.

**Comment by lazka** [comment]
@peterbud Do you mean this https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces#General ?

**Comment by peterbud** [comment]
You mean basically to self-build, right?

**Comment by lazka** [comment]
Yes, change the options in the PKGBUILD and rebuild.

**Pull request merged**
