### PR TITLE
clang: update to 4.0.1

### PR DESCRIPTION
**Pull request by mati865**
I have disabled libunwind as per https://github.com/Alexpux/MINGW-packages/pull/2294#issuecomment-310940009
CC @martell

### CODE REVIEW

**Comment by Alexpux** [comment]
Dont disable it. You can just not install it but do not disable

**Comment by mati865** [comment]
Okay, libc++abi is broken anyway so we can let it build with libunwind.

**Comment by wirx6** [comment]
Clang/llvm can already perform self-build so I think we should set `_compiler` to `clang`.
It will make future patches more relevant because libcxx/cxxabi/unwind are used with clang anyway.

**Comment by mati865** [comment]
Clang cannot build 64 bit libc++ until mingw-w64 gets fixed.

**Comment by paniq** [comment]
I got an error trying to build this patch because it appears the public keys have changed
```
==> Verifying source file signatures with gpg...
    llvm-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    cfe-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    compiler-rt-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    test-suite-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    libcxx-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    libcxxabi-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    clang-tools-extra-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    lld-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    lldb-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    libunwind-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
    polly-4.0.1.src.tar.xz ... FAILED (unknown public key 8F0871F202119294)
==> ERROR: One or more PGP signatures could not be verified!
```

**Comment by mati865** [comment]
@paniq you have to either import this key or compile with `--skippgpcheck`.

There is no compiler error in your log, maybe out of memory issue.
CI reached 77% before reaching it's 1.5h qouta https://ci.appveyor.com/project/Alexpux/mingw-packages/build/1.0.3224

**Comment by mati865** [comment]
I'm working on 5.0.0 version.

**Pull request closed without merging**
