### PR TITLE
libmariadbclient: Add install of "mariadb_config.exe".

### PR DESCRIPTION
**Pull request by stahta01**
Possible fix for #2681 
I do NOT know enough about this package to say if my fix works or is the correct fix.
I have asked @jeroen to verify the fix works.

Tim S.

### CODE REVIEW

**Comment by jeroen** [comment]
Yes this works! It builds and installs and gives working cflags and libs! Thanks!

There is one minor annoyance that in addition to the correct paths it also returns a non-existing `-L/lib` and `-I/include`. Because these do not exist they simply get skipped by the preprocessor/linker so it's harmless. 

But perhaps we can tweak the `PKGBUILD` to properly set `${MINGW_PREFIX}` in `CFLAGS` and `LDFLAGS`?

```sh
Jeroen@MINGW64 ~/mingw-packages/mingw-w64-libmariadbclient
$ mariadb_config --libs
-L/lib/mariadb -lmariadb

Jeroen@MINGW64 ~/mingw-packages/mingw-w64-libmariadbclient
$ mariadb_config --cflags
-I/include/mariadb -I/include/mariadb/mysql -march=x86-64 -mtune=generic -O2 -pipe -Wunused -Wno-uninitialized

```

**Comment by stahta01** [comment]
I do NOT have the time or energy to look for the -L/lib and -I/include issue.

Tim S.

**Comment by jeroen** [comment]
OK I think this can be merged as is!

**Comment by jeroen** [comment]
OK I figured it out! All we need to do is add this line to the `PKGBUILD`:

```
-DPREFIX_INSTALL_DIR=${MINGW_PREFIX} \
```

This macro is used in side `mariadb_config.exe`. @stahta01  do you want to add this to your PR or should I make a new PR?

**Comment by stahta01** [comment]
Why don't you make a new pull. Post in this one after you do and I will close it then.

Tim S.

**Comment by jeroen** [comment]
@stahta01 OK I have created a [new PR](https://github.com/Alexpux/MINGW-packages/pull/2702). Thanks again for your help!

**Pull request closed without merging**
