### PR TITLE
python3: Update to 3.6.1

### PR DESCRIPTION
**Pull request by lazka**
The patches starting with 16 are new to fix the build.
Some no longer relevant patches were dropped, the rest is just refreshed.

### CODE REVIEW

**Comment by lazka** [comment]
Not sure how updating Python gets handled, bump pkgrel for all deps?. The following packages depend on it:

```
mingw-w64-blender
mingw-w64-boost
mingw-w64-gedit
mingw-w64-gedit-plugins
mingw-w64-git-repo
mingw-w64-goocanvas
mingw-w64-graphene
mingw-w64-lensfun
mingw-w64-libbotan
mingw-w64-libepoxy
mingw-w64-libftdi
mingw-w64-libgit2-glib
mingw-w64-libpeas
mingw-w64-libplist
mingw-w64-meson
mingw-w64-miniupnpc
mingw-w64-openscenegraph
mingw-w64-pycairo
mingw-w64-pygobject
mingw-w64-pygobject2
mingw-w64-pyqt4
mingw-w64-pyqt5
mingw-w64-pyside-qt4
mingw-w64-python-appdirs
mingw-w64-python-beaker
mingw-w64-python-beautifulsoup4
mingw-w64-python-bsddb3
mingw-w64-python-characteristic
mingw-w64-python-colorama
mingw-w64-python-csssselect
mingw-w64-python-cvxopt
mingw-w64-python-cx_Freeze
mingw-w64-python-cycler
mingw-w64-python-decorator
mingw-w64-python-distutils-extra
mingw-w64-python-docutils
mingw-w64-python-funcsigs
mingw-w64-python-html5lib
mingw-w64-python-httplib2
mingw-w64-python-icu
mingw-w64-python-idna
mingw-w64-python-imagesize
mingw-w64-python-ipykernel
mingw-w64-python-ipython_genutils
mingw-w64-python-jdcal
mingw-w64-python-jsonschema
mingw-w64-python-jupyter_console
mingw-w64-python-jupyter_core
mingw-w64-python-lhafile
mingw-w64-python-lxml
mingw-w64-python-markupsafe
mingw-w64-python-mistune
mingw-w64-python-mock
mingw-w64-python-networkx
mingw-w64-python-numpy
mingw-w64-python-packaging
mingw-w64-python-path
mingw-w64-python-pdfrw
mingw-w64-python-pgen2
mingw-w64-python-pillow
mingw-w64-python-pip
mingw-w64-python-pretend
mingw-w64-python-psutil
mingw-w64-python-py
mingw-w64-python-pyasn1
mingw-w64-python-pyasn1-modules
mingw-w64-python-pycparser
mingw-w64-python-pyparsing
mingw-w64-python-pytest
mingw-w64-python-pytz
mingw-w64-python-pywin32
mingw-w64-python-pyzmq
mingw-w64-python-qtconsole
mingw-w64-python-reportlab
mingw-w64-python-requests
mingw-w64-python-rst2pdf
mingw-w64-python-setuptools
mingw-w64-python-simplegeneric
mingw-w64-python-six
mingw-w64-python-snowballstemmer
mingw-w64-python-sphinx-alabaster-theme
mingw-w64-python-sphinx_rtd_theme
mingw-w64-python-sqlitedict
mingw-w64-python-wcwidth
mingw-w64-python-webencodings
mingw-w64-python-win_unicode_console
mingw-w64-python-xlsxwriter
mingw-w64-python-yaml
mingw-w64-python-zope.event
mingw-w64-python-zope.interface
mingw-w64-shiboken-qt4
mingw-w64-sip
mingw-w64-swig
mingw-w64-waf
```

**Comment by Alexpux** [comment]
I'm in hospital so this week can't do anything

**Comment by lazka** [comment]
There's no rush. Get well!

**Comment by lazka** [comment]
The blender build fails here as well in the same way on master. Any idea welcome.

**Comment by mati865** [comment]
@lazka looks like too long path issue.

**Comment by lazka** [comment]
Thanks. Reducing the path length didn't help afaics.

I think oslc.exe from openshadinglanguage is broken as it doesn't do anything. Rebuilding openshadinglanguage itself also fails for the same reason. Maybe because I'm on Windows 7?

Anyway, I assume this is not related to the Python update so I'm ignoring this for now.

**Comment by lazka** [comment]
Thanks. If there are any problems please ping me and I'll have a look.

**Comment by lazka** [comment]
Having run some test suites of my projects now I get occasionally segfaults in the ssl module (in do_handshake), but not when run under gdb. Maybe 3.6.2rc1 which should be released next week will help..

**Comment by mingwandroid** [comment]
Thank you for helping out on this @lazka, it's one of the trickiest packages we have (as I'm sure you're well aware).

**Comment by lazka** [comment]
No problem, thanks for taking my patches :)

I've tracked the problem down to the faulthandler module. Calling faulthandler.enable() which I use in my test suites to get crash stacktraces, results in random segfaults in other places. There have been fixes for faulthandler+Windows in CPython which should be part of the upcoming 3.6.2 release, so I'm hoping that this is fixed already.

I don't think faulthandler is that commonly used, and having all my (personal) test suites pass now I feel confident with the update.

**Pull request merged**
