### PR TITLE
Rust 1.15

### PR DESCRIPTION
**Pull request by hcorion**
Self explanatory.

### CODE REVIEW

**Comment by Alexpux** [comment]
@hcorion, next time I will not accept pull request from you if you not verify building yourself. Why I need spend my time to fix everything?

**Comment by mati865** [comment]
@Alexpux do you know what happened with AppVeyor? 19 days ago it got stuck and every build is queued.
BTW what was the error with Rust?

**Comment by Alexpux** [comment]
@mati865, I dont know what with AppVeyour.
Rust is completely broken for build. I'm rebase patches but need more work

**Comment by Alexpux** [comment]
I'm push some fixes.

**Comment by hcorion** [comment]
Sorry. I recently moved to Linux and it takes like 10 minutes just to boot into windows and wine can't run it. I'll make sure to test next time.

**Comment by mati865** [comment]
Mingw python `subprocess.Popen(['/mingw64/bin/cargo.exe', 'build', '--manifest-path', 'D:/projekty/msys2/MINGW-packages/mingw-w64-rust/src/rustc-1.15.0-src/src/bootsrap/Cargo.toml'], env` fails because it doesn't understand short path like `/mingw64/bin/cargo.exe`.
I'll try rolling back to old build system (`--disable-rustbuild`) to get 1.15.1 working and if I have enough time I'll fix new build system.

**Comment by hcorion** [comment]
I don't know if `--disable-rustbuild` even does anything, see issue https://github.com/rust-lang/rust/issues/39762 and has been removed (after 1.15.1 release) https://github.com/rust-lang/rust/commit/6194a7643c799c280c762917d8204275a2898f47

**Comment by hcorion** [comment]
Perhaps has something to do with commit https://github.com/rust-lang/rust/commit/25adc4e82ee405127beff6e200499122ed2099dc

**Pull request merged**
