### PR TITLE
mingw-w64-gcc-git: Add gcc-7-branch.

### PR DESCRIPTION
**Pull request by lhmouse**

### CODE REVIEW

**Comment by lhmouse** [comment]
@Alexpux @niXman This takes the place of #2426 .

**Comment by Alexpux** [comment]
You miss 0017 patch in commit

**Comment by lhmouse** [comment]
Yeah I had missed it. I have added it now.

**Comment by niXman** [comment]
@lhmouse @Alexpux Please change my email to github.nixman@protonmail.com

**Comment by lhmouse** [comment]
@Alexpux  Would you please change that?

**Comment by Alexpux** [comment]
ok

**Comment by niXman** [comment]
This [patch](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gcc-git/0017-gcc-7-branch-Enable-std-experimental-filesystem.patch) is broken because the fs-win32.h/fs-posix.h files are not included into this patch.

**Comment by niXman** [comment]
original patch: https://github.com/niXman/mingw-builds/blob/develop/patches/gcc/gcc-7-filesystem.patch

**Comment by Alexpux** [comment]
@lhmouse, fix patch

**Comment by lhmouse** [comment]
Done in #2452 .

**Pull request merged**
