### PR TITLE
icu: update to 60rc

### PR DESCRIPTION
**Pull request by Adsun701**
This updates icu to the latest version, 60rc.

### CODE REVIEW

**Comment by mati865** [comment]
@Ede123, it breaks XP/Vista support. What do you think?

**Comment by Ede123** [comment]
For one we certainly should wait for the final release instead of relying on a release candidate.

Regarding XP support it's a bit more complicated...
* In an ideal world it would be great to say goodbye to XP for good. Objectively people *should* stop using it and I'd be totally fine with dropping XP support.
* In the *real* world however it seems a lot of people are still using Windows XP these days.<br/>As the maintainer of the Windows builds of Inkscape  (why depends on ICU) this change would make my life a lot harder. I'd either have to tell those people that Inkscape 0.92.2 is the last version they can use (probably very unpopular) or I'd have to start to maintain my own builds of ICU and the dependent libraries [!] which is obviously possible but means a lot of work and additional infrastructure as well as more complicated build instructions for new developers which I had hoped to eliminate by using an MSYS2 build environment.

I assume other projects might be affected by such a change as well?

One thing I also can not judge is the drop of Vista compatibility (Windows 7 still seems supported) and how many people it might affect.

**Comment by peterbud** [comment]
The support for XP has ended more than 3 years ago in 2014. I believe it does not make too much sense to make significant efforts to keep supporting an OS which is 15+ years old, and not even the manufacturer supports anymore.

**Comment by lazka** [comment]
> I'd either have to tell those people that Inkscape 0.92.2 is the last version they can use (probably very unpopular)

What makes you think that? They are already using lots of unsupported and insecure software without any way to update.

**Comment by Ede123** [comment]
As I said: You don't have to convince me but the users of the software we build...

Personally I won't shed tears over XP, some users certainly will (if it's a "relevant" amount - who knows - you always hear those few who make the most noise...)

If the MSYS2 project as a whole decides it's time to move on so be it - I'd just prefer if people took a moment to think before dropping XP support for ideological reasons. (E.g. @peterbud you're creating darktable - have you asked your users if there are some still using XP?)

> > I'd either have to tell those people that Inkscape 0.92.2 is the last version they can use (probably very unpopular)
> 
> What makes you think that?

The [mailing list thread on inkscape-devel](http://inkscape.13.x6.nabble.com/Roadmap-for-Inkscape-0-93-on-Windows-GTK3-devlibs-MSYS2-and-support-for-Windows-XP-tt4979046.html) I created some time ago when I started to switch the current development version (i.e. future 0.93) of Inkscape to use MSYS2 and mentioned we won't be able to support XP because GTK+3 does not support it (even then people started to complain and argue why XP still had its right to exist when I specifically explained that we *can't* support it).<br/>
Back then I got people of my back explaining it would only affect the development version but not 0.92.x stable branch.

**Comment by lazka** [comment]
Hm, thanks for the info. I don't think that people on a mailing list are a good representation of a software user base, but I can understand that you want to keep active people involved in the development/community happy.

btw glib has dropped XP support now, so the release in 5 months will be win7+

**Comment by peterbud** [comment]
@Ede123 I have not asked darktable users whether they use WinXP or Win95. 

Just one analogy which I believe is interesting: darktable is not being updated for Ubuntu 14.04 anymore, so if you are on that version (which BTW has been released as recently as 2014!), you stuck with version 2.0.7. See more details [here](https://launchpad.net/~pmjdebruijn/+archive/ubuntu/darktable-release)

So in other words if you keep an old version of OS is fine, but then you will only get an old version of the software. If you want tough you can try to build it for yourself, but there are good reasons why old OS versions cannot build new versions of software.

**Comment by lazka** [comment]
Suggestion: Leave this until 2018-03-14, when glib without XP support is released and reevaluate then.

**Comment by Ede123** [comment]
@lazka Your suggestion would certainly have my support (I kind of assumed this would be obvious, sorry if it wasn't).

Whatever happens I want to release at least an Inkscape 0.92.3 with XP support as 0.92.2 was the first release built with MSYS2 and some issues related to this switch were discovered and solved in the meantime.
Unfortunately I'm not even able to build for XP right now due to some mingw-w64 issue (which linked `_time32` which seems not to be available on XP; not sure if this was publicly discussed anywhere).

Related question: Does anybody know how long old packages are kept in the repos? Otherwise I'd just save the package databases once the build is successful again to make sure I have a backup plan available...

**Comment by mati865** [comment]
You can browse repository, there still are packages uploaded years ago.

22.11.2017 21:24 "Eduard Braun" <notifications@github.com> napisał(a):

**Comment by lazka** [comment]
glib requiring Win7+ is out: https://ftp.acc.umu.se/pub/GNOME/sources/glib/2.56/

**Comment by lazka** [comment]
new glib is in the repos

**Comment by lazka** [comment]
3cd54ad32894fe5bb7

**Pull request closed without merging**
