### PR TITLE
 New package: python3-jupyter-notebook (Version: 5.5.0) 

### PR DESCRIPTION
**Pull request by peterbud**
Please note that can be built only without logging - a `bower `error will stop building if you use `-L` switch

### CODE REVIEW

**Comment by Alexpux** [comment]
@peterbud notebook not buildable for me:
````
==> Starting build()...
running build
running build_py
running jsversion
running js
running jsdeps
> bower install --allow-root --config.interactive=false
bower preact#*              not-cached https://unpkg.com/preact@^7.2.0/dist/preact.min.js#*
bower preact#*                 resolve https://unpkg.com/preact@^7.2.0/dist/preact.min.js#*
bower proptypes#*           not-cached https://unpkg.com/proptypes@^0.14.4/index.js#*
bower proptypes#*              resolve https://unpkg.com/proptypes@^0.14.4/index.js#*
bower preact-compat#*       not-cached https://unpkg.com/preact-compat@^3.14.3/dist/preact-compat.min.js#*
bower preact-compat#*          resolve https://unpkg.com/preact-compat@^3.14.3/dist/preact-compat.min.js#*
bower xterm.js#*            not-cached https://unpkg.com/xterm@~3.1.0/dist/xterm.js#*
bower xterm.js#*               resolve https://unpkg.com/xterm@~3.1.0/dist/xterm.js#*
bower xterm.js-css#*        not-cached https://unpkg.com/xterm@~3.1.0/dist/xterm.css#*
bower xterm.js-css#*           resolve https://unpkg.com/xterm@~3.1.0/dist/xterm.css#*
bower xterm.js-fit#*        not-cached https://unpkg.com/xterm@~3.1.0/dist/addons/fit/fit.js#*
bower xterm.js-fit#*           resolve https://unpkg.com/xterm@~3.1.0/dist/addons/fit/fit.js#*
bower backbone#~1.2         not-cached https://github.com/components/backbone.git#~1.2
bower backbone#~1.2            resolve https://github.com/components/backbone.git#~1.2
bower bootstrap#~3.3        not-cached https://github.com/components/bootstrap.git#~3.3
bower bootstrap#~3.3           resolve https://github.com/components/bootstrap.git#~3.3
bower codemirror#~5.35      not-cached https://github.com/components/codemirror.git#~5.35
bower codemirror#~5.35         resolve https://github.com/components/codemirror.git#~5.35
bower font-awesome#~4.7.0   not-cached https://github.com/components/font-awesome.git#~4.7.0
bower font-awesome#~4.7.0      resolve https://github.com/components/font-awesome.git#~4.7.0
bower jquery#~2.2           not-cached https://github.com/components/jquery.git#~2.2
bower jquery#~2.2              resolve https://github.com/components/jquery.git#~2.2
bower jquery-ui#~1.10       not-cached https://github.com/components/jqueryui.git#~1.10
bower jquery-ui#~1.10          resolve https://github.com/components/jqueryui.git#~1.10
bower MathJax#~2.6          not-cached https://github.com/components/MathJax.git#~2.6
bower MathJax#~2.6             resolve https://github.com/components/MathJax.git#~2.6
bower underscore#~1.8.3     not-cached https://github.com/components/underscore.git#~1.8.3
bower underscore#~1.8.3        resolve https://github.com/components/underscore.git#~1.8.3
bower preact#*                download https://unpkg.com/preact@^7.2.0/dist/preact.min.js
bower proptypes#*             download https://unpkg.com/proptypes@^0.14.4/index.js
bower xterm.js#*              download https://unpkg.com/xterm@~3.1.0/dist/xterm.js
bower preact-compat#*         download https://unpkg.com/preact-compat@^3.14.3/dist/preact-compat.min.js
bower xterm.js-fit#*          download https://unpkg.com/xterm@~3.1.0/dist/addons/fit/fit.js
bower xterm.js-css#*          download https://unpkg.com/xterm@~3.1.0/dist/xterm.css
bower requirejs-text#~2.0.15       not-cached https://github.com/requirejs/text.git#~2.0.15
bower requirejs-text#~2.0.15          resolve https://github.com/requirejs/text.git#~2.0.15
bower moment#~2.19.3               not-cached https://github.com/moment/moment.git#~2.19.3
bower moment#~2.19.3                  resolve https://github.com/moment/moment.git#~2.19.3
bower marked#~0.3                  not-cached https://github.com/chjj/marked.git#~0.3
bower marked#~0.3                     resolve https://github.com/chjj/marked.git#~0.3
bower es6-promise#~1.0             not-cached https://github.com/components/es6-promise.git#~1.0
bower es6-promise#~1.0                resolve https://github.com/components/es6-promise.git#~1.0
bower jed#~1.1.1                   not-cached https://github.com/SlexAxton/Jed.git#~1.1.1
bower jed#~1.1.1                      resolve https://github.com/SlexAxton/Jed.git#~1.1.1
bower text-encoding#~0.1           not-cached https://github.com/inexorabletash/text-encoding.git#~0.1
bower text-encoding#~0.1              resolve https://github.com/inexorabletash/text-encoding.git#~0.1
bower requirejs-plugins#~1.0.3     not-cached https://github.com/millermedeiros/requirejs-plugins.git#~1.0.3
bower requirejs-plugins#~1.0.3        resolve https://github.com/millermedeiros/requirejs-plugins.git#~1.0.3
bower google-caja#5669             not-cached https://github.com/minrk/google-caja-bower.git#5669
bower google-caja#5669                resolve https://github.com/minrk/google-caja-bower.git#5669
bower requirejs#~2.1               not-cached https://github.com/jrburke/requirejs-bower.git#~2.1
bower requirejs#~2.1                  resolve https://github.com/jrburke/requirejs-bower.git#~2.1
bower bootstrap-tour#0.9.0         not-cached https://github.com/sorich87/bootstrap-tour.git#0.9.0
bower bootstrap-tour#0.9.0            resolve https://github.com/sorich87/bootstrap-tour.git#0.9.0
bower preact-compat#*                resolved https://unpkg.com/preact-compat@^3.14.3/dist/preact-compat.min.js#e-tag:W/"24d1-16
bower backbone#~1.2                  download https://github.com/components/backbone/archive/1.2.0.tar.gz
bower proptypes#*                    resolved https://unpkg.com/proptypes@^0.14.4/index.js#e-tag:W/"2e56-15
bower jquery-typeahead#~2.0.0      not-cached https://github.com/running-coder/jquery-typeahead.git#~2.0.0
bower jquery-typeahead#~2.0.0         resolve https://github.com/running-coder/jquery-typeahead.git#~2.0.0
bower font-awesome#~4.7.0            download https://github.com/components/font-awesome/archive/4.7.0.tar.gz
bower codemirror#~5.35               download https://github.com/components/codemirror/archive/5.35.0.tar.gz
bower bootstrap#~3.3                 download https://github.com/components/bootstrap/archive/3.3.7.tar.gz
bower jquery-ui#~1.10                download https://github.com/components/jqueryui/archive/1.10.4.tar.gz
bower preact#*                       resolved https://unpkg.com/preact@^7.2.0/dist/preact.min.js#e-tag:W/"246b-15
bower xterm.js-fit#*                 resolved https://unpkg.com/xterm@~3.1.0/dist/addons/fit/fit.js#e-tag:W/"b15-161
bower xterm.js-css#*                 resolved https://unpkg.com/xterm@~3.1.0/dist/xterm.css#e-tag:W/"e0b-161
bower underscore#~1.8.3              download https://github.com/components/underscore/archive/1.8.3.tar.gz
bower jquery#~2.2                    download https://github.com/components/jquery/archive/2.2.4.tar.gz
bower MathJax#~2.6                   download https://github.com/components/MathJax/archive/2.6.0.tar.gz
bower xterm.js#*                     resolved https://unpkg.com/xterm@~3.1.0/dist/xterm.js#e-tag:W/"3fd9c-1
bower marked#~0.3                    download https://github.com/chjj/marked/archive/v0.3.19.tar.gz
bower backbone#~1.2                   extract archive.tar.gz
bower backbone#~1.2                  resolved https://github.com/components/backbone.git#1.2.0
bower moment#~2.19.3                 download https://github.com/moment/moment/archive/2.19.4.tar.gz
bower underscore#*                 not-cached https://github.com/jashkenas/underscore.git#*
bower underscore#*                    resolve https://github.com/jashkenas/underscore.git#*
bower jquery#*                     not-cached https://github.com/jquery/jquery-dist.git#*
bower jquery#*                        resolve https://github.com/jquery/jquery-dist.git#*
bower es6-promise#~1.0               download https://github.com/components/es6-promise/archive/v1.0.0.tar.gz
bower jed#~1.1.1                     download https://github.com/SlexAxton/Jed/archive/1.1.1.tar.gz
bower requirejs-text#~2.0.15         download https://github.com/requirejs/text/archive/2.0.15.tar.gz
bower underscore#~1.8.3               extract archive.tar.gz
bower underscore#~1.8.3              resolved https://github.com/components/underscore.git#1.8.3
bower font-awesome#~4.7.0             extract archive.tar.gz
bower bootstrap#~3.3                  extract archive.tar.gz
bower text-encoding#~0.1             download https://github.com/inexorabletash/text-encoding/archive/v0.1.0.tar.gz
bower requirejs-plugins#~1.0.3       download https://github.com/millermedeiros/requirejs-plugins/archive/v1.0.3.tar.gz
bower codemirror#~5.35                extract archive.tar.gz
bower google-caja#5669               download https://github.com/minrk/google-caja-bower/archive/5669.0.0.tar.gz
bower font-awesome#~4.7.0            resolved https://github.com/components/font-awesome.git#4.7.0
bower jquery#~2.2                     extract archive.tar.gz
bower jquery#~2.2                    resolved https://github.com/components/jquery.git#2.2.4
bower jquery-ui#~1.10                 extract archive.tar.gz
bower requirejs#~2.1                 download https://github.com/jrburke/requirejs-bower/archive/2.1.22.tar.gz
bower bootstrap-tour#0.9.0           download https://github.com/sorich87/bootstrap-tour/archive/v0.9.0.tar.gz
bower es6-promise#~1.0                extract archive.tar.gz
bower es6-promise#~1.0               resolved https://github.com/components/es6-promise.git#1.0.0
bower bootstrap#~3.3                 resolved https://github.com/components/bootstrap.git#3.3.7
bower requirejs-text#~2.0.15          extract archive.tar.gz
bower requirejs-text#~2.0.15         resolved https://github.com/requirejs/text.git#2.0.15
bower jquery-typeahead#~2.0.0        download https://github.com/running-coder/jquery-typeahead/archive/2.0.0.tar.gz
bower jquery#*                       download https://github.com/jquery/jquery-dist/archive/3.3.1.tar.gz
bower underscore#*                   download https://github.com/jashkenas/underscore/archive/1.9.1.tar.gz
bower marked#~0.3                     extract archive.tar.gz
bower jed#~1.1.1                      extract archive.tar.gz
bower jed#~1.1.1                     resolved https://github.com/SlexAxton/Jed.git#1.1.1
bower requirejs-plugins#~1.0.3        extract archive.tar.gz
bower requirejs-plugins#~1.0.3   invalid-meta for:C:\Users\Alexx\AppData\Local\Temp\WARLOCK-Alexx\bower\ad74b92b76f0adeb7f6f6fe62454cb7c-134348-KvxUjJ\bower.json
bower requirejs-plugins#~1.0.3   invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["src/async.js","src/depend.js","src/font.js","src/goog.js","src/image.js","src/json.js","src/mdown.js","src/noext.js","src/propertyParser.js","lib/Markdown.Converter.js","lib/text.js"]
bower moment#~2.19.3                  extract archive.tar.gz
bower requirejs-plugins#~1.0.3       resolved https://github.com/millermedeiros/requirejs-plugins.git#1.0.3
bower marked#~0.3                    resolved https://github.com/chjj/marked.git#0.3.19
bower requirejs#~2.1                  extract archive.tar.gz
bower requirejs#~2.1                 resolved https://github.com/jrburke/requirejs-bower.git#2.1.22
bower codemirror#~5.35               resolved https://github.com/components/codemirror.git#5.35.0
bower jquery-typeahead#~2.0.0         extract archive.tar.gz
bower jquery-typeahead#~2.0.0    invalid-meta for:C:\Users\Alexx\AppData\Local\Temp\WARLOCK-Alexx\bower\382d6e15dee80d634318874dac20c576-134348-thQffs\bower.json
bower jquery-typeahead#~2.0.0    invalid-meta The "description" is too long, the limit is 140 characters
bower jquery-typeahead#~2.0.0    invalid-meta The "main" field cannot contain minified files
bower jquery-typeahead#~2.0.0        resolved https://github.com/running-coder/jquery-typeahead.git#2.0.0
bower google-caja#5669                extract archive.tar.gz
bower jquery#*                        extract archive.tar.gz
bower underscore#*                    extract archive.tar.gz
bower jquery-ui#~1.10                resolved https://github.com/components/jqueryui.git#1.10.4
bower text-encoding#~0.1              extract archive.tar.gz
bower google-caja#5669               resolved https://github.com/minrk/google-caja-bower.git#5669.0.0
bower underscore#*                   resolved https://github.com/jashkenas/underscore.git#1.9.1
bower text-encoding#~0.1         invalid-meta for:C:\Users\Alexx\AppData\Local\Temp\WARLOCK-Alexx\bower\833568e05e8f47d11ed8440f1d4c6bfd-134348-9qR0O1\bower.json
bower text-encoding#~0.1         invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["lib/encoding.js","lib/encoding-indexes.js"]
bower text-encoding#~0.1             mismatch Version declared in the json (0.0.0) is different than the resolved one (0.1.0)
bower text-encoding#~0.1             resolved https://github.com/inexorabletash/text-encoding.git#0.1.0
bower jquery#*                       resolved https://github.com/jquery/jquery-dist.git#3.3.1
bower moment#~2.19.3                 resolved https://github.com/moment/moment.git#2.19.4
bower bootstrap-tour#0.9.0            extract archive.tar.gz
bower bootstrap-tour#0.9.0           resolved https://github.com/sorich87/bootstrap-tour.git#0.9.0
bower MathJax#~2.6                    extract archive.tar.gz
bower MathJax#~2.6               invalid-meta for:C:\Users\Alexx\AppData\Local\Temp\WARLOCK-Alexx\bower\8e3d2eb85a42d64f91511af6cc70f6e0-134348-L4oBfn\bower.json
bower MathJax#~2.6               invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower MathJax#~2.6                   resolved https://github.com/components/MathJax.git#2.6.0
bower preact-compat#*                 install preact-compat#e-tag:W/"24d1-16
bower proptypes#*                     install proptypes#e-tag:W/"2e56-15
bower preact#*                        install preact#e-tag:W/"246b-15
bower xterm.js-fit#*                  install xterm.js-fit#e-tag:W/"b15-161
bower xterm.js-css#*                  install xterm.js-css#e-tag:W/"e0b-161
bower xterm.js#*                      install xterm.js#e-tag:W/"3fd9c-1
bower backbone#~1.2                   install backbone#1.2.0
bower underscore#~1.8.3               install underscore#1.8.3
bower font-awesome#~4.7.0             install font-awesome#4.7.0
bower jquery#~2.2                     install jquery#2.2.4
bower es6-promise#~1.0                install es6-promise#1.0.0
bower bootstrap#~3.3                  install bootstrap#3.3.7
bower requirejs-text#~2.0.15          install requirejs-text#2.0.15
bower jed#~1.1.1                      install jed#1.1.1
bower requirejs-plugins#~1.0.3        install requirejs-plugins#1.0.3
bower marked#~0.3                     install marked#0.3.19
bower requirejs#~2.1                  install requirejs#2.1.22
bower codemirror#~5.35                install codemirror#5.35.0
bower jquery-typeahead#~2.0.0         install jquery-typeahead#2.0.0
bower jquery-ui#~1.10                 install jquery-ui#1.10.4
bower google-caja#5669                install google-caja#5669.0.0
bower text-encoding#~0.1              install text-encoding#0.1.0
bower moment#~2.19.3                  install moment#2.19.4
bower bootstrap-tour#0.9.0            install bootstrap-tour#0.9.0
bower MathJax#~2.6                    install MathJax#2.6.0

preact-compat#e-tag:W/"24d1-16 notebook\static\components\preact-compat

proptypes#e-tag:W/"2e56-15 notebook\static\components\proptypes

preact#e-tag:W/"246b-15 notebook\static\components\preact

xterm.js-fit#e-tag:W/"b15-161 notebook\static\components\xterm.js-fit

xterm.js-css#e-tag:W/"e0b-161 notebook\static\components\xterm.js-css

xterm.js#e-tag:W/"3fd9c-1 notebook\static\components\xterm.js

backbone#1.2.0 notebook\static\components\backbone
├── jquery#2.2.4
└── underscore#1.8.3

underscore#1.8.3 notebook\static\components\underscore

font-awesome#4.7.0 notebook\static\components\font-awesome

jquery#2.2.4 notebook\static\components\jquery

es6-promise#1.0.0 notebook\static\components\es6-promise

bootstrap#3.3.7 notebook\static\components\bootstrap
└── jquery#2.2.4

requirejs-text#2.0.15 notebook\static\components\requirejs-text

jed#1.1.1 notebook\static\components\jed

requirejs-plugins#1.0.3 notebook\static\components\requirejs-plugins

marked#0.3.19 notebook\static\components\marked

requirejs#2.1.22 notebook\static\components\requirejs

codemirror#5.35.0 notebook\static\components\codemirror

jquery-typeahead#2.0.0 notebook\static\components\jquery-typeahead

jquery-ui#1.10.4 notebook\static\components\jquery-ui
└── jquery#2.2.4

google-caja#5669.0.0 notebook\static\components\google-caja

text-encoding#0.1.0 notebook\static\components\text-encoding

moment#2.19.4 notebook\static\components\moment

bootstrap-tour#0.9.0 notebook\static\components\bootstrap-tour
├── bootstrap#3.3.7
└── jquery#2.2.4

MathJax#2.6.0 notebook\static\components\MathJax
Rebuilding C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0/notebook/static/notebook/js/main.min.js
> node tools/build-main.js notebook
Rebuilding C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0/notebook/static/edit/js/main.min.js
Rebuilding C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0/notebook/static/tree/js/main.min.js
Rebuilding C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0/notebook/static/terminal/js/main.min.js
> node tools/build-main.js edit
Rebuilding C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0/notebook/static/auth/js/main.min.js
> node tools/build-main.js tree
> node tools/build-main.js auth
> node tools/build-main.js terminal
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repo\mingw-w64-python3-jupyter-notebook\src\notebook-5.5.0\tools\build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repo\mingw-w64-python3-jupyter-notebook\src\notebook-5.5.0\tools\build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repo\mingw-w64-python3-jupyter-notebook\src\notebook-5.5.0\tools\build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repo\mingw-w64-python3-jupyter-notebook\src\notebook-5.5.0\tools\build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repo\mingw-w64-python3-jupyter-notebook\src\notebook-5.5.0\tools\build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm unavailable
rebuilding js and css failed. The following required files are missing: ['notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    main()
  File "setup.py", line 147, in main
    setup(**setup_args)
  File "C:/building/msys32/mingw64/lib/python3.7/site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0\setupbase.py", line 597, in run
    raise e
  File "C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0\setupbase.py", line 587, in run
    self.distribution.run_command('js')
  File "C:/building/msys32/mingw64/lib/python3.7\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0\setupbase.py", line 534, in run
    pool.map(self.build_main, self.apps)
  File "C:/building/msys32/mingw64/lib/python3.7\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:/building/msys32/mingw64/lib/python3.7\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:/building/msys32/mingw64/lib/python3.7\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:/building/msys32/mingw64/lib/python3.7\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0\setupbase.py", line 527, in build_main
    run(['node', 'tools/build-main.js', name])
  File "C:/repo/mingw-w64-python3-jupyter-notebook/src/notebook-5.5.0\setupbase.py", line 338, in run
    return check_call(cmd, *args, **kwargs)
  File "C:/building/msys32/mingw64/lib/python3.7\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', 'tools/build-main.js', 'auth']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().

````

**Comment by peterbud** [comment]
@Alexpux , which version of `npm ` / `nodejs` is installed? You need `8.11.1-2`, see #3793 
```

$ pacman -Ss nodejs
mingw32/mingw-w64-i686-nodejs 8.11.1-1
    Evented I/O for V8 javascript (mingw-w64)
mingw64/mingw-w64-x86_64-nodejs 8.11.1-1 [installed: 8.11.1-2]
    Evented I/O for V8 javascript (mingw-w64)
```

**Comment by Alexpux** [comment]
@peterbud I have the same version installed

**Comment by peterbud** [comment]
I have managed to localize the problem with 32-bit version of the build, at least I have the same symptom. While I try to figure out the issue, could you give a try with the 64-bit build? Is that working for you or shows the same error?

**Comment by Alexpux** [comment]
I post error from 64 not 32 build

**Pull request merged**
