### PR TITLE
mingw-w64-perl - 5.26.0 - Update to latest version.  Move build to pa…

### PR DESCRIPTION
**Pull request by JPeterMugaas**
…ckage since pkgdir is not the same value in build() as it is in package().  add and use helper macros.

mingw-w64-lcov - 1.13.\ - Update to latest version and use helper macros.

### CODE REVIEW

**Comment by peterbud** [comment]
My latest information was that the `mingw64` perl is broken, and we should use the msys2 version. Is this version working better? How have you tested?

**Comment by JPeterMugaas** [comment]
Unfortunately, it still is broken although I'm still not sure why.  I would also point out that this package does interfere with some gtk build stuff and it has to do with autoconf and intltool.  My thinking is this, you probably will need two separate sets of perl libraries (or three if have both i686 and x86_64).  Then you could have a mingw-perl set of libraries along with the msys2 version.  Unfortunately, this seems have a bad habit of accessing the msys perl libraries and that's not desirable.

What I did was attempt to help matters by updating to the latest version of perl.  That distribution was based on 5.22 which is outdated.  Right now, I'm working on a 5.26 version of perl for msys2 and so far so good.

**Comment by mingwandroid** [comment]
Perl 5.26 changed the handling of @INC (see http://blogs.perl.org/users/sawyer_x/2017/05/perl-5260-is-now-available.html)

As you can probably guess this breaks a *lot* of things. We need to update to automake 1.15.1 for example. I ran into a few more but the details elude me (it *probably* broke git).

**Comment by JPeterMugaas** [comment]
I have gone ahead and made a MSYS2 version of Perl 5.26 at https://github.com/Alexpux/MSYS2-packages/pull/971 .

**Pull request closed without merging**
