### PR TITLE
[WIP] clang: update to 3.9.0

### PR DESCRIPTION
**Pull request by mati865**
Looks like a huge mess but works better than old Clang (except `_flat128` regression).
Rebased on new @martell patches and applied old and own patches where needed.

#### Compile with GCC, Clang doesn't like mingw-w64 headers.
Example:
```
In file included from D:/projekty/msys2/MATI865-packages/mingw-w64-clang/src/llvm-3.9.0.src/projects/libcxx/src/thread.cpp:35:
In file included from D:\msys64\mingw64\x86_64-w64-mingw32\include\windows.h:114:
D:\msys64\mingw64\x86_64-w64-mingw32\include\stralign.h:121:37: error: cannot initialize return object of type 'PUWSTR_C' (aka 'wchar_t *') with an rvalue of type 'const wchar_t *'
    if(WSTR_ALIGNED(String)) return wcschr((PCWSTR)String,Character);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\msys64\mingw64\x86_64-w64-mingw32\include\stralign.h:125:37: error: cannot initialize return object of type 'PUWSTR_C' (aka 'wchar_t *') with an rvalue of type 'const wchar_t *'
    if(WSTR_ALIGNED(String)) return wcsrchr((PCWSTR)String,Character);
```

### TODO:
- [ ] lldb (almost compiles)
- [ ] libunwind (untested)
- [ ] testsuite (untested)

### Issues:
- [x] https://github.com/Alexpux/MINGW-packages/issues/886
- [x] https://github.com/Alexpux/MINGW-packages/issues/1541 (fix sent to mingw-w64)
- [x] https://github.com/Alexpux/MINGW-packages/issues/1669
- [ ] https://github.com/Alexpux/MINGW-packages/issues/1676 (@martell we need your help)
- [ ] https://github.com/Alexpux/MINGW-packages/issues/1677
- [ ] https://github.com/Alexpux/MINGW-packages/issues/1678
- [x] https://github.com/Alexpux/MINGW-packages/issues/1679 (0018-experimental-workaround-for-limits-bug.patch)
- [ ] when using lld instead of ld apps segfault (we probably need lldb to solve it)

@martell there is problem with `0002-COFF-Fix-short-import-lib-import-name-type-bitshift.patch`: `test/tools/llvm-readobj/Inputs/imports.mangle.coff-x86_64` doesn't exist

EDIT: Tea fails because of outdated cmake
EDIT2: Added lld issue.

### CODE REVIEW

**Comment by martell** [comment]
Adding a note.
We need to back port Reid's fix for libc++abi
https://reviews.llvm.org/rL279786

**Comment by martell** [comment]
Thanks for all the work on this @mati865 btw :)
I assume 0002 is https://reviews.llvm.org/D23540
I'll push that upstream now after running the testbed.

**Comment by mati865** [comment]
@martell, most of patches are your work.
I just had to comment out https://github.com/Alexpux/MINGW-packages/pull/1768/files#diff-fb941abd396fd02f8a6dabb60456016dR94
and add some patches to make it compile with GCC on Windows.
`0041-mingw-w64-hack-and-slash-fixes-for-libc` doesn't work nicely with GCC so I had to patch it with 0042 😄

Libunwind seems important to make libc++abi work but I had no time to even test if it compiles
lldb almost compiles with GCC but it's not as important as getting working Clang

**Comment by martell** [comment]
This is what will replace the 0002 and be pushed to llvm master.
https://gist.github.com/martell/99e00b2f7c1e0bd954455f15a2cfab4f
This won't apply on top of 3.9.0 we can strip it to just the COFF.h change

My main focus for doing this was to get a clang standalone toolchain.
I don't have a high priority on supporting libstdc++ with clang.
So #1677 and #1678 will have to go on the back log for now.

**Comment by martell** [comment]
https://reviews.llvm.org/rL283055
Send Upstream :)

**Comment by vit9696** [comment]
> My main focus for doing this was to get a clang standalone toolchain.
> I don't have a high priority on supporting libstdc++ with clang.

Thanks for your work, but isn't libstdc++ currently the only way to support clang on Windows? I did send you an email questioning the current state of libc++, and it could have gotten lost. However, I do not expect anything to have changed. libc++ would be nice, but getting it work with exceptions is likely going to be years, just like with Linux.

**Comment by mati865** [comment]
Added lld to issues:
> when using lld instead of ld apps segfault (we probably need lldb to solve it)

**Comment by martell** [comment]
lld will not work with a mingw-w64-crt libs build with binutils dlltool.
It complies with the PE COFF spec fully which binutils does not.
That was the reason for the creation of genlib and finally llvm-genlib

**Comment by mati865** [comment]
Ok, I'll try to get lldb building then.
@martell, you are our LLVM expert, feel free to coordinate this work and set priorities.

**Comment by mati865** [comment]
Apparently GCC doesn't support `#pragma comment(lib...)` so we need to add `dbghelp` somewhere in `CMakeLists.txt`, any suggestions?

**Comment by Alexpux** [comment]
@mati865, yes you need add extra link libraries in CMakeLists.txt

**Comment by mati865** [comment]
More fixes with @Alexpux  help.
Currently it fails on linking: http://pastebin.com/xhi2WPag
When it's resolved it will fail here: https://github.com/llvm-mirror/lldb/blob/release_39/tools/lldb-mi/Platform.h#L89

**Comment by mati865** [comment]
Disable lldb to compile it.
The only critical issue is `_float128` and will have to be disabled in Clang somehow.

**Pull request merged**
