### PR TITLE
Sqlite checksum updates

### PR DESCRIPTION
**Pull request by fracting**
Another problem detected by our nice stress testing: https://github.com/Alexpux/MINGW-packages/pull/1077 

(Please wait for CI build result, I haven't test locally yet)

### CODE REVIEW

**Comment by elieux** [comment]
I confirmed the checksums are wrong. I don't see a reason not to merge.

**Comment by fracting** [comment]
Yes, please merge, thanks!

**Comment by vszakats** [comment]
Thank you! I missed the fact that a repository file was checksummed, sorry.

**Comment by vszakats** [comment]
BTW, wouldn't it be worth to switch to SHA256, if we're at this?

**Comment by vszakats** [comment]
use SHA256 and sqlite 3.11.0:

```diff
diff --git a/mingw-w64-sqlite-analyzer/PKGBUILD b/mingw-w64-sqlite-analyzer/PKGBUILD
index 721e4db..b301f53 100644
--- a/mingw-w64-sqlite-analyzer/PKGBUILD
+++ b/mingw-w64-sqlite-analyzer/PKGBUILD
@@ -15,8 +15,8 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
              "${MINGW_PACKAGE_PREFIX}-fossil")
 source=("LICENSE"
         "lemon.patch")
-md5sums=('99ad5d4fba7d423c054b7bc74133253a'
-         '5894795373d34f149a09fb7c7a07c20c')
+sha256sums=('0b76663a90e034f3d7f2af5bfada4cedec5ebc275361899eccc5c18e6f01ff1f'
+            '3549fbdfa29b275c7d3946f621cdb2df4ebdbdb2852fb94b7218ccef4f990a72')
 
 prepare() {
   if [ ! -f sqlite.fossil ]; then
diff --git a/mingw-w64-sqlite3/PKGBUILD b/mingw-w64-sqlite3/PKGBUILD
index eeb4152..132187a 100644
--- a/mingw-w64-sqlite3/PKGBUILD
+++ b/mingw-w64-sqlite3/PKGBUILD
@@ -5,8 +5,8 @@
 _realname=sqlite3
 pkgbase=mingw-w64-${_realname}
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
-_amalgamationver=3100200
-pkgver=3.10.2.0
+_amalgamationver=3110000
+pkgver=3.11.0.0
 pkgrel=1
 pkgdesc="A C library that implements an SQL database engine (mingw-w64)"
 arch=('any')
@@ -18,8 +18,8 @@ depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs"
 makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
 source=("https://www.sqlite.org/2016/sqlite-autoconf-${_amalgamationver}.tar.gz"
         LICENSE)
-sha1sums=('ea4156fc3f6a4a4a2752a5a3ac5c5b3fe7e1a24b'
-          'e2aa07adae13aed713860b74165d3325a18c6792')
+sha1sums=('508d4dcbcf7a7181e95c717a1dc4ae3c0880b3d593be0c4b40abb6c3a0e201fb'
+          '0b76663a90e034f3d7f2af5bfada4cedec5ebc275361899eccc5c18e6f01ff1f')
 options=('!strip' 'staticlibs' '!buildflags')
 
 build() {
```

**Comment by vszakats** [comment]
use SHA256 and sqlite 3.11.0:

```diff
diff --git a/mingw-w64-sqlite-analyzer/PKGBUILD b/mingw-w64-sqlite-analyzer/PKGBUILD
index 721e4db..b301f53 100644
--- a/mingw-w64-sqlite-analyzer/PKGBUILD
+++ b/mingw-w64-sqlite-analyzer/PKGBUILD
@@ -15,8 +15,8 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
              "${MINGW_PACKAGE_PREFIX}-fossil")
 source=("LICENSE"
         "lemon.patch")
-md5sums=('99ad5d4fba7d423c054b7bc74133253a'
-         '5894795373d34f149a09fb7c7a07c20c')
+sha256sums=('0b76663a90e034f3d7f2af5bfada4cedec5ebc275361899eccc5c18e6f01ff1f'
+            '3549fbdfa29b275c7d3946f621cdb2df4ebdbdb2852fb94b7218ccef4f990a72')
 
 prepare() {
   if [ ! -f sqlite.fossil ]; then
diff --git a/mingw-w64-sqlite3/PKGBUILD b/mingw-w64-sqlite3/PKGBUILD
index eeb4152..aedb557 100644
--- a/mingw-w64-sqlite3/PKGBUILD
+++ b/mingw-w64-sqlite3/PKGBUILD
@@ -5,8 +5,8 @@
 _realname=sqlite3
 pkgbase=mingw-w64-${_realname}
 pkgname="${MINGW_PACKAGE_PREFIX}-${_realname}"
-_amalgamationver=3100200
-pkgver=3.10.2.0
+_amalgamationver=3110000
+pkgver=3.11.0.0
 pkgrel=1
 pkgdesc="A C library that implements an SQL database engine (mingw-w64)"
 arch=('any')
@@ -18,8 +18,8 @@ depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs"
 makedepends=("${MINGW_PACKAGE_PREFIX}-gcc")
 source=("https://www.sqlite.org/2016/sqlite-autoconf-${_amalgamationver}.tar.gz"
         LICENSE)
-sha1sums=('ea4156fc3f6a4a4a2752a5a3ac5c5b3fe7e1a24b'
-          'e2aa07adae13aed713860b74165d3325a18c6792')
+sha256sums=('508d4dcbcf7a7181e95c717a1dc4ae3c0880b3d593be0c4b40abb6c3a0e201fb'
+            '0b76663a90e034f3d7f2af5bfada4cedec5ebc275361899eccc5c18e6f01ff1f')
 options=('!strip' 'staticlibs' '!buildflags')
 
 build() {
```

**Comment by fracting** [comment]
Thanks!

I'm waiting https://bugs.wine-staging.com/show_bug.cgi?id=646 to be merge, then do a Wine upgrade in https://hub.docker.com/r/fracting/msys32/ , then upgrade wine-ci.org, once fossil is supported by the Wine version in wine-ci.org, I'll steal your code and update the pull request. It shouldn't take more than one week, i'll take care of that.

**Comment by elieux** [comment]
Okay. Ping the PR afterwards please.

**Comment by fracting** [comment]
Ping.

I steal the code from @vszakats

In theory this should success now, like: http://wine-ci.org/Alexpux/MINGW-packages/127 (force installed mingw-w64-i686-ca-certificates)

In practice, due to a similar issue to https://github.com/Alexpux/MINGW-packages/issues/1086, ca-certificates is not installed, so fossil will fail to clone https link.

Anyway it is ready to be merge now.

Thanks!

**Comment by elieux** [comment]
At least change the commit message.

**Comment by vszakats** [comment]
@fracting Thank you!

Yes, title needs to be changed to 'mingw-w64-sqlite 3.11.0 and checksum update for mingw-w64-sqlite-analyzer' (or similar)

**Comment by fracting** [comment]
Thanks for review! Updated.

**Comment by elieux** [comment]
Verified the new sqlite3 version builds fine.

**Pull request merged**
