### PR TITLE
curl: change dependency from libidn to libidn2 + other minor change

### PR DESCRIPTION
**Pull request by filnet**

### CODE REVIEW

**Comment by Optiligence** [comment]
`ldd (which curl) | grep idn` currently gives
```
        libidn2-0.dll => /mingw64/bin/libidn2-0.dll (0x63d00000)
        libidn-11.dll => /mingw64/bin/libidn-11.dll (0x69540000)
```
is it correct then, to only have idn2 as dependency?

**Comment by mati865** [comment]
Nice catch @Optiligence

**Comment by Alexpux** [comment]
Dependency Walker show only libidn2 dependency

**Comment by filnet** [comment]
Seems like @Optiligence  is correct:

$ ntldd -R  /mingw32/bin/curl
        libcurl-4.dll => D:\msys64\mingw32\bin\libcurl-4.dll (0x00420000)
         libwinpthread-1.dll => D:\msys64\mingw32\bin\libwinpthread-1.dll (0x00380000)
         wldap32.dll => C:\Windows\system32\wldap32.dll (0x00380000)
         libgcc_s_dw2-1.dll => D:\msys64\mingw32\bin\libgcc_s_dw2-1.dll (0x00380000)
         **libidn2-0.dll => D:\msys64\mingw32\bin\libidn2-0.dll (0x00380000)**
          libintl-8.dll => D:\msys64\mingw32\bin\libintl-8.dll (0x003b0000)
           libiconv-2.dll => D:\msys64\mingw32\bin\libiconv-2.dll (0x008a0000)
          libunistring-2.dll => D:\msys64\mingw32\bin\libunistring-2.dll (0x008a0000)
         libnghttp2-14.dll => D:\msys64\mingw32\bin\libnghttp2-14.dll (0x00380000)
         librtmp-1.dll => D:\msys64\mingw32\bin\librtmp-1.dll (0x00380000)
          libgmp-10.dll => D:\msys64\mingw32\bin\libgmp-10.dll (0x00500000)
          libgnutls-30.dll => D:\msys64\mingw32\bin\libgnutls-30.dll (0x008a0000)
           **libidn-11.dll => D:\msys64\mingw32\bin\libidn-11.dll (0x00500000)**

**Comment by Optiligence** [comment]
`gnutls` has `libidn` as dep tho, so it’s fine

**Pull request merged**
