### PR TITLE
[DO NOT MERGE] Update to Rust 1.6

### PR DESCRIPTION
**Pull request by K900**
This should be everything that's needed, but I'm running another build on a clean install to make sure I didn't miss anything

### CODE REVIEW

**Comment by K900** [comment]
Aaaaand it failed on both CI instances, with different error messages. Dis gun b gud.

**Comment by fracting** [comment]
Appveyor CI failure:
```
/c/projects/mingw-packages/mingw-w64-rust/src/rustc-1.6.0/src/jemalloc/configure: line 557: 0: Bad file descriptor
```
This is a known problem of Appveyor, see http://help.appveyor.com/discussions/problems/4150-0-bad-file-descriptor-error-running-configure

Drone CI failure:
```
/mingw32/bin/llvm-config.exe "stdc++"
failed to run llvm_config: args = `['C:/msys32/mingw32/bin/llvm-config.exe', '--libs', '--system-libs', 'x86', 'arm', 'aarch64', 'mips', 'powerpc', 'ipo', 'bitreader', 'bitwriter', 'linker', 'asmparser', 'mcjit', 'interpreter', 'instrumentation']`

llvm-config: unknown component name: aarch64




/drone/src/github.com/Alexpux/MINGW-packages/mingw-w64-rust/src/rustc-1.6.0/mk/llvm.mk:89: recipe for target '/drone/src/github.com/Alexpux/MINGW-packages/mingw-w64-rust/src/build-i686-w64-mingw32/i686-pc-windows-gnu/rt/llvmdeps.rs' failed
make: *** [/drone/src/github.com/Alexpux/MINGW-packages/mingw-w64-rust/src/build-i686-w64-mingw32/i686-pc-windows-gnu/rt/llvmdeps.rs] Error 1
rm i686-pc-windows-gnu/rt/crt2.o i686-pc-windows-gnu/rt/dllcrt2.o
==> ERROR: A failure occurred in build().
    Aborting...
```

This is something i don't understand, anyone else have some ideas?

**Comment by fracting** [comment]
This command line fails for me on Windows as well:
``` C:/msys32/mingw32/bin/llvm-config.exe --libs --system-libs aarch64 ```

Error message:
```
llvm-config: unknown component name: aarch64
```

Any idea what happens?

**Comment by K900** [comment]
That's three different errors, on the same setup the Rust people recommend for building on Windows, except with a workaround for a fourth error we're not even hitting. It's way past bedtime here, so I'm going to give it another shot tomorrow.

**Comment by fracting** [comment]
@K900 we hit https://github.com/drone/drone/issues/1429#issuecomment-176020154
The full log is not shown in our case. The CI server asked me to say sorry to you :D

**Comment by Alexpux** [comment]
Rust 1.7 released

**Comment by hcorion** [comment]
@Alexpux Close this.

**Pull request closed without merging**
