### PR TITLE
Add: qBittorrent-git

### PR DESCRIPTION
**Pull request by Chocobo1**

### CODE REVIEW

**Comment by Chocobo1** [comment]
tea-ci fails because the packages there are too old. libtorrent-rasterbar was updated recently and the CI didn't pick up the update.

**Comment by Chocobo1** [comment]
Is git build accepted or not?

**Comment by Alexpux** [comment]
I dont see reason to accept git package. In any case only release package will be in binary repo

**Comment by Chocobo1** [comment]
OK, then closing this now.

**Pull request closed without merging**
