### PR TITLE
[DO NOT MERGE] python2: Use is_cygpty() to detect a terminal; disable readline with …

### PR DESCRIPTION
**Pull request by lazka**
…a real Windows console

This is the same patch as https://github.com/Alexpux/MINGW-packages/pull/2675
adjusted to work with Python 2.7

### CODE REVIEW

**Comment by lazka** [comment]
Noticed that line buffering isn't enabled, needs more work.

**Comment by lazka** [comment]
hm, ok..

**Comment by lazka** [comment]
From what I see Python 2, unlike Python 3, doesn't change the buffering unless in unbuffered or interactive mode, so the missing line buffering is because mintty doesn't do it compared to cmd.exe. It would be possible to force unbuffered mode when mintty is detected (in Modules/main.c).... but Python 2 is on its way out and I don't care that much.

**Comment by manisandro** [comment]
Hi
I've built a Fedora mingw-python2 package [1] which is basically this work here packaged as a RPM. I'm investigating an issue where stdout (and stderr) simply aren't printed to the console by python2.exe, but I see the outputs if I redirect them to a file. And python2.exe does not run in interactive mode. Is this issue here related to this? Also with `2700-cygpty-isatty-disable-readline.patch` I see no output on the console.

Thanks and apologies for potentially hijacking.

[1] https://src.fedoraproject.org/rpms/mingw-python2/tree/master

**Comment by lazka** [comment]
Which type of console?

**Comment by manisandro** [comment]
Standard Windows cmd.

**Comment by lazka** [comment]
This patch should only change things with cygwin terminals. No idea what could cause your problem, sorry :/

The msys2 Python2 seems to work fine here in cmd.exe

**Comment by lazka** [comment]
The only thing I can think of is that in case the readline module gets build in your build, try deleting it.

**Comment by manisandro** [comment]
Okay thanks, I'll dig further then.

**Comment by lazka** [comment]
In case your build includes the readline module, try deleting it.

**Comment by mati865** [comment]
@manisandro I suppose Python has proper `fflush()` usage but you can try disabling stdout and stderr buffering anyway.

**Comment by manisandro** [comment]
Hm I now build without readline, and indeed the `lib-dynload/readline.pyd` is not built anymore, but I still don't see anything, even if I start as `python2.exe -u`.

**Comment by Ede123** [comment]
@lazka I just noticed this patch broke Windows XP support. Is it supposed to work on Windows as-is? Or do we need to set some compiler flags? It seems you put quite some amount of effort into supporting older versions of Windows without `GetFileInformationByHandleEx` so I hope it will be an easy fix...

**Comment by lazka** [comment]
@Ede123 The code is a straight copy of https://github.com/k-takata/ptycheck According to the readme it should be possible to run on winxp with some defines. I'll have a look.

**Comment by Ede123** [comment]
Thanks! I guess `USE_DYNFILEID` is what we probably want then?

**Comment by lazka** [comment]
@Ede123 see #3187

**Comment by lazka** [comment]
@Ede123 can you test the package: https://ci.appveyor.com/project/Alexpux/mingw-packages/build/1.0.4350/job/djsvrib29g5dhsd2/artifacts ?

**Comment by Ede123** [comment]
Functionality restored on Windows XP, thank you @lazka!

**Comment by lazka** [comment]
Thanks for testing, and sorry for the trouble

**Pull request merged**
