### PR TITLE
gdal: make postgresql dependency non optional

### PR DESCRIPTION
**Pull request by filnet**
see https://github.com/Alexpux/MINGW-packages/issues/3169

### CODE REVIEW

**Comment by Alexpux** [comment]
Dont think that this is fgood idea.

**Comment by filnet** [comment]
I don't like it either but I looks like current libgdal-20.dll needs postgresql:

```
$ ntldd /mingw64/bin/libgdal-20.dll
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000af0000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000af0000)
        ODBC32.dll => C:\WINDOWS\SYSTEM32\ODBC32.dll (0x0000000000af0000)
        ODBCCP32.dll => C:\WINDOWS\SYSTEM32\ODBCCP32.dll (0x00000000000c0000)
        PSAPI.DLL => C:\WINDOWS\SYSTEM32\PSAPI.DLL (0x0000000000020000)
        libwinpthread-1.dll => C:\msys64\mingw64\bin\libwinpthread-1.dll (0x0000000000020000)
        USER32.dll => C:\WINDOWS\SYSTEM32\USER32.dll (0x0000000002080000)
        WS2_32.dll => C:\WINDOWS\SYSTEM32\WS2_32.dll (0x00000000020a0000)
        libgcc_s_seh-1.dll => C:\msys64\mingw64\bin\libgcc_s_seh-1.dll (0x00000000000c0000)
        libstdc++-6.dll => C:\msys64\mingw64\bin\libstdc++-6.dll (0x0000000001f80000)
        libcryptopp.dll => C:\msys64\mingw64\bin\libcryptopp.dll (0x0000000002df0000)
        libcurl-4.dll => C:\msys64\mingw64\bin\libcurl-4.dll (0x0000000000af0000)
        libexpat-1.dll => C:\msys64\mingw64\bin\libexpat-1.dll (0x00000000000c0000)
        libfreexl-1.dll => C:\msys64\mingw64\bin\libfreexl-1.dll (0x00000000000c0000)
        libgeos_c.dll => C:\msys64\mingw64\bin\libgeos_c.dll (0x00000000000c0000)
        libgeotiff-2.dll => C:\msys64\mingw64\bin\libgeotiff-2.dll (0x00000000000c0000)
        libgif-7.dll => C:\msys64\mingw64\bin\libgif-7.dll (0x0000000000020000)
        libhdf5-0.dll => C:\msys64\mingw64\bin\libhdf5-0.dll (0x0000000002df0000)
        libiconv-2.dll => C:\msys64\mingw64\bin\libiconv-2.dll (0x0000000001f80000)
        libjasper-4.dll => C:\msys64\mingw64\bin\libjasper-4.dll (0x0000000000af0000)
        libjpeg-8.dll => C:\msys64\mingw64\bin\libjpeg-8.dll (0x0000000001f80000)
        libjson-c-2.dll => C:\msys64\mingw64\bin\libjson-c-2.dll (0x00000000000c0000)
        libkmlbase.dll => C:\msys64\mingw64\bin\libkmlbase.dll (0x00000000000c0000)
        libkmldom.dll => C:\msys64\mingw64\bin\libkmldom.dll (0x0000000000af0000)
        libkmlengine.dll => C:\msys64\mingw64\bin\libkmlengine.dll (0x00000000000c0000)
        libnetcdf.dll => C:\msys64\mingw64\bin\libnetcdf.dll (0x0000000001f80000)
        libopenjp2-7.dll => C:\msys64\mingw64\bin\libopenjp2-7.dll (0x0000000000af0000)
        libpcre-1.dll => C:\msys64\mingw64\bin\libpcre-1.dll (0x0000000000af0000)
        libpng16-16.dll => C:\msys64\mingw64\bin\libpng16-16.dll (0x00000000000c0000)
        libpoppler-70.dll => C:\msys64\mingw64\bin\libpoppler-70.dll (0x0000000001f80000)
        LIBPQ.dll => C:\msys64\mingw64\bin\LIBPQ.dll (0x0000000000af0000)
        libspatialite-4.dll => C:\msys64\mingw64\bin\libspatialite-4.dll (0x0000000002df0000)
        libsqlite3-0.dll => C:\msys64\mingw64\bin\libsqlite3-0.dll (0x0000000001f80000)
        libtiff-5.dll => C:\msys64\mingw64\bin\libtiff-5.dll (0x0000000000af0000)
        libwebp-7.dll => C:\msys64\mingw64\bin\libwebp-7.dll (0x0000000000af0000)
        libxerces-c-3-1.dll => C:\msys64\mingw64\bin\libxerces-c-3-1.dll (0x0000000002df0000)
        libxml2-2.dll => C:\msys64\mingw64\bin\libxml2-2.dll (0x0000000001f80000)

```

**Comment by filnet** [comment]
But note that, although installing gdal will install the whole postgresql package, you only need to ship libpq.dll in your distribution.

**Comment by filnet** [comment]
What would a good fix ?

**Pull request merged**
