### PR TITLE
mingw-w64-zlib: fixed patches for latest minizip

### PR DESCRIPTION
**Pull request by emmenlau**
Fixed the minizip checkout to specific commit revision, and updated line numbers in one patch.

### CODE REVIEW

**Comment by Alexpux** [comment]
Maybe instead adjust patches for current version?

**Comment by emmenlau** [comment]
The current version of minizip did not compile for me. It failed with a missing linker symbol from their code. I think their head is currently broken (or was broken when I tried).

Also a philosophical question: maybe its better to use a fixed dependency (tag, branch, revision) and not just head? We don't have CI triggers for the minizip repo updates, so we never know when they change something?

**Comment by mati865** [comment]
Specific tag/branch surely should be used instead of the latest commit or it will broke again in future.
With -no-undefined patch current master builds:
```
$ tree
.
└── mingw64
    ├── bin
    │   └── libminizip-1.dll
    ├── include
    │   └── minizip
    │       ├── crypt.h
    │       ├── ioapi.h
    │       ├── iowin32.h
    │       ├── unzip.h
    │       └── zip.h
    └── lib
        ├── libminizip.a
        ├── libminizip.dll.a
        ├── libminizip.la
        └── pkgconfig
            └── minizip.pc

6 directories, 10 files
```
Minizip version can be safely set to latest commit and patches ported.

**Comment by emmenlau** [comment]
I have ported the patches and will test now. I'll update the PR once testing is complete.

**Comment by emmenlau** [comment]
Dear @mati865 , with the updated patches and the latest minizip revision `a447950d`, I get undefined references. Am I doing something wrong? I have updated my branch for your reference.

Please find the build log here:
http://data.biodataanalysis.de/tmp/buildlogs/1487603853-mingw-w64-zlib-buildlog.txt

**Comment by mati865** [comment]
Now I see how badly this repo has been messed up. https://github.com/nmoinvaz/minizip/commit/7b8e226c491a77360dbbc71c2429470924555a9e detached after https://github.com/nmoinvaz/minizip/commit/2e6177226239ac68f3c49cd439a1e8dc29c2f380 so it didn't contain breaking changes.

Out of tree build didn't fail but exectuables are missing but I thought it's normal for out of tree build.

Please add this patch:
[014-fix-Makefile.am.patch.txt](https://github.com/Alexpux/MINGW-packages/files/788110/014-fix-Makefile.am.patch.txt) (remove `.txt`, GitHub limitation....)

**Comment by mati865** [comment]
Also created PR for upstream https://github.com/nmoinvaz/minizip/pull/90

**Comment by emmenlau** [comment]
Thanks @mati865 your upstream patch has been accepted already. I reference the new revision, zlib compiles again. This time it will not break from upstream changes :-)
Please merge!

**Pull request merged**
