### PR TITLE
mingw-w64-vtk: update to 8.0.0, removed deprecated patches

### PR DESCRIPTION
**Pull request by emmenlau**
Updated VTK to newest 8.0.0 release. The patches are not required for building anymore. I did not perform any tests except that VTK builds.

### CODE REVIEW

**Comment by Alexpux** [comment]
Do you test 32 bit build? It fail for me

**Comment by emmenlau** [comment]
I'm sorry that I did not wait with PR before the 32bit test finished. It fails for me too with a linker error.
VTK builds `libvtkharu`, but I think later `vtkIOExport` does not link `libvtkharu`. I will look into it.

**Comment by emmenlau** [comment]
Reported upstream here: https://gitlab.kitware.com/vtk/vtk/issues/17074

**Comment by Alexpux** [comment]
Fixed

**Comment by Alexpux** [comment]
VTK updated to 8.0.1

**Pull request closed without merging**
