### PR TITLE
portmidi: New library

### PR DESCRIPTION
**Pull request by elieux**
As requested in #638.

### CODE REVIEW

**Comment by elieux** [comment]
@j3ffhubb, should I include any of the executables from `pm_test`: latency.exe, midiclock.exe, midithread.exe, midithru.exe, mm.exe, qtest.exe, sysex.exe, test.exe?

**Comment by elieux** [comment]
Also, should the package rather be called `libportmidi`?

**Comment by j3ffhubb** [comment]
Thanks for the quick turnaround :-)

The CLI utilities are not required for using the Portmidi C library, but it may be a good idea to include them because they are mostly for doing MIDI hardware diagnostics, so they have value for testing whether Portmidi is working correctly.

Portmidi is the counter-part to Portaudio, which is already packaged, so the name should probably align with Portaudio, so IMHO just call it portmidi:

```
$ pacman -Ss portaudio
mingw32/mingw-w64-i686-portaudio 19_20140130-1 [installed]
    A free, cross-platform, open source, audio I/O library. (mingw-w64)
mingw64/mingw-w64-x86_64-portaudio 19_20140130-1 [installed]
    A free, cross-platform, open source, audio I/O library. (mingw-w64)
```

**Comment by elieux** [comment]
I updated the PKGBUILD. @Alexpux, can you build?

**Pull request merged**
