### PR TITLE
Update to gnutls-3.4.0 with various workarounds.

### PR DESCRIPTION
**Pull request by ekpyron**
Updates gnutls to version 3.4.0 and adds a patch as well as some modifications to the PKGBUILD, so that gnutls 3.4.0 can be built successfully.

A few of the tests fail due to undefined references to rpl_close, but I think that's a problem within the gnutls test suite and should not cause any problems for anything depending on gnutls.

### CODE REVIEW

**Comment by Alexpux** [comment]
gnutls patch is wrong. I can't merge it

**Comment by ekpyron** [comment]
Could you be more specifc about how the patch is "wrong"? It's not particularily nice, but it definitely works...

**Comment by ekpyron** [comment]
OK - you updated gnutls yourself already - then nevermind :-).

**Comment by bagong** [comment]
The update breaks because of wrong or missing pgp signature...

**Comment by elieux** [comment]
@bagong, what do you mean? Is this related to the signature issue you're seeing? https://wiki.archlinux.org/index.php/Makepkg#Signature_checking

**Comment by bagong** [comment]
Sorry for being unclear. As I was really hoping to get msys cmake working, I tried to build your new gnutls package. The build doesn't even start, it fails on pgp-sig check (I guess you forgot to sign the new source):
```
 Validating source files with md5sums...
    gnutls-3.4.0.tar.xz ... Passed
    gnutls-3.4.0.tar.xz.sig ... Skipped
    0001-add-missing-define.patch ... Passed
    0002-fix-duplicate-entries.patch ... Passed
    0004-fix-gtkdoc.all.patch ... Passed
    0005-fix-strtok-conflict.mingw.patch ... Passed
==> Verifying source file signatures with gpg...
    gnutls-3.4.0.tar.xz ... FAILED (unknown public key 9D5EAAF69013B842)
==> ERROR: One or more PGP signatures could not be verified!
```
After I disabled sig checking the actual build also broke, but I am sorry, didn't take a note of the build error, was some 15 mins into the build, 64-bit :)
This is on a brand new msys2, just set up today. Really cool, btw!!!

**Comment by mingwandroid** [comment]
We don't sign the sources of externally released source packages. You need
to import the keys of the actual developers to be able to verify their
signatures.

Top posted from a small computing device.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/ab2d30aa7cf6eb7b95f77ace1a1e4589d5b1166d

**Comment by bagong** [comment]
Ah, okay, thanks!

**Pull request closed without merging**
