### PR TITLE
Some various things I wanted to add before I forget

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Hi @JPeterMugaas, please improve the commit messages. Use the defacto standard as reference. In particular, the first and second commits do not give enough indication in the first line about what they do and the last 3 should be of the form:

package name:  Update to version

`git rebase -i HEAD~6` is your friend here.

Many thanks in advance.

**Comment by JPeterMugaas** [comment]
I hope the new labeling helps.  I want to get things in so I can go on and make more contributions.

**Comment by mati865** [comment]
Looks much better now.

**Comment by mingwandroid** [comment]
Thanks. Still slightly long on the first lines and you should list yourself as maintainer for packages you contribute, but good enough!

**Pull request merged**
