### PR TITLE
Update libsndfile to v.1.0.28

### PR DESCRIPTION
**Pull request by bagong**
Hi,

this updates libsndfile to version 1.0.28, which is a quite significant update with lot's of bugfixes. The old patches don't apply anymore, and it seems they are not really required? Maybe it's better just to remove them and suggest potentially required fixes upstream. The libsndfile repo has been very responsive, lately. This might also make future updates in MSYS2 easier.

Best
.r.

### CODE REVIEW

**Comment by bagong** [comment]
The build error is a "permission-error". Not sure how I can influence that?

````
../libtool: fork: Permission denied
make[2]: *** [Makefile:721: libcommon.la] Error 254
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/drone/src/github.com/Alexpux/MINGW-packages/mingw-w64-libsndfile/src/build-x86_64-w64-mingw32/src'
make[1]: *** [Makefile:550: all] Error 2
make[1]: Leaving directory '/drone/src/github.com/Alexpux/MINGW-packages/mingw-w64-libsndfile/src/build-x86_64-w64-mingw32/src'
make: *** [Makefile:531: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
````

**Comment by mati865** [comment]
Cygwin on Wine has crashed, there is nothing you can do about it.

**Comment by bagong** [comment]
Is it a problem?

**Comment by mati865** [comment]
No, you can ignore it completely.

**Comment by bagong** [comment]
Turns out the 1.0.28 release is buggy. They're working on 1.0.29. I'll close for now and resubmit when that release is out.

**Pull request closed without merging**
