### PR TITLE
Gnuplot

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by peterbud** [comment]
Please don't merge this. `gnuplot` change. 
First it seems its is not building properly: see Appveyor CI. 
Second, as I have mentioned my original submission, I have a much better way to build gnuplot. I'm just waiting for @Alexpux to publish the proper 32-bit libgd in the repo to be able to build also the 32-bit version of `gnuplot` properly

**Comment by Alexpux** [comment]
I think proper fix for building gnuplot with libgd is to add define ````BGDWIN32```` to flags during build

**Comment by peterbud** [comment]
I'm not sure. At least I have not found `BGDWIN32` flag in the code. `gnuplot` builds properly with the 32-bit version if the 32-bit versions of `libgd` is exposing normal (not mangled) function names  - see our conversation #2950.
If you could upload the `libgd` 2.2.5 into the repo, I could open a PR to show how `gnuplot` builds with the 32-bit version.

**Comment by Alexpux** [comment]
I'm push changes for libgd and gnuplot

**Pull request closed without merging**
