### PR TITLE
gitg: downgrade to version 0.2.7.

### PR DESCRIPTION
**Pull request by KrullKorg**
It builds but it doesn't work very well.

### CODE REVIEW

**Comment by DavidEGrayson** [comment]
I couldn't even build the existing gitg PKGBUILD because I don't know where `mingw-w64-x86_64-webkit2gtk3` comes from.

**Comment by Alexpux** [comment]
There are no working webkit2 package for GTK. We have ````mingw-w64-{i686,x86_64}-webkitgtk3```` packages but it contain only webkit1 as webkit2 not buildable for Windows

**Comment by mingwandroid** [comment]
webkit2 would be a great task for someone to step up and hack on :-)

I've not got enough time unfortunately.

**Comment by KrullKorg** [comment]
I downgrade gitg because version 0.2.7 doesn't depend on webkit2gtk3; i'll try ASAP to make it more usable under win

**Comment by KrullKorg** [comment]
could you merge it?

**Comment by mingwandroid** [comment]
How well is it working now?

**Comment by KrullKorg** [comment]
not very well (for example sometime it shows the history and sometimes not) but it builds; 0.3.3 doesn't and it cannot be build until webkit2gtk3 is buildable

**Pull request closed without merging**
