### PR TITLE
[DO NOT MERGE][WIP]KDEF5: add, fix or update packages

### PR DESCRIPTION
**Pull request by mati865**
Depends: working cmake (3.5.2 or https://github.com/Alexpux/MINGW-packages/pull/1596; 3.6.0 is bugged), https://github.com/Alexpux/MINGW-packages/pull/1614, ~~https://github.com/Alexpux/MINGW-packages/pull/1621~~, https://sourceforge.net/p/mingw-w64/bugs/550/, https://github.com/Alexpux/MINGW-packages/pull/1640

I'm thinking about moving KDE stuff to another repository to reduce @Alexpux work. Those are only framework or tools to build it.

TODO:
- ~~replace hacks with proper fixes (high importance)~~
- ~~fix config directory location (`.kde`)~~
- fix kpty
- improve building order [by tiers](https://api.kde.org/frameworks/index.html)
- fix kpeople (low priority)
- ~~test if desktop2json from kcoreaddons is Ok~~
- fix dependencies
- ~~`mingw{32,64}/lib/plugins` is not searched~~
- fix kapidox

Testing: 

```
cd mingw-w64-PKGBUILD-common
./build-kf5 shared
```

Contributing:
Everyone can create PR to the branch kdef5 or post here.

### CODE REVIEW

**Comment by elieux** [comment]
> I'm thinking about moving KDE stuff to another repository to reduce @Alexpux work. Those are only framework or tools to build it.

If we can agree on *not building* KDE5 packages, I'd much rather have them all together here.

**Comment by mati865** [comment]
> If we can agree on not building KDE5 packages, I'd much rather have them all together here.

Or we could keep KDE stuff here but don't build it for mingw64 and create kde{32,64} binary repositories. Framework contain 65 packages, if we add KDE Applications it will surely be more than 200 packages.
I think @Alexpux is busy enough with the other MSYS2 stuff and someone else should watch over it.

I've just discovered that during rebase something went wrong and some packages weren't updated, hopefully they are fine now.

Updated first post about contributing and TODO.

@mingwandroid I couldn't catch you on the IRC. I've added you as Maintainer to all packages and myself as Contributor. What way do you prefer: as is, two Maintainers or something else?

**Comment by mkae** [comment]
@elieux what do you mean by keeping it here, but not building the KDE5 packages?

I believe it's nice to have KF5 here on MSYS2, as it offers an alternative path to install the KDE ecosystem.

**Comment by mati865** [comment]
Commiting drunk but hoping KDEF5 is buildable by now. Failed rebase broke some things.

Also update TODO.

**Comment by mingwandroid** [comment]
Adding yourself as maintainer is 100% fine by me. I'm going to make more effort to get onto IRC next week too. Cheers!

**Comment by mkae** [comment]
Thumbs up for your efforts, mati865, to get KF5 installed via MSYS2!

**Comment by mkae** [comment]
@elieux and @mingwandroid, has there ever been a discussion about perhaps creating a mirror repository which would contain additionally all those packages which its maintainers don't want to throw onto @AlexPux.

The maintenance to be done by him is enormous and one should come up with an alternative which lifts a big chunk from his shoulders.

A mirror repo for that purpose could be an alternative, no!?

**Comment by mati865** [comment]
@mkae I'm thinking about providing BinTray repository for KDE but I worry that my PC will be not enough to rebuild everything in reasonable amount of time after update.

**Comment by mati865** [comment]
@mingwandroid I could use some help at fixing `QStandardPaths::GenericDataLocation` usage, [doc](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum). On Windows it points:`"C:/Users/<USER>/AppData/Local", "C:/ProgramData", "<APPDIR>", "<APPDIR>/data"`
But we would use Linux-like `"~/.local/share", "/usr/local/share", "/usr/share"`.
I have created quick workarounds just to make it compile (`hack-fix*`.patch) and they won't work if MSYS2 directory isn't either X:\msys32 or X:\msys64. And since `QStandardPaths::GenericDataLocation` is used by pretty every KDE package we need more generic solution ( icons, plugins, themes and much more stuff isn't working because of it: http://imgur.com/BwOoHRf).

**Comment by mkae** [comment]
You might direct this directly to the kde-devel mailing list, @mati865, as this is an issue we've been discussing at length also for KDE on OSX in the course of the past year.

**Comment by mati865** [comment]
@mkae I'm using ArchLinux for pretty much everything except gaming for 6 years or even longer always with KDE.

**Comment by mkae** [comment]
I have worked on KDE4 and KF5 for quite some time now and started an initiative on OSX/MacPorts to improve the support for KDE software on Apple hardware [1].

At the very beginning there were patches against Qt5 (in fact) to make it work with OSX in the way that KDE expected it. I used those for a KDE CI system which was based on MacPorts up to about a year ago [1]. This has been discussed to death on the relevant mailing lists with the result that none of the Qt and KDE developers really supported the idea of such patches, not even for CI purposes. Yet, no one came up with a viable approach to facilitate an alternative CI system up to now. KDE even bought a Mac mini to get going with that, but it is still in preparation [3].

If you want to learn more about how MSYS2 could profit from the knowledge we gained on MacPorts with respect to KF5, you should get in touch with [René Bertin](https://phabricator.kde.org/p/rjvbb/), who did finally set up KF5 for OSX by introducing a new MacPorts port called `qt5-kde` - which is still WIP but...

Just today, though, I was able to successfully build 100 KF5-related ports including and using his `kf5-Frameworks` port [4]! :-) So, we're close to releasing this to MacPorts soonish, after all.

It would be nice to see KF5 flying on MSYS2!! Cool to see you getting into this!!! 👍 

[1] https://trac.macports.org/wiki/KDEProblems
[2] https://trac.macports.org/wiki/KDEProblems/KDEMacPortsCI/Status
[3] https://phabricator.kde.org/T2250
[4] https://mail.kde.org/pipermail/kde-mac/2016-August/004942.html

**Comment by mati865** [comment]
@mkae I just found 5 minutes ago QLibraryInfo::PrefixPath https://doc.qt.io/qt-5/qlibraryinfo.html#location which returns `D:/msys64/mingw64/`. That should apply to most of the cases (if not all).

**Comment by mkae** [comment]
Yeah, don't know how much good the pages are for your use case. But perhaps you can find something of interest. `QLibraryInfo` rings a bell with me... I believe René makes use of it as well.

**Comment by mati865** [comment]
It's pretty comfortable to use: no more crazy hacks, most of the fixed Framework packages should be ready for Monday or Tuesday.

**Comment by mingwandroid** [comment]
Excellent. I really look forward to checking this out. Sorry I have less time for MSYS2 at the moment. For the question of which repo, I don't mind at all if it's external, but let's wait to hear from @Alexpux.

**Comment by mkae** [comment]
@mati865, here the relevant link to our efforts at MacPorts to achieve what you're trying to do here on MSYS2: https://trac.macports.org/ticket/49925#comment:21

**Comment by mati865** [comment]
@mingwandroid NP, I was out of ideas how to fix it without non-portable hacks. And then accidentally found QLibraryInfo. Right now I'm ~30-40% done.

**Comment by mati865** [comment]
I take back my words, just did grep instead of counting directories to see progress.
Higher tier packages extensively use `QStandardPaths` enum. I would say I have ported 10% but actual state is far lower and autotests aren't easily fixable.
@Alexpux, @mingwandroid we have to patch Qt or create new package `mingw-w64-qt5-kde` (I can maintain binary alongside KDE packages) like MacPorts did.
However our environment is a bit different and we could either:
- create class lets say `QMsysPaths` based on `QStandardPaths` and just sed includes
- create enum `QStandardPaths::MsysLocation` and sed `QStandardPaths::StandardLocation` to `QStandardPaths::MsysLocation`

**Comment by mkae** [comment]
@mati865, yes, you're encountering the same problems like we did on OSX/MacPorts. A patched Qt is least intrusive for the KF5 packages, but it's not a real solution. Please trigger a discussion at KDE's devel mailing list, if you feel like. I could search the archives for past discussions on the topic, but I guess you're able to spot those yourselves too. It's not an easy decision how to proceed, otherwise we already could have come to an agreement about how to tackle this in the future for all platforms. With an MSYS2-based release of KF5 I figure that it might make sense to restart such discussions with the KDE folks again.

**Comment by mati865** [comment]
@mkae, sure I'll bring it to the mailing list but lets get something to show first.

**Comment by mkae** [comment]
KDE folks focus for Windows on emerge...
Yeah, but you're right, good to try to get it to work first and then proceed with discussions.

**Comment by mingwandroid** [comment]
Yeah it is a shame they didn't adopt MSYS2 and ditch emerge.

**Comment by mati865** [comment]
@mingwandroid, my attempt to patching Qt. It is currently building but I wouldn't expect it to be ready for tests until Friday https://github.com/mati865/MINGW-packages/commit/c57e84acee38044000b0d57377bc6624fafd2a6d

**Comment by mingwandroid** [comment]
I don't think we should bother with a whole new qt5 variant just for this standard paths change. It's appropriate for all Qt applications to live inside the /mingw?? prefix for global stuff and inside /home/%USERNAME% for user stuff.

When we make this change we may want add some migration code to the qt5 post install scripts to copy user stuff from the old place to the new place though.

**Comment by mati865** [comment]
The problem with `QStandardPaths::GenericDataLocation` is that it provides `~/.local/share", "/usr/local/share", "/usr/share` on Linux and `C:/Users/<USER>/AppData/Local", "C:/ProgramData", "<APPDIR>", "<APPDIR>/data` on Windows. But we keep data similar to Linux in `/mingw{32,64}/share` so KDE programs cannot find them. Replacing those functions is problematic:
only for KDE Frameworks it's nearly 600 (could be more if I missed something) calls of functions `QStandardPaths::standardLocations()` and `QStandardPaths::writableLocation()`. Big part of them must be threaten separately because we have to mimic `QStandardPaths::locate()` and `QStandardPaths::locateAll()`. If it wasn't enough there is a thing called `testMode` used in some parts of autotests which further complicates replacing those functions.
Home directory is next thing to discuss. On Windows it defaults to the %USERPROFILE% environement variable. My patch changes it to MSYS `/home` for everything but Music, Movies, Pictures, etc.

Forgot to mention my changes to the Qt are just 1 patch: `0200-create-writableLocationMsys-and-standardLocationsMsy.patch` (yeah, it's typo about missing 's' for Msys).
I think we could use this patch for original Qt package since it shouldn't mess anything. If not I'll maintain qt5-kde variant with this patch provided.

**Comment by mingwandroid** [comment]
I definitely am not suggesting replacing 600 occourances of QStandardPaths:: ...

Having a qt5-kde variant just for this one change seems like massive overkill. Existing Qt applications (e.g. qtcreator) will be storing their settings in the 'old' paths, so we need to do a migration when we change Qt.

If we *must* make KDE applications behave differently we could consider setting an env. var at the KDE entry points, reading it in qt initialization code and checking it in `QStandardPaths::` but I don't think there's any need for us to do that either.

**Comment by mati865** [comment]
> Having a qt5-kde variant just for this one change seems like massive overkill.

If this patch (`0200-create-writableLocationMsys-and-standardLocationsMsy.patch`) could be accepted to our standard qt5 package there would be no need for another variant. But I need to know what you @mingwandroid and @Alexpux think about it.

> Existing Qt applications (e.g. qtcreator) will be storing their settings in the 'old' paths, so we need to do a migration when we change Qt.

That's why I created two new functions instead or replacing old. Unless we replace `QStandardPaths::standardLocations()` and `QStandardPaths::writableLocation()` with patch or sed applications will use old paths.

> If we must make KDE applications behave differently we could consider setting an env. var at the KDE entry points, reading it in qt initialization code and checking it in QStandardPaths:: but I don't think there's any need for us to do that either.

You mean something like `XDG_*` https://wiki.archlinux.org/index.php/XDG_Base_Directory_support?
Neither KDE nor default Windows `QStandardPaths` support it but functions added by my patch support it just like on Linux.

**Comment by mkae** [comment]
@mingwandroid & @mati865, your lines of argumentation are the exact repetition of what happened on the KDE-MAC mailing list w.r.t. the OSX/MacPorts qt5-kde port variant for weeks and months... :-)

It's really a tough decision to make, patch qt5 or not, but the latter requires sacrifices and workarounds at the moment, which might not be feasible for potential KF5 users. Many of those just want their applications to behave like on Linux... Unless qt5 comes up with another concept of defining its standard paths this will require it being patched as suggested.

**Comment by mati865** [comment]
After some testing and polishing here comes the patch for Qt5: https://github.com/Alexpux/MINGW-packages/pull/1634

P.S.
Don't try to build whole Qt5 on C2D machine unless you want to waste 16 hours 😄 .

**Comment by mati865** [comment]
Fixed Qt: https://github.com/Alexpux/MINGW-packages/pull/1640
Frameworks updated to 5.25 and patched for the new Qt functions will come soon.

**Comment by mati865** [comment]
Updated framework to latest 5.25.0 and replaced QStandardPaths functions with sed. Last critical thing is to fix  `mingw{32,64}/lib/plugins` is not being searched.

**Comment by mkae** [comment]
Hi @mati865, I meant to ask why this is actually called KDEF5 here?!? As far as I know the proper terminology for KDE's KDE Framework 5 is KF5. Sorry for sounding somewhat pernickety, though! :)

**Comment by mkae** [comment]
@RJVB, are you aware of this PR?

**Comment by mati865** [comment]
@mkae 

> Hi @mati865, I meant to ask why this is actually called KDEF5 here?!? As far as I know the proper terminology for KDE's KDE Framework 5 is KF5. Sorry for sounding somewhat pernickety, though! :)

It was called here that way before. I'll change it after squishing commits.

**Comment by mati865** [comment]
Last thing that I hoped will be fixed by fixing plugins but is not is deadlock when exiting apps. For an example https://github.com/KDE/kiconthemes/blob/master/src/tools/kiconfinder/kiconfinder.cpp is fine until `return 0` or `return 1` is called. Then app must be killed from task manager. I asked about it on kde-windows IRC but there was no answer, I'll ask on mailing list when I get more time.

**Comment by mati865** [comment]
Due to lack of time I'm closing this PR.
I'll keep this branch in my repo but it won't be updated unless I have time to do it.

**Pull request closed without merging**
