### PR TITLE
glib2: updated to 2.54.0.

### PR DESCRIPTION
**Pull request by KrullBorg**
Before build you must update the gtk-doc package

### CODE REVIEW

**Comment by Alexpux** [comment]
i try to build GLIB2 and it have conflicts with files from other package seems. Did you try to build and install it yourself?

**Comment by KrullBorg** [comment]
yes i built it and installed it without problems; what conflicts?

**Comment by Alexpux** [comment]
glib-genmarshal

**Comment by Alexpux** [comment]
problem seems that in previous version builded ````glib-genmarshal.exe```` and now without extension

**Comment by Ede123** [comment]
You might want to hold of on that update because of
https://bugzilla.gnome.org/show_bug.cgi?id=787648

(glibmm 2.54.0 accidentally requires C++14)

**Comment by mati865** [comment]
@Ede123 GCC is used to build packages (with gnu++14 standard as default). libc++ is broken so much it cannot be used with MinGW even for hello world programs.
We can ignore linked issue.

**Comment by Ede123** [comment]
@mati865 It breaks the Inkscape build on ubuntu 17.10.1, see the [build log](https://launchpadlibrarian.net/337093458/buildlog_ubuntu-artful-amd64.inkscape-trunk_1%3A0.92.0+devel+16028+91~ubuntu17.10.1_BUILDING.txt.gz) which (if I'm not completely mistaken) uses gcc to build (Inkscape defines `-std=c++11`).

**Comment by mati865** [comment]
@Ede123 you are right, looks like everything would have to switch to c++14.

**Comment by lazka** [comment]
>problem seems that in previous version builded glib-genmarshal.exe and now without extension

While looking into fixing mingw gtk-doc I've used the following to create exe launchers for python scripts: https://bpaste.net/show/f2160a91e230

maybe that's also useful here

**Comment by holgern** [comment]
Then we have to switch to an old version for gobject-introspection.
The actual version depends on glib 2.54.0.

**Comment by Ede123** [comment]
glibmm 2.54.1 (which removes the C++14 dependency) has been released in the meantime (see https://bugzilla.gnome.org/show_bug.cgi?id=787648#c36), so we can update to that version.

**Comment by Alexpux** [comment]
Ok

**Comment by Ede123** [comment]
@Alexpux Do you want a PR for 2.54.1 (we now have 2.54.0) or will you update the pkgver yourself?

**Comment by Alexpux** [comment]
you can create pr

**Comment by lazka** [comment]
@Ede123 glib and glibmm are two different projects

**Comment by Ede123** [comment]
Good catch... I think nobody noticed I was telling nonsense all this time (maybe Alex did). :-D

I somehow assumed this was about glibmm from the start (probably got tricked by the synced version numbers)  and saved that part in my brain... Thanks for playing along everybody (and sorry for the confusion). ;-)

**Pull request merged**
