### PR TITLE
Updated GNU libmicrohttpd to latest upstream version (0.9.53)

### PR DESCRIPTION
**Pull request by Karlson2k**
Restored compatibility with WinXP

### CODE REVIEW

**Comment by Karlson2k** [comment]
For some reason still have `WARNING: Skipping verification of source file PGP signatures.` in log.
PGP keys added.

**Comment by elieux** [comment]
@Karlson2k, I guess you have `--skippgpcheck` enabled.

> '289FE99E138CF6D473A3F0CFBF7AC4A5EAC2BAF4') # Karlson2k (Evgeny Grin)

I'm confused. Why is there your key here? Are you the packager of upstream libmicrohttpd?

**Comment by Karlson2k** [comment]
> I'm confused. Why is there your key here? Are you the packager of upstream libmicrohttpd?
@elieux Correct, I'm co-maintainer of GNU libmicrohttpd.

**Comment by elieux** [comment]
Disregard my complaint then.

**Pull request merged**
