### PR TITLE
Nghttp2

### PR DESCRIPTION
**Pull request by JPeterMugaas**

### CODE REVIEW

**Comment by peterbud** [comment]
@JPeterMugaas : just a question - Why you have som many commits in this PR?

**Comment by mati865** [comment]
@peterbud It happens when you use `git-merge` instead of `git-rebase`.

**Comment by peterbud** [comment]
Hmmm I'm always using merge in my forked master branch, and then I create a new branch from there, then initiate a PR to the upstream, and I haven't had such symptoms...

**Comment by mati865** [comment]
I'm not a git expert but I think it tries to do fast forward merge first, and if it fails then merge commits are created. GitHub sees that repositories have different history and tries to update history of https://github.com/Alexpux/MINGW-packages to look like repository from PR.

**Comment by JPeterMugaas** [comment]
I have gone ahead and reset what I have.  I will be retrying this request.

**Pull request closed without merging**
