### PR TITLE
pngcrush v1.7.86, sqlite v3.8.11.1, putty 0.65

### PR DESCRIPTION
**Pull request by elieux**
Everything builds okay here.

Nevermind the branch name. :)

### CODE REVIEW

**Comment by Alexpux** [comment]
your changes conflicts. resolve it

**Comment by elieux** [comment]
I just noticed that Alexey updated sqlite3 to v3.8.11.1 today as well, but sqlite-analyzer only to v3.8.11. My patch updated both to v3.8.11.1.

**Comment by elieux** [comment]
Okay, will be resolved shortly.

**Comment by elieux** [comment]
Rebase done.

**Pull request merged**
