### PR TITLE
gcc-git: Update to GCC8 and remove patches for GCC 5 and GCC 6.

### PR DESCRIPTION
**Pull request by lhmouse**
Signed-off-by: Liu Hao <lh_mouse@126.com>

### CODE REVIEW

**Comment by lhmouse** [comment]
@Alexpux Will remove 0012 and re-push.

That color patch was adopted into trunk and is now available naturally in GCC 8.

**Comment by lhmouse** [comment]
Done.

**Comment by jeroen** [comment]
Is there any reason not to copy this set of changes to `mingw-w64-gcc`?

**Comment by lhmouse** [comment]
It is just because I don't maintain `mingw-w64-gcc`.

**Pull request merged**
