### PR TITLE
Fix issue where the wrong OpenJPEG configuration file was found causi…

### PR DESCRIPTION
**Pull request by JPeterMugaas**
…ng cmake to fail.  I also specified where the data is located.

### CODE REVIEW

**Comment by Alexpux** [comment]
poppler check that opengpeg is version 2 or greater
https://gitlab.freedesktop.org/poppler/poppler/blob/master/CMakeLists.txt#L206

**Comment by Alexpux** [comment]
i also have installed openjpeg 1 and it doesnt find it

**Comment by JPeterMugaas** [comment]
I got this: 

-- Found Cairo: D:/msys64/mingw64/lib/libcairo.dll.a (Required is at least version "1.10.0")
-- Checking for modules 'glib-2.0>=2.41;gobject-2.0>=2.41;gio-2.0>=2.41'
--   Found glib-2.0, version 2.56.1
--   Found gobject-2.0, version 2.56.1
--   Found gio-2.0, version 2.56.1
-- Found GLib: gio-2.0;gobject-2.0;glib-2.0;intl
-- Checking for module 'gobject-introspection-1.0'
--   Found gobject-introspection-1.0, version 1.56.1
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: D:/msys64/mingw64/lib/libiconv.dll.a
CMake Error at CMakeLists.txt:207 (message):
  Install libopenjpeg2 before trying to build poppler.  You can also decide
  to use the internal unmaintained JPX decoder or none at all.


-- Configuring incomplete, errors occurred!

I am certain that OpenJPEG2 is installed as well as OpenJPEG 1.x.  That's why I made the workaround I did.  The where I specify the OpenJPEG 2 path does seem to work better here.

**Comment by Alexpux** [comment]
@JPeterMugaas do you build fixed openjpeg2? I fix cmake files location for it

**Comment by JPeterMugaas** [comment]
From the CMakeCache.txt I have: 
//The directory containing a CMake configuration file for OpenJPEG.
OpenJPEG_DIR:PATH=D:/msys64/mingw64/lib/openjpeg-1.5

**Comment by JPeterMugaas** [comment]
Alright, I tried yours but I got this:
==> Build shared version
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: D:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: D:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: D:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for string.h
-- Looking for string.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for math.h
-- Looking for math.h - found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Checking for 64-bit off_t
-- Checking for 64-bit off_t - present with _FILE_OFFSET_BITS=64
-- Checking for fseeko/ftello
-- Checking for fseeko/ftello - present
-- Large File support - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - found
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
-- Looking for memalign
-- Looking for memalign - not found
-- Found ZLIB: D:/msys64/mingw64/lib/libz.dll.a (found version "1.2.11")
-- Your system seems to have a Z lib available, we will use it to generate PNG lib
-- Found PNG: D:/msys64/mingw64/lib/libpng.dll.a (found version "1.6.35")
-- Your system seems to have a PNG lib available, we will use it
-- Found TIFF: D:/msys64/mingw64/lib/libtiff.dll.a (found version "4.0.9")
-- Your system seems to have a TIFF lib available, we will use it
-- Found LCMS2: D:/msys64/mingw64/lib/liblcms2.dll.a
-- Your system seems to have a LCMS2 lib available, we will use it
-- Found Java: C:/Program Files/Java/jdk-9.0.4/bin/java.exe (found suitable version "9.0.4", minimum required is "1.5") found components:  Development
-- Configuring done
-- Generating done
-- Build files have been written to: D:/msys64/home/jpmugaas/exp/mingw-w64-openjpeg2/src/build-shared-x86_64-w64-mingw32
Scanning dependencies of target openmj2
Scanning dependencies of target OPJViewerJar
Scanning dependencies of target openjp2
Scanning dependencies of target opj_jpip_addxml
Scanning dependencies of target ppm2rgb3
Scanning dependencies of target compare_dump_files
Scanning dependencies of target openjpwl
Scanning dependencies of target openjp3d
Scanning dependencies of target compare_raw_files
[  1%] Building C object src/lib/openmj2/CMakeFiles/openmj2.dir/mj2.c.obj
[  1%] javac *.java; jar cvf -> opj_jpip_viewer.jar
[  1%] Building C object src/lib/openjp2/CMakeFiles/openjp2.dir/thread.c.obj
warning: [options] bootstrap class path not set in conjunction with -source 1.5
error: Source option 1.5 is no longer supported. Use 1.6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.
make[2]: *** [src/bin/jpip/CMakeFiles/OPJViewerJar.dir/build.make:70: bin/opj_jpip_viewer.jar] Error 2
[  1%] Building C object src/bin/jpip/CMakeFiles/opj_jpip_addxml.dir/opj_jpip_addxml.c.obj
[  2%] Building C object tests/CMakeFiles/compare_dump_files.dir/compare_dump_files.c.obj
make[1]: *** [CMakeFiles/Makefile2:1847: src/bin/jpip/CMakeFiles/OPJViewerJar.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Pull request closed without merging**
