### PR TITLE
add mono package (version 5.4.1.7)

### PR DESCRIPTION
**Pull request by Adsun701**
This adds the mono package (version 5.4.1.7), a C# and .NET Framework implementation.

Unfortunately it requires an already existing installation of mingw-w64-mono for bootstrapping; however, I've uploaded existing mingw-w64-mono packages here for installation and bootstrapping:
https://github.com/Adsun701/msys2-mingw-binary-packages

Thanks.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Hod did you build these bootstrap binaries? Where is the recipe?

**Comment by Adsun701** [comment]
I originally built the bootstrap mono package by using the monolite directory that came with the source. The recipe can be found here: [https://github.com/Adsun701/msys2-mingw-binary-packages/tree/master/mono-bootstrap](url)

**Comment by mingwandroid** [comment]
I fixed your links. You aren't doing them right. I think you should include the bootrap recipe in a subdir here.

**Comment by Adsun701** [comment]
Added bootstrap recipe. Sorry for not responding so long.

**Pull request merged**
