### PR TITLE
Add optimisations for non-MSVC compilers...

### PR DESCRIPTION
**Pull request by mkae**
... for lib and app.

Also fix for upper case still used for app's exe, since that leads to trouble in `makepkg-mingw`!

### CODE REVIEW

**Comment by mkae** [comment]
Don't understand why drone doesn't find the patch file:
```
==> ERROR: optimisations-CMakeLists.txt.patch was not found in the build directory and is not a URL.
```
Could it be that this is caused by the upper case in the package's directory name?

**Comment by fracting** [comment]
Hi @mkae the missing patch was putting into a separate directory: https://github.com/mkae/MINGW-packages/tree/master/mingw-w64-bsdfprocessor

It is interesting that this work on Windows, which means there is some bug in Wine + MSYS2, thanks for helping me find Wine bugs ;) However, the patch itself should also be fixed, could you double check?

Thanks!

**Comment by mkae** [comment]
Hi, @fracting, I don't think it's a real bug in wine. Guess it just means that wine is running on a case-sensitive file system, while AppVeyor operated on a case-insensitive one. No?

**Comment by mkae** [comment]
But yes, the repo itself has files for this package in two separate folders, with upper and lower case, as I see only now. So, my local clone on my Vista machine is thus different from my own repo at github!!

**Comment by mkae** [comment]
Well, and so AppVeyor must be running on a case-insensitive file system...

Okay, will try to fix this with a checkout of my repo on Linux, in order to work on a case-sensitive file system.

**Pull request merged**
