### PR TITLE
glib2: to maintain compatibility with windows xp.

### PR DESCRIPTION
**Pull request by KrullKorg**

### CODE REVIEW

**Comment by KrullKorg** [comment]
i'm afraid, but github decided to add new commit (gexiv2) to this pull request...

**Comment by Alexpux** [comment]
no problem

**Comment by bpisoj** [comment]
Nice to have gexiv2 included but this gexiv2 package not installs typelib and python overrides.

From Makefile:
PYTHON2_GIDIR = C:/msys64/mingw32/lib/python2.7/site-packages/gi/overrides
py2gidir = $(PYTHON2_GIDIR)

and then pkg try to install to "$(DESTDIR)$(py2gidir)" and fail.

**Comment by bpisoj** [comment]
This patch works for me!
https://gist.github.com/bpisoj/b0cb17e61c6804fb3655

**Comment by mingwandroid** [comment]
Please fork the repository and submit a pull request.

**Comment by bpisoj** [comment]
Done that in PR:
  gexiv2: fix install of typelib and python overrides

**Pull request merged**
