### PR TITLE
Updated protobuf, grpc, and eigen3, and improved the build

### PR DESCRIPTION
**Pull request by emmenlau**

### CODE REVIEW

**Comment by peterbud** [comment]
Do you know why the CI job run into an error:
```
src/core/lib/iomgr/pollset_windows.c: In function 'grpc_pollset_shutdown':
src/core/lib/iomgr/pollset_windows.c:114:3: error: ignoring return value of 'grpc_pollset_kick', declared with attribute warn_unused_result [-Werror=unused-result]
   grpc_pollset_kick(pollset, GRPC_POLLSET_KICK_BROADCAST)
```

**Comment by filnet** [comment]
The compiler was probably upgraded (to a stricter version) since that package was last compiled.

**Comment by emmenlau** [comment]
Interesting. I can confirm that it compiles fine for me with latest msys2 from today. @peterbud does it work for you?

**Comment by mati865** [comment]
You could try changing https://github.com/grpc/grpc/blob/b1f6bf2ec4148902d5ee4ec06e9d521b27bfb4f0/include/grpc/impl/codegen/port_platform.h#L364 to
```
#if defined(__GNUC__) && !defined(_WIN32)

**Comment by filnet** [comment]
Other strange things:
- tea fails later (i.e. it manages to compile the file that fails under appveyor)
- appveyor displays "cc1.exe: all warnings being treated as errors" after the compilation error

**Comment by mati865** [comment]
Build should fail because of this: https://github.com/grpc/grpc/blob/ed92f7bc04d5dcea415f9eeb0f3593ce9a3cc485/config.m4#L593

So why didn't it fail locally?
Maybe [this hack](https://github.com/Alexpux/MINGW-packages/pull/1951/commits/8c6546ecf5a5e8841df403a64d54ab29fc6a55a3#diff-9762945ac9e3599ed7539185968db6b4R310) for some reason didn't work in AppVeyor.

**Comment by mati865** [comment]
@emmenlau Did you build both 32 and 64 bit packages or 64 bit only?
32 bit Tea also failed at unused-result https://tea-ci.org/Alexpux/MINGW-packages/1843/2

**Comment by emmenlau** [comment]
@mati865 sorry I did not do the 32bit build yet, have just started it now. But for the sake of reproducibility I just re-built protobuf and grpc and they both compile fine on 64bit. git tells me I have lo local changes and everything is pushed to github. And pacman now lists a few updates, but nothing major...

**Comment by mati865** [comment]
Just found out reason why this hack:
```
#ifdef __MINGW64__
#pragma GCC diagnostic ignored "-Wunused-result"
#endif
```
is not working.
`__MINGW64__` is defined only with 64 bit MINGW, you should use `__MINGW64_VERSION_MAJOR` instead.
I still think changing [header](https://github.com/grpc/grpc/blob/b1f6bf2ec4148902d5ee4ec06e9d521b27bfb4f0/include/grpc/impl/codegen/port_platform.h#L364) would be more proper solution.

**Comment by emmenlau** [comment]
@mati865 I've fixed the issue with ```__MINGW64__``` define.
I've also updated protobuf to 3.1.0 and applied the necessary patches to grpc to build against this newer protobuf (patch from upstream). Works for me on i686 and x86_64.

**Comment by Alexpux** [comment]
Rebase changes to header

**Comment by emmenlau** [comment]
@Alexpux I've rebased the changes to header. It still works for me on 32 and 64 bit.

**Comment by Alexpux** [comment]
Changes not rebases as you can see on your pull request 34 commits and 103 files changed

**Comment by peterbud** [comment]
@emmenlau  read this issue #1948, mingwandroid provided a good description what can be done. 
Also [this](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) and [this](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) can be useful to read.

And **always** cretae a feature branch before you do something to avoid such situations.

**Comment by emmenlau** [comment]
I realized that I create this mess a week ago, and switched to ```git pull --rebase``` now, sorry. But I won't have time to fix my git in a few days. Is there any way you can pull the changes anyways? Or take some pieces like eigen3?

**Comment by Alexpux** [comment]
@emmenlau  will you rebase changes or I will close pull request

**Comment by emmenlau** [comment]
I will rebase the changes but only in a week, no time right now :-( You can close the pull request if you prefer.

**Pull request closed without merging**
