### PR TITLE
New package: scummvm-2.0.0

### PR DESCRIPTION
**Pull request by rootfather**
After learning how to make PKGBUILDS, I thought it might be funny if there's a mingw-package of ScummVM (https://www.scummvm.org).

So here we go.

### CODE REVIEW

**Comment by filnet** [comment]
I want Doom now.

**Comment by rootfather** [comment]
Let me see what I can do about it. :)

**Comment by rootfather** [comment]
@Alexpux, can you tell me how long it takes on average to make new packages available in the repository?

**Comment by rootfather** [comment]
Hm... still not available in the repo?

**Pull request merged**
