### PR TITLE
Make sure that pytest executables actually run so we use those with o…

### PR DESCRIPTION
**Pull request by JPeterMugaas**
…ur packages.

### CODE REVIEW

**Comment by lazka** [comment]
What does this fix?

**Comment by JPeterMugaas** [comment]
Alright, without this, trying to execute something like "py.test" from the command line would not work.  Without it, it would probably complain about something not being found in the /usr path.

**Comment by lazka** [comment]
executing py.test works fine here... but ok..

**Comment by JPeterMugaas** [comment]
I think what it could be is that I build mingw-w64 packages and do testing from the MSYS prompt using the MSYS menu item as opposed to the "mingw64" or "mingw32" menu item.    But such things can be telling because some scripts that were built for mingw-w64 could mistakenly be run in the MSYS python interpreter and vice-versa.

**Comment by lazka** [comment]
Would changing the shebang to just "#!python3.exe" work? It seems to here.

**Pull request merged**
