### PR TITLE
Rebuild glibmm/fontconfig (without _time32 bug in mingw-w64)

### PR DESCRIPTION
**Pull request by Ede123**
Last build was with buggy version of mingw-w64 which was linking
with _time32 which is not available on Windows XP

(see https://sourceforge.net/p/mingw-w64/support-requests/133/)

### CODE REVIEW

**Comment by Ede123** [comment]
poppler needs a rebuild, too (I saw it is WIP already)

More binaries containing the broken _time32 call (determined with grep on my local installation):
[_time32.txt](https://github.com/Alexpux/MINGW-packages/files/1602029/_time32.txt)

**Comment by mingwandroid** [comment]
I don't think XP should be supported anymore. Providing software that runs on that OS does people a disservice since it encourages them to stay on an operating system that does not receive security patches.

**Comment by Ede123** [comment]
I agree. However in this case there was an issue in the toolchain that is now fixed and shipping binaries that are known to be broken on purpose does not seem to be the proper way to end support for an OS...

**Comment by mingwandroid** [comment]
It's a fine way to stop support IMHO, it's what everyone does to effect such a change.

**Comment by Ede123** [comment]
Yes, this is now outdated.

**Pull request closed without merging**
