### PR TITLE
boost: update to 1.67.0

### PR DESCRIPTION
**Pull request by Adsun701**
This updates boost to 1.67.0.

### CODE REVIEW

**Comment by Alexpux** [comment]
@Adsun701 after building check that both python 2 and 3 libraries builded and they linked with proper python libraries

**Comment by Adsun701** [comment]
OK, so only python2 libraries were built. Let me work on linking the python3 libraries.

One thing I've noticed is the naming change from `${MINGW_PREFIX}/lib/libboost_python-mt.a` to `${MINGW_PREFIX}/lib/libboost_python27-mt.a`.

**Comment by Alexpux** [comment]
@Adsun701 I think this is not good fix for python. All previous releases are building both python modules in one time. I disagree with such changes

**Comment by Adsun701** [comment]
The boost python3 libraries are being built using the python2 include headers and overwriting the previous boost python2 libraries. I really don't know how to fix this, so I posted a gist here:

[https://gist.githubusercontent.com/Adsun701/ca75e86609571d267d6125c60d2a191c/raw/e9ee7459a1d928f37aeb4cdd8de7b9830e8c81f8/mingw-w64-boost-1.67.0-1-x86_64-build.log](url)

**Comment by Alexpux** [comment]
@Adsun701 in the past version patch boost-1.64-default-python.patch fix this problem but now you comment it

**Comment by Adsun701** [comment]
Actually, the patch boost-1.64-default-python.patch is not needed anymore, as the code that patch reverts has been reverted for version 1.67.0. The real problem was specifying more than one python version in the command arguments, which I just fixed in a new commit. Now both boost python libraries are built and link against the appropriate python.

**Pull request merged**
