### PR TITLE
Add support for Azure Pipelines. See #4396

### PR DESCRIPTION
**Pull request by lazka**
This creates a mingw32 and a ming64 job running on Server 2012r2

### CODE REVIEW

**Comment by lazka** [comment]
Once that file is in master I can enable it on the azure side of things.

**Comment by mati865** [comment]
While at CI topic Tea could be disabled as it doesn't help anymore and only confuses people.

**Comment by lazka** [comment]
One thing I just noticed is that it doesn't support any UI stuff (interactive mode) compared to appveyor. I don't think we need it.. or do we?

**Comment by lazka** [comment]
> One thing I just noticed is that it doesn't support any UI stuff (interactive mode) compared to appveyor. I don't think we need it.. or do we?

According to https://github.com/mesonbuild/meson/issues/4154#issuecomment-421220046 the server2016 one supports it, so if it turns out to be a problem we can switch there.

**Comment by lazka** [comment]
I'm taking the liberty to just merge this so we can see how it works. With tea-ci we are used to CI not working anyway so things wont get worse anyway.

**Pull request merged**
