### PR TITLE
opencv: add opencv_contrib

### PR DESCRIPTION
**Pull request by filnet**
Requires vtk 7.0.0-2.

Switched to the official opencv repo.

opencv_contrib is needed by gst-plugins-bad to build the opencv plugin.

### CODE REVIEW

**Comment by mati865** [comment]
```
[MSYS2 CI] Approving recipe quality
	failure: mingw-w64-opencv: missing license
[MSYS2 CI] FAILURE: Approving recipe quality failed.
```

**Comment by filnet** [comment]
Should be fixed.

See https://github.com/opencv/opencv/blob/master/LICENSE

**Comment by mati865** [comment]
Ideally license should be 'BSD' and license file installed with package like on Arch https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/opencv#n99
But it's my mistake I didn't mention it earlier.

Anyway looks good to me

**Comment by filnet** [comment]
CI fails because it using vtk 7.0.0-1 (needs vtk 7.0.0-2)

**Comment by mati865** [comment]
It's not a problem

**Pull request merged**
