### PR TITLE
curl: add winssl variant

### PR DESCRIPTION
**Pull request by Chilledheart**
configuring with gnutls is conflict with openssl or winssl option.
removing it should be safe.

### CODE REVIEW

**Comment by Alexpux** [comment]
I don't want to have the same packages with different options. Feel free to have it in your local repo

**Comment by mingwandroid** [comment]
Should it not provide for all 3 variants? gnutls, openssl or winssl? If the guntls build isn't working ATM then that should be fixed so it is used by default. Then after that you can have suffixes for those who want to use the other versions in the PKGBUILD file, @Alexpux does this sound ok?

**Comment by Alexpux** [comment]
From my POV winssl conflict with OpenSSL and if you want to use package builded with winssl then other packages also need to be builded with winssl instead OpenSSL.
Also I don't want to build all this variants of one package. So only default variant will be present in repo

**Comment by Chilledheart** [comment]
It is is a pity that it is not going to be merged, though I am fine with that. I am keeping maintain it in my local repo. Feel free if you want to reopen it in the future.

**Comment by Alexpux** [comment]
Maybe instead creating new PKGBUILD you can merge changes in original curl PKGBUILD. Where user can change variant of building.

**Comment by Chilledheart** [comment]
It looks like a good option. I have removed the winssl directory, does it look better?

**Comment by Alexpux** [comment]
Do not add '_namesuff'. This is just the same curl package but builded with gunnels or openssl

**Comment by Chilledheart** [comment]
- removed `_namesuff`
- add gnutls variant

**Pull request merged**
