### PR TITLE
WIP: Rebuilds for libidn2 library name change

### PR DESCRIPTION
**Pull request by lazka**
See https://github.com/Alexpux/MINGW-packages/issues/4844#issuecomment-452742844

### CODE REVIEW

**Comment by lazka** [comment]
gnutls doesn't build, help welcome

**Comment by Alexpux** [comment]
@lazka most of this packages already rebuilded and changes in repo already. You need remove ````autogen```` package to fix building gnutls

**Comment by lazka** [comment]
@Alexpux OK, thanks :)

**Comment by lazka** [comment]
just in case, gnutls is broken in the repo now.

**Comment by Alexpux** [comment]
Rebuilded version not uploaded yet

**Pull request closed without merging**
