### PR TITLE
glbinding: Updated to 2.0.0 (shared library only)

### PR DESCRIPTION
**Pull request by nazar554**
The source tarball contains `CMakeLists.txt` with CRLF line endings, so I made a CRLF patch but git wants to make it LF. How to go around this?
Also upstream started using CMake export files, so side by side static and shared installation is not possible without separate prefix. Is it possible to make a `glbinding-static` package that conflicts with shared one?

### CODE REVIEW

**Comment by nazar554** [comment]
I figured out a workaround, don't know if it's okay

**Comment by Alexpux** [comment]
You can safely convert patch to have LF line endings

**Comment by nazar554** [comment]
But I still need to make it CRLF in `prepare()`? Because otherwise patch fails due to different line endings.

**Comment by Alexpux** [comment]
No it apply patch with different line endings

**Comment by nazar554** [comment]
Looks like it worked. Want me to rebase this into a single commit?

**Pull request merged**
