### PR TITLE
Added mingw-w64-glbinding-git package

### PR DESCRIPTION
**Pull request by nazar554**
glbinding project is on GitHub, so I made a -git package. I don't know if `pkgver()` looks ok. This package requires no patch (issue fixed upstream).

### CODE REVIEW

**Comment by mingwandroid** [comment]
They do build releases at https://github.com/cginternals/glbinding/releases.

.. I encourage having -git when possible, however, if the releases are frequent enough then you should also add a package for that which Alexey will build the binary packages from.

**Comment by Alexpux** [comment]
Please look into my fixes for regular glbindings:
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-glbinding

**Comment by Alexpux** [comment]
@mingwandroid, regular PKGBUILD already committed. So "git" will not be build by me in any case

**Comment by mingwandroid** [comment]
why'd you close it?

**Pull request closed without merging**
