### PR TITLE
Another try to pull lfcxml-1.2.1 and cego-2.28.1

### PR DESCRIPTION
**Pull request by bjlemke**
After git pull --rebase another try to get things in sync ..

### CODE REVIEW

**Comment by Alexpux** [comment]
Rebase on top :)

**Comment by bjlemke** [comment]
Next try, please check. Thanks

**Comment by Alexpux** [comment]
Wow. Why you include files not from your commit?

**Comment by bjlemke** [comment]
Because I still do not really unterstand the git rebase HEAD~x command.
After pull rebase, I still got several commit from other projects.

**Comment by bjlemke** [comment]
I think we are clean now :)

**Comment by bjlemke** [comment]
Hi Alex,

after several iterations, I learned the following procedure how to commit changes 
for managed packages to your repository.
Please correct, if required, so I can use this procedure for future pull requests to save us some time :)

Perhaps it would be useful, to provide a similar README for other novice contributors ...

1. Checkout master from remote with
	
	git checkout master

2. Sync upstream with your local repository

	git pull —rebase upstream master

3. Deploy required changes to your local repository

        I used another local mirror and just copied updated or new files to the local repository

4. Commit your changes

	git commit

5. If required, go to step 3 for further changes, otherwise proceed with this procedure

6. Rebase your commits ( just required, if multiple commits have been performed )

	git rebase -i HEAD~<number of commits>

	Just leave the first line and change subsequent lines from pick to squash.
	This squashs all your performed commits to a single commit

7. Push local repository to remote

	git push origin master —force

8. Create a pull request to upstream ( via Web Gui )

Happy new year :)

Best regards,
Björn

Björn Lemke
lemke@lemke-it.com
http://www.lemke-it.com

**Comment by DavidEGrayson** [comment]
@bjlemke Most projects like to see pull requests with a minimal number of commits that are based on a recent commit from their master branch.  I've made several successful pull requests to this project.  My tips for achieving that are:

1. Plan to make a new branch for each of your pull requests instead of doing pull requests on your master branch.  This allows you to have multiple pull requests happening concurrently, and it means you are less likely to accidentally push a change to one of the pull request branches (which updates the pull request).
2. The master branch on your local repository and GitHub fork should just be used to track what the upstream project is doing.  If your master branch has diverged from the upstream, you can fix it with a series of commands like this:

    ````sh
    git fetch origin
    git checkout master
    git reset --hard origin/master
    git push -f mine master:master
    ````

I was going to continue this post and write some instructions for how to make a pull request, but then I realized that my workflow differs depending on how long the change will take, so it's kind of hard to describe.

:smile:  :new: :calendar:!

**Pull request merged**
