### PR TITLE
clang: fix 32 bit LLDB build

### PR DESCRIPTION
**Pull request by mati865**
32-bit version fails to build

### CODE REVIEW

**Comment by mati865** [comment]
This hack: [1.patch.txt](https://github.com/Alexpux/MINGW-packages/files/582322/1.patch.txt) allowed me to build lldb but it's untested.
If someone knows lldb and want's to test this patch the feedback would be nice.

**Comment by mati865** [comment]
@martell what do you think about hack from previous comment?

**Comment by martell** [comment]
According to https://msdn.microsoft.com/en-us/library/14h5k7ff.aspx it seem fine.
It depends on what the `struct stat` actually is.
https://github.com/llvm-mirror/lldb/blob/master/source/Host/windows/FileSystem.cpp#L256
If there is no run time error because of that then this looks good to me for a hack to get it working.

**Comment by mati865** [comment]
Since Vista time is a 64 bit value so it can crash on WinXp. Yet it's probably better to have lldb for Vista and newer than not having it at all.
I'll update this PR.

**Comment by mati865** [comment]
Neither 32 bit or 64 bit lldb crashes.
LLDB is probably fine to deploy it.

**Pull request merged**
