### PR TITLE
added current git repos for dlfcn / isl

### PR DESCRIPTION
**Pull request by ABaumgaertner**
Hi Alex,

small update for current git repos for 2 packages:
mingw-w64-dlfcn-git
mingw-w64-isl-git

for dlfcn head is used
for isl a version tag is specified

thx,
Andreas

### CODE REVIEW

**Comment by mingwandroid** [comment]
What is the point? These projects are small and change so infrequently I can't see any reason to have git versions.

**Comment by Alexpux** [comment]
I'm agree with @mingwandroid. There are no reasons to build this projects from git.
Need just move dlfcn-svn package to dlfcn-git as googlecode will be closed. I will update dlfcn-svn package myself.

**Comment by ABaumgaertner** [comment]
? - take a look at http://repo.or.cz/w/isl.git/shortlog

**Comment by Alexpux** [comment]
We don't want to build prerequisites for GCC  from git, sorry. If you need it then create your own local packages for it.

**Comment by Alexpux** [comment]
dlfcn-win32 packages updated by https://github.com/Alexpux/MINGW-packages/commit/1bbecce88a5b55fd7002b8ac4a8827eee18f72f1

**Comment by mingwandroid** [comment]
Ok so ISL is bigger and still quite active, we could merge the PKGBUILD for developers who need it, but I don't think we should build packages still .. @ABaumgaertner will that be ok?

**Comment by Alexpux** [comment]
Don't do it. I will update ISL to 0.14.1 soon. Seems ISL migrate to another site.

**Comment by Alexpux** [comment]
ISL updated to 0.14.1 by https://github.com/Alexpux/MINGW-packages/commit/b194e5fa2d87e8b43ab82674036b7c40e634a0dc

**Comment by ABaumgaertner** [comment]
mentioning would be nice - I believe this is how it works ;-) ... anyway - you are the owners 
thanks for msys2 and mingw-packages - this is really awesome!

**Pull request closed without merging**
