### PR TITLE
Add kate and kwrite

### PR DESCRIPTION
**Pull request by zrax**
Depends on #4526

### CODE REVIEW

**Comment by Alexpux** [comment]
@zrax currently kate/kwrite fail to install because, first them install data folder in bin - it must not do it, second - only one package seems need to have this folder. I think you dont need to split package to kate/kwrite, instead add ````provides```` entry in PKGBUILD and package all in one

**Comment by mati865** [comment]
Data in bin directory is configured in `extra-cmake-modules`, see https://github.com/mati865/MINGW-packages/blob/kdef5/mingw-w64-extra-cmake-modules/use-UNIX-paths-for-MSYS.patch for incomplete fix.

**Comment by Alexpux** [comment]
@mati865 we use MINGW cmake for mingw packages, so ````NOT MSYS```` is not for MINGW target

**Comment by mati865** [comment]
@Alexpux `MSYS` was defined somehow so it worked. There were more places requiring changes like that.

**Comment by zrax** [comment]
The use of the 'data' folder in bin is due to Qt's unfortunate `QStandardPaths::GenericDataLocation` paths on Windows...  After digging into it for a while, I determined that leaving things that don't need to be accessed by other packages in bin/data was easier than fixing every use of `QStandardPaths` in KF5 (there are many) :(.  However, in my tests, these unfortunate install locations didn't cause any install conflicts, so I'm curious what you ran into...

**Comment by Alexpux** [comment]
Both kwrite and Kate packages container the same files in bin data, so it conflicts. But in any cases I will not accept packages with bin/data folders

**Comment by zrax** [comment]
Hmm, then will you accept a patch that changes the behavior of a fundamental Qt5 API?  That's the only other reasonable solution I can think of at the moment...

**Comment by zrax** [comment]
Wow, that looks a whole lot more complicated than the solution I had in mind...   I'll look into it more later, but I was thinking to just add `QDir::cleanpath(QCoreApplication::applicationDirPath() + "../share")` to the end of the QStandardPaths::GenericDataLocation search paths.  It means it would (potentially) change the behavior of Qt apps, but it also means you don't have to patch every usage to make it work.

**Comment by mati865** [comment]
Yes it's complicated but it (hopefully) doesn't break anything.
I'd avoid changing official APIs, many people use MSYS2 provided Qt build to distribute with their programs. Having API that doesn't mach official Qt API would be probably big turn-off for them.

**Comment by zrax** [comment]
Hmm, good point.

**Comment by gbschenkel** [comment]
I got error when trying to run it.
C:/dev/msys64/mingw64/bin/kate.exe: error while loading shared libraries: Qt5Xml.dll: cannot open shared object file: No such file or directory

https://github.com/Alexpux/MINGW-packages/issues/4534

**Pull request merged**
