### PR TITLE
gpgme: make mkdefsinc use CPPFLAGS

### PR DESCRIPTION
**Pull request by lovetox**
This fixes the build on the CI and some Windows systems

see #4165 

thanks to @vyache-slav for providing the patch

### CODE REVIEW

**Comment by lovetox** [comment]
Do i have to up `pkgrel=` to get people updated?

**Comment by lovetox** [comment]
tea-ci seems to have a problem fining the libgpg-error package

**Comment by Alexpux** [comment]
@lovetox yes you need increase pkgrel

**Comment by lovetox** [comment]
Done !

**Pull request merged**
