### PR TITLE
Make p11-kit use spawn instead of exec to call external helper programs

### PR DESCRIPTION
**Pull request by sschuberth**
This fixes files not being written before p11-kit exits.

### CODE REVIEW

**Comment by sschuberth** [comment]
That was a quick merge, thanks! Could you post back here once the binaries are available?

**Comment by Alexpux** [comment]
Binaries are available now.
For future, do not forget to increase "pkgrel" in PKGBUILD

**Comment by sschuberth** [comment]
> Binaries are available now.

Thanks!

> For future, do not forget to increase "pkgrel" in PKGBUILD

Will do!

**Comment by mingwandroid** [comment]
@sschuberth thanks for taking care of this!

**Pull request merged**
