### PR TITLE
clang: more fixes, ready for using

### PR DESCRIPTION
**Pull request by mati865**
There are no more `_float128` errors and it can be build thanks to disabling lldb.
Tomorrow I'm gonna try if Clang can compile itself but I suppose to face mingw-w64 bug.

### CODE REVIEW

**Comment by mati865** [comment]
I still couldn't find out why .cmake files aren't put into `/mingw{32,64}/share/llvm/cmake`

**Comment by mati865** [comment]
Clang 32 bit almost compiles itself, linking error at 85% (bugpoint tool):
```
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0x693): undefined reference to `pthread_mutex_init'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0x6a4): undefined reference to `pthread_mutex_init'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0x6d9): undefined reference to `pthread_mutex_init'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0x8f8): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0x9be): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0x9f6): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0xa7a): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text+0xa89): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEE19handleKnownFunctionENS1_21OrcRemoteTargetRPCAPI9JITFuncIdE]+0x26f): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEED2Ev]+0xc1): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote10RPCChannelD2Ev]+0xe): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote10RPCChannelD2Ev]+0x1a): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN12FDRPCChannelD0Ev]+0xe): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN12FDRPCChannelD0Ev]+0x1a): undefined reference to `pthread_mutex_destroy'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote10RPCChannelD0Ev]+0xe): more undefined references to `pthread_mutex_destroy' follow
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj20EFvvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj20EFvvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj2EFiyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIiEEJyEEEJLj0EEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x5c): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj2EFiyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIiEE]+0x22): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj2EFiyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIiEE]+0x8e): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj3EFiySt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISC_EEEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIiEEJySE_EEEJLj0ELj1EEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x8b): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj3EFiySt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIiEE]+0x22): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj3EFiySt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIiEE]+0x8e): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj4EFvyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyEEEJLj0EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x58): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj4EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj4EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj5EFvyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyEEEJLj0EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x58): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj5EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj5EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj6EFvyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyEEEJLj0EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x58): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj6EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj6EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj7EFvyjEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyjEEEJLj0ELj1EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x7e): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj7EFvyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj7EFvyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj8EFvyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyEEEJLj0EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x58): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj8EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj8EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj9EFvyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyEEEJLj0EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x58): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj9EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj9EFvyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj10EFSt5tupleIJyyjEEyjEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIS7_EEJyjEEEJLj0ELj1EEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x82): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj10EFSt5tupleIJyyjEEyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIS5_EE]+0x30): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj10EFSt5tupleIJyyjEEyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIS5_EE]+0x5d): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj11EFvvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj11EFvvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj12EFSt5tupleIJyjEEvEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIS7_EEJEEEJEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x2e): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj12EFSt5tupleIJyjEEvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIS5_EE]+0x28): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj12EFSt5tupleIJyjEEvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIS5_EE]+0xb2): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj13EFyNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIyEEJRKSB_EEEJLj0EEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x8c): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj13EFyNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIyEE]+0x28): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj13EFyNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIyEE]+0x9c): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj14EFSt5tupleIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjjjjEEvEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedISD_EEJEEEJEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x2b): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj14EFSt5tupleIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjjjjEEvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedISB_EE]+0x22): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj14EFSt5tupleIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjjjjEEvEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedISB_EE]+0x93): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj15EFSt6vectorIcSaIcEEyyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIS8_EEJyyEEEJLj0ELj1EEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x76): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj15EFSt6vectorIcSaIcEEyyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIS6_EE]+0x30): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj15EFSt6vectorIcSaIcEEyyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIS6_EE]+0x5d): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj16EFvyjEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyjEEEJLj0ELj1EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x7e): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj16EFvyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj16EFvyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj17EFyyyjEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_8ExpectedIyEEJyyjEEEJLj0ELj1ELj2EEEENS_5ErrorERS4_T_NS_14index_sequenceIJXspT0_EEEE]+0xb0): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj17EFyyyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIyEE]+0x28): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj17EFyyyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RNS_8ExpectedIyEE]+0x9c): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj19EFvyyjEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyyjEEEJLj0ELj1ELj2EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0xac): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj19EFvyyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj19EFvyyjEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj21EFvNS1_18DirectBufferWriterEEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJS6_EEEJLj0EEEESG_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0xca): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj21EFvNS1_18DirectBufferWriterEEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS9_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj21EFvNS1_18DirectBufferWriterEEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS9_]+0x74): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase13HandlerHelperINS1_10RPCChannelEtNS2_14FunctionHelperIjLj22EFvyyEEEE13readAndHandleINS2_15MemberFnWrapperINS1_21OrcRemoteTargetServerI12FDRPCChannelNS0_13OrcGenericABIEEENS_5ErrorEJyyEEEJLj0ELj1EEEESF_RS4_T_NS_14index_sequenceIJXspT0_EEEE]+0x6e): undefined reference to `pthread_mutex_unlock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj22EFvyyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x27): undefined reference to `pthread_mutex_lock'
CMakeFiles/lli-child-target.dir/objects.a(ChildTarget.cpp.obj):(.text[__ZN4llvm3orc6remote7RPCBase14FunctionHelperIjLj22EFvyyEE7respondINS1_10RPCChannelEtEENS_5ErrorERT_T0_RS8_]+0x74): undefined reference to `pthread_mutex_unlock'
```
Clang 64 bit fails at mingw-w64 headers: https://sourceforge.net/p/mingw-w64/mailman/message/35433667/

@martell want to add something? 😃

**Comment by martell** [comment]
@mati865 Try changing this https://reviews.llvm.org/rL241485 for your pthread errors.
Awhile back I added an option to disable pthreads https://reviews.llvm.org/rL241929

This seems like the correct approach.

```
if (!Args.hasArg(options::OPT_no_pthread))
  CmdArgs.push_back("-lpthread");
```

I remember creating this exact patch before but it was not accepted upstream because mingw.org compilers don't link libpthread by default.
The stance on dropping support for mingw.org will change though shortly.
I don't think that should be an issue to have this locally for now.

Alternatively before someone suggested to me that we can `-Wl,--as-needed` when linking with libstdc++ to resolve this also. I never went with that approach because I switched to supporting libc++.


I was in an email thread about the __float128 errors and it just died.
I assume this is the reason why. I will try and get this backported to 3.9.1

**Comment by mati865** [comment]
First thing I've tried after this error was adding `-pthread` to C and CXX flags but it didn't help.
I'll try bootstrapping with libc++ and 64 bit Clang case is still open (had no time to check it yet).

**Comment by mati865** [comment]
@martell, with this change it went a bit further (bugpoint is now 83%) to eventually fail with:
```
[ 84%] Linking CXX executable ../../bin/llvm-cov.exe
[ 84%] Linking CXX executable ../../bin/llvm-dwarfdump.exe
../../lib/libLLVMSupport.a(ThreadPool.cpp.obj):(.text[__ZNSt13__future_base13_State_baseV213_M_set_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEb]+0x45): undefined reference to `std::__once_callable'
../../lib/libLLVMSupport.a(ThreadPool.cpp.obj):(.text[__ZNSt13__future_base13_State_baseV213_M_set_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEb]+0x4b): undefined reference to `std::__once_call'
../../lib/libLLVMSupport.a(ThreadPool.cpp.obj):(.text[__ZSt16__once_call_implISt12_Bind_simpleIFSt7_Mem_fnIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS2_12_Result_baseENS6_8_DeleterEEvEEPbEEPS3_SB_SC_EEEvv]+0x12): undefined reference to `std::__once_callable'
../../lib/libLLVMSupport.a(ThreadPool.cpp.obj):(.text[__ZNSt13__future_base13_State_baseV221_M_set_delayed_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEESt8weak_ptrIS0_E]+0x63): undefined reference to `std::__once_callable'
../../lib/libLLVMSupport.a(ThreadPool.cpp.obj):(.text[__ZNSt13__future_base13_State_baseV221_M_set_delayed_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEESt8weak_ptrIS0_E]+0x69): undefined reference to `std::__once_call'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/llvm-cov/CMakeFiles/llvm-cov.dir/build.make:341: bin/llvm-cov.exe] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:49455: tools/llvm-cov/CMakeFiles/llvm-cov.dir/all] Błąd 2
```

**Comment by martell** [comment]
@mati865 sounds likt a difference between what clang and gcc produce.
https://reviews.llvm.org/rL243438 might help, should be supported for mingw-w64 targets

Can you check libstdc++ for `___emutls_v._ZSt15__once_callable` instead of `__ZSt15__once_callable` which is what clang emits

**Comment by mati865** [comment]
You are right. So we should check for mingw with libstdc++ here: https://github.com/llvm-mirror/clang/blob/release_39/lib/Driver/Tools.cpp#L5011 and change line 10493 like in your previous post but with check for libstdc++.
Any suggestions how to properly check for it?

**Comment by mati865** [comment]
@martell, 32-bit Clang bootstrapped and seems to be working.
It's 278.11 MB smaller than GCC build (it might be also bad news; more testing needed).

But I wouldn't upload patches that surely break libc++, I'll wait for your response about checks.

**Comment by mati865** [comment]
32 bit Clang can successfully build itself and it's working.
64 bit fails with:
```
In file included from
D:/projekty/msys2/MINGW-packages/mingw-w64-clang/src/llvm-3.9.0.src/projects/libcxx/src/thread.cpp:35:
In file included from
D:\projekty\msys2\clang\msys64\mingw64\x86_64-w64-mingw32\include\windows.h:114:
D:\projekty\msys2\clang\msys64\mingw64\x86_64-w64-mingw32\include\stralign.h:121:37:
error: cannot initialize return object of type 'PUWSTR_C' (aka 'wchar_t *')
with an rvalue of type 'const wchar_t *'
    if(WSTR_ALIGNED(String)) return wcschr((PCWSTR)String,Character);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\projekty\msys2\clang\msys64\mingw64\x86_64-w64-mingw32\include\stralign.h:125:37:
error: cannot initialize return object of type 'PUWSTR_C' (aka 'wchar_t *')
with an rvalue of type 'const wchar_t *'
    if(WSTR_ALIGNED(String)) return wcsrchr((PCWSTR)String,Character);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Anyway I thing it can replace Clang 3.8.0 from repo right now

**Comment by mati865** [comment]
Right now Clang compiled by itself cannot link against libc++, soon I'll test GCC build.

**Pull request merged**
