### PR TITLE
gst-python: make prepare step similar to other gst packages

### PR DESCRIPTION
**Pull request by filnet**

### CODE REVIEW

**Comment by filnet** [comment]
gst-python 1.14.0 source tarball is missing some files (autogen.sh and others).
this has been notified upstream and is fixed in the future 1.14.1 release.

**Comment by filnet** [comment]
Issue has been fixed upstream in 1.14.1.

See https://cgit.freedesktop.org/gstreamer/gst-python/commit/?h=1.14&id=2025f714a21c15cc0ee9a3d3f3924824afccb5cf

**Comment by lazka** [comment]
> Issue has been fixed upstream in 1.14.1 so this PR is good to merge.

From what I see you need to bump the version to 1.14.1 first, no?

**Comment by filnet** [comment]
> From what I see you need to bump the version to 1.14.1 first, no?

Yes. And all of gstreamer.

**Comment by filnet** [comment]
Branch was rebased against current master.
Package builds fine.

**Comment by lazka** [comment]
I've included this in #4505

**Pull request closed without merging**
