### PR TITLE
glib2: enabled gtk-doc installation (closes #2355).

### LINKED ISSUE #2355: mingw-w64-glib2 doesn't install documentation
It seems the gtk-doc documentation is not installed, which makes it not show in the devhelp help browser. It should either pass the --enable-gtk-doc argument to the configure script or have a specific package of pre-compiled docs.

### PR DESCRIPTION
**Pull request by KrullKorg**

### CODE REVIEW

**Comment by Alexpux** [comment]
To use gtk-doc from msys packages try to do as I do for evince:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-evince/PKGBUILD#L53

**Comment by KrullKorg** [comment]
i doesn't work, but i haven't delved into

**Comment by Alexpux** [comment]
Here is proper fix for building documentation https://github.com/Alexpux/MINGW-packages/commit/34991830a660a14c2d04ee3c47fac77295ba9213

But there are some problems  with it:
````
make[4]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference/gobject'
Making all in gio
make[4]: Entering directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference/gio'
  DOC   Preparing build
  DOC   Building XML
  DOC   Scanning header files
  DOC   Introspecting gobjects
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x243): undefined reference to `g_desktop_app_info_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x24f): undefined reference to `g_desktop_app_info_lookup_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x2bb): undefined reference to `g_file_descriptor_based_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6cf): undefined reference to `g_unix_connection_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6db): undefined reference to `g_unix_credentials_message_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6e7): undefined reference to `g_unix_fd_list_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6f3): undefined reference to `g_unix_fd_message_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x6ff): undefined reference to `g_unix_input_stream_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x70b): undefined reference to `g_unix_mount_monitor_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x717): undefined reference to `g_unix_output_stream_get_type'
.libs/gio-scan.o:gio-scan.c:(.text.startup+0x723): undefined reference to `g_unix_socket_address_get_type'
collect2.exe: error: ld returned 1 exit status
Linking of scanner failed:
make[4]: *** [Makefile:959: scan-build.stamp] Error 1
make[4]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference/gio'
make[3]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs/reference'
make[3]: *** [Makefile:486: all-recursive] Error 1
make[2]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared/docs'
make[2]: *** [Makefile:486: all-recursive] Error 1
make[1]: Leaving directory '/scripts/mingw-w64-glib2/src/build-x86_64-shared'
make[1]: *** [Makefile:1238: all-recursive] Error 1
make: *** [Makefile:859: all] Error 2
````

Someone need to see it.

**Comment by KrullKorg** [comment]
My patch simply use (copy) the already built gtk-doc

**Comment by Alexpux** [comment]
@KrullKorg your patch is simple but not right. If documentation can be builded then it need be buildable at least. 
There are also other issue about gtk-doc https://github.com/Alexpux/MINGW-packages/issues/2328
I\m show how it can be fixed on GLIB2 example

**Comment by KrullKorg** [comment]
but if it is already built why we need to rebuild it?

**Comment by Alexpux** [comment]
@KrullKorg , thinking as you we can use builded libraries from somewhere and build anything ourself.
Also building it ourself show that something wrong with it.

**Comment by KrullKorg** [comment]
two things completly differents: gtk-doc is provided in the source package (when it is a tar.gz, not from git) already generated, it doesn't change if i build the package under msys2 or under gnu/linux

**Pull request closed without merging**
