### PR TITLE
Updated GDAL to version 2.1.1

### PR DESCRIPTION
**Pull request by moispe**
Updated GDAL to version 2.1.1 as it contains some important bug fixes compared to previous version.

### CODE REVIEW

**Comment by mati865** [comment]
`pkgrel` is wrong

**Comment by moispe** [comment]
What it should be? Now I just incremented it by one.

**Comment by mati865** [comment]
`pkgrel` is reset every time `pkgver` is bumped

**Comment by Alexpux** [comment]
I'm not be able build GDAL right now. I'm get error:
````
libtool: compile:  x86_64-w64-mingw32-g++ -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/port -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/gcore -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/alg -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/ogr -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/ogr/ogrsf_frmts -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/gnm -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/apps -march=x86-64 -mtune=generic -O2 -pipe -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wnull-dereference -Wduplicated-cond -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -DOGR_ENABLED -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DDONT_DEPRECATE_SPRINTF -I/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/port -I/mingw64/include/qhull -I/mingw64/include -DGDAL_COMPILATION -I/mingw64/include -DHAVE_CURL -DHAVE_LIBZ -I/mingw64/include/libxml2 -DHAVE_LIBXML2 -DHAVE_CRYPTOPP -DUSE_ONLY_CRYPTODLL_ALG -c cpl_vsil_win32.cpp  -DDLL_EXPORT -DPIC -o .libs/cpl_vsil_win32.o
cpl_vsil_win32.cpp: In member function 'virtual char** VSIWin32FilesystemHandler::ReadDirEx(const char*, int)':
cpl_vsil_win32.cpp:830:31: error: '_findclose' was not declared in this scope
             _findclose( hFile );
                               ^
cpl_vsil_win32.cpp:847:28: error: aggregate 'VSIWin32FilesystemHandler::ReadDirEx(const char*, int)::_finddata_t c_file' has incomplete type and cannot be defined
         struct _finddata_t c_file;
                            ^~~~~~
cpl_vsil_win32.cpp:857:56: error: '_findfirst' was not declared in this scope
         if ( (hFile = _findfirst( pszFileSpec, &c_file )) != -1L )
                                                        ^
cpl_vsil_win32.cpp:864:48: error: '_findnext' was not declared in this scope
             } while( _findnext( hFile, &c_file ) == 0 );
                                                ^
cpl_vsil_win32.cpp:866:31: error: '_findclose' was not declared in this scope
             _findclose( hFile );
                               ^
make[1]: *** [../GDALmake.opt:654: cpl_vsil_win32.lo] Ошибка 1
make[1]: выход из каталога «/c/repo/mingw-w64-gdal/src/build-x86_64-w64-mingw32/port»
make: *** [GNUmakefile:71: port-target] Ошибка 2
````

**Comment by moispe** [comment]
What command are you using to initiate the build? I'm just wondering if I have done something differently on my computer because I was able to build the package for mingw32 and mingw64.

**Comment by Alexpux** [comment]
I'm always use next command:
````LC_ALL=C LANGUAGE=en_US.UTF-8 makepkg-mingw -Ccfsi --sign --skippgpcheck --nocheck -L && MINGW_INSTALLS=mingw32 LC_ALL=C makepkg-mingw --allsource --skippgpcheck --sign -f```

Maybe I'm have detected some more dependencies for GDAL by configure script and its fault build some additional sources. Verify that you have builded cpl_vsil_win32.cpp source file

**Comment by moispe** [comment]
I was able to build and install the package by using command you provided above? I also verified that `cpl_vsil_win32.cpp` was built by checking that `cpl_vsil_win32.o` and `cpl_vsil_win32.lo` exists in `\MINGW-packages\mingw-w64-gdal\src\build-i686-w64-mingw32\port\`.

**Comment by Alexpux** [comment]
Ok. Then I need to see myself what is wrong

**Pull request merged**
