### PR TITLE
go: fix build

### PR DESCRIPTION
**Pull request by oysteinkrog**
GOROOT was not set correctly

### CODE REVIEW

**Comment by oysteinkrog** [comment]
Hm, I see now that commit msg was wrong (meant hub, not go). Sorry about that.

**Comment by Alexpux** [comment]
Go still not building...

**Comment by oysteinkrog** [comment]
Hm, I have not been involved in the go package but for me it seems to build without any issues.
What do you mean exactly?

**Comment by Alexpux** [comment]
I can't build. It just hang on after configure

**Pull request merged**
