### PR TITLE
wxwidgets 3.1.0

### PR DESCRIPTION
**Pull request by ncihnegn**
3.0.2 has this bug:
assert "m_menuDepth > 0" failed in wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?"

### CODE REVIEW

**Comment by Alexpux** [comment]
Is wxWidgets are compatible with all our wxWidget packages?

**Comment by ncihnegn** [comment]
From wxwidgets.org:

"Please notice that while 3.1.0 is officially a "development" version because it is not fully compatible with 3.0.x, the list of backwards incompatible changes is very short, so you shouldn't have any problems updating to this version from 3.0.x in practice, and you're encouraged to try this version out and use it in production in spite of its odd version number."

**Comment by Alexpux** [comment]
I think we will skip this version now

**Comment by DoctorWho11** [comment]
Best to wait for the next release of wx 3.1 once 3.0 backwards compatibility is fixed

**Pull request closed without merging**
