### PR TITLE
Add libspiro-git and libuninameslist-git

### PR DESCRIPTION
**Pull request by jtanx**
These packages are used by [FontForge](https://github.com/fontforge/fontforge).

### CODE REVIEW

**Comment by Alexpux** [comment]
libspiro already present.

**Comment by jtanx** [comment]
The provided libspiro is out of date.

**Comment by Alexpux** [comment]
I don't prefer to build git versions of software. I try to minimize such packages. So I don't want to add two more git packages, sorry.

**Comment by jtanx** [comment]
Okay. I would suggest to switch libspiro over to use releases from [here](https://github.com/fontforge/libspiro/releases).

**Pull request closed without merging**
