### PR TITLE
tesseract-ocr updates

### PR DESCRIPTION
**Pull request by Shreeshrii**
use git source, 
add pkgver,
add eng + osd tessdata dependency

Use 3.02.eng.tar.gz from downloads

Use 3.01.osd.tar.gz from downloads

### CODE REVIEW

**Comment by mingwandroid** [comment]
@Shreeshrii , can you squash all these commits into one and name all of the patches along the lines of "tesseract-ocr: Something informative", I don't know who Dave is, or why I want a patch from him :-)

**Comment by mingwandroid** [comment]
Actually, re: squashing, I don't know if that's appropriate, I'll leave that decision up to you, but two commits named "Merge" and "merge" would not look nice in the git log, maybe they just need better names (I didn't look at them yet).

**Comment by Shreeshrii** [comment]
Ray,

Sorry about that. I am not very familiar with git.

FYI, when I was having some problem with using leptonica with tesseract on
mingw2, Dave had sent these patches to use while compiling the image
libraries. Please take a look at the patches and see if they are needed. If
so, I'll figure out how to commit them correctly.



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Alexpux** [comment]
We already have tesseract 3.04 on repo now. Does this pull request still relevant?

**Comment by Shreeshrii** [comment]
Thanks!

​Please close this.​

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by andreygursky** [comment]
Ping: this could be closed.

**Pull request closed without merging**
