### PR TITLE
atom-editor, atom-shell: fix invalid checksum-types

### PR DESCRIPTION
**Pull request by vszakats**
* fix two `shasum` checksum types (with `SKIP` content) to `sha256sum`
* add a missing dependency

### CODE REVIEW

**Comment by fracting** [comment]
Hi @vszakats 

According to build log, mingw-w64-nodejs is missing as makedepends, could you update your patch please? Thanks!

BTW, due to a known bug, nodejs does not work on Wine yet, so the Drone CI is going to fail anyway: https://bugs.wine-staging.com/show_bug.cgi?id=626

I have no idea about the error in Appveyor CI, hopefully someone else understand nodejs could have a look.

**Comment by vszakats** [comment]
Thanks @fracting, update committed. Fingers crossed.

**Comment by fracting** [comment]
I pushed an workaround for winpty to Drone CI: https://github.com/fracting/msys32-docker/commit/e071a65af40bf54206183eb56d32fc046033812b

Now Drone CI fails in the same way with Appveyor CI:

```
==> Starting package()...
    Currently, attempting to make a log fails!
     so for now, please call without -L option
input is not a tty
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by fracting** [comment]
Cross Reference:
Another related error when building on my local machine
https://bugs.wine-staging.com/show_bug.cgi?id=655

**Comment by vszakats** [comment]
May or may not be the same issue, but resembles a bit to the error `./<script>: line <n>: 0: Bad file descriptor` I was getting when running certain (or may I say _any_) `Configure` scripts.

The solution was to open a "dummy file descriptor":
```sh
   exec 0</dev/null && ./configure
```

**Comment by vszakats** [comment]
Reworked this to include the fix only. `sha521sums` isn't a problem at all.

**Comment by vszakats** [comment]
https://github.com/Alexpux/MINGW-packages/pull/1092#issuecomment-187852152 was identified and subsequently fixed as an AppVeyor bug: https://github.com/appveyor/ci/issues/652

**Comment by fracting** [comment]
> #1092 (comment) was identified and subsequently fixed as an AppVeyor bug: appveyor/ci#652

Great!

**Pull request merged**
