### PR TITLE
python3: Update to 3.6.6; drop winXP patches; fix idle/pydoc shebang

### PR DESCRIPTION
**Pull request by lazka**
Python3 doesn't support WinXP since 3.5

### CODE REVIEW

**Comment by Alexpux** [comment]
@lazka I'm working on updating to python 3.7 so I think i will not build 3.6.6

**Comment by lazka** [comment]
@Alexpux ok

**Comment by lazka** [comment]
In case you haven't started working on 3.7 you can still merge this. The included changes should be useful for 3.7 as well.

Otherwise please close this.

**Comment by Alexpux** [comment]
See python-3.7 branch in repo

**Comment by lazka** [comment]
Ah, right :+1:

**Pull request closed without merging**
