### PR TITLE
qt5[-static]: add upstream patch for QTBUG-55482

### PR DESCRIPTION
**Pull request by filnet**
workaround crashes in QtQml code related to dead-store elimination
see https://bugreports.qt.io/browse/QTBUG-55482

### CODE REVIEW

**Comment by mati865** [comment]
Does it resolve https://github.com/Alexpux/MINGW-packages/issues/1713?

**Comment by filnet** [comment]
Seems not :(

$ qtcreator
Segmentation fault

PS: I use official QtCreator not msys2 one.

**Comment by filnet** [comment]
But it does address nasty crashes on application startup if Qt5Qml library is compiled with GCC 6.1.1/6.2.0

**Comment by filnet** [comment]
Hi,

Any ETA for publishing the new qt5 ?

Cheers,
Philippe.

**Comment by Alexpux** [comment]
I'm not plan to rebuild Qt5 in near time. Soon will be 5.6.2 released and then we will think about new packages.

**Comment by filnet** [comment]
No problems. Thanks for answering.

**Pull request merged**
