### PR TITLE
upgrade of lfcxml to version 1.2.1

### PR DESCRIPTION
**Pull request by bjlemke**
+ upgrade of cego to version 2.28.1

Can you give a hint, how to keep the fork in sync ?
If I try the documented procedure, I get unresolved conflicts with other packages.
I don't want to touch any other package files except those, I will maintain !

### CODE REVIEW

**Comment by mingwandroid** [comment]
Yes, `git pull --rebase` pulls the remote changes in and applies you local changes on top (after) them.

**Comment by bjlemke** [comment]
I performed git pull --rebase origin master but I had to skip several merges 
using git rebase --skip
Hope this is still fine ...

**Comment by Alexpux** [comment]
Sorry do it again) I commit another changes

**Comment by bjlemke** [comment]
Big efforts to just update 2 versions numbers ;)

**Pull request closed without merging**
