### PR TITLE
clang: cxxflags fix

### PR DESCRIPTION
**Pull request by wirx6**

### CODE REVIEW

**Comment by mati865** [comment]
Could you also add `"${MINGW_PACKAGE_PREFIX}-libffi"` in https://github.com/Alexpux/MINGW-packages/pull/2540/files#diff-f8431e29bf404d2b6e837a3e6a7e6b00R297 ?
https://github.com/msys2/msys2/issues/30

**Comment by wirx6** [comment]
I also think about adding polly but i don't know if anyone need it.

**Comment by mati865** [comment]
I had no time to test and add it but feel free to do it.

CC @martell BTW

**Comment by wirx6** [comment]
`CXXFLAGS='-O3 -mllvm -polly'` used in some projects brought no error.

**Comment by martell** [comment]
LGTM with 2 nits.
Squash into 1 commit.
Add `=> 3.4.3` for `cmake` build deps to fix build bot.
You may also add yourself as a contributor if you wish :)

**Comment by wirx6** [comment]
Done

**Comment by martell** [comment]
Alexey will probably bump the `pkgrel` when there is a change to build a new package.
We need to backport some other things before we release a new version.
I am currently preoccupied with work and getting everything in before the llvm 5.0 window.
Thanks for the contribution @wirx6

**Comment by martell** [comment]
@Alexpux I see that you changed from PR merges to rebase merges.
Apologies. Do you want to force push to remove the  Merge commit?
I don't feel comfortable force pushing to the master branch myself.

**Comment by mingwandroid** [comment]
We don't have to be super pedantic here. Good have some guidelines but if it's already pushed best not to force push imho, as that can cause problems for contributors.

**Pull request merged**
