### PR TITLE
Add words.txt to sources list for srtp package

### PR DESCRIPTION
**Pull request by marcin-sielski**

### CODE REVIEW

**Comment by Alexpux** [comment]
where is file itself?

**Comment by mati865** [comment]
@Alexpux, here: https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libsrtp.

**Comment by Alexpux** [comment]
Well I see duplicate pull request for this package also

**Comment by Alexpux** [comment]
Fixed by another pull request

**Pull request closed without merging**
