### PR TITLE
Update pyqt to 5.6

### PR DESCRIPTION
**Pull request by patstew**

### CODE REVIEW

**Comment by Alexpux** [comment]
Seems it not buildable.

**Comment by fracting** [comment]
Builds fine: https://tea-ci.org/Alexpux/MINGW-packages/1110

(The failure in https://tea-ci.org/Alexpux/MINGW-packages/1109 is caused by deleted branch, not a build error)

**Comment by Alexpux** [comment]
For me not. I get infinite of qmake processes

**Comment by Alexpux** [comment]
The last hunk in patch about "make" is cause troubles for me so I'm remove it. We need use mingw32-make instead make when building pyqt5

**Pull request merged**
