### PR TITLE
wxWidgets 3.0.2 bug fix.

### PR DESCRIPTION
**Pull request by stambaughw**
There is a know bug in version 3.0.2 of wxWidgets which effects mirrored rendering that causes serious print rendering problems with KiCad.  The bug report can be found at http://trac.wxwidgets.org/ticket/16908.  This pull request applies a patch to wxWidgets 3.0.2 which fixes the issue.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Can you squash all of the merges please. They'd make our history very untidy.

**Comment by stambaughw** [comment]
Please excuse my git ignorance but `git merge --squash` says there is
nothing to do.  What do I need to do flatten the merge history without
completely making a mess of things.

**Comment by stambaughw** [comment]
After several failed attempts at rebasing my local branch, I gave up and
started over.  I've resubmitted the pull request.  I apologize for any
inconvenience.

**Comment by mingwandroid** [comment]
Ah, ok, sorry I didn't get back to you on this, that would've been one of my suggestions actually. 
Generally when resyncing with upstream (assuming you add https://github.com/Alexpux/MINGW-packages as a remote called "upstream") if you use "git fetch upstream" then "git rebase upstream/master" you'll avoid merges and retain a clean history.

Also, you could reset your branch to "upstream/master", re-do your change, then push it to github with --force.

But what you've done is fine.

**Pull request merged**
