### PR TITLE
mingw-w64-flif - 0.3 - New package.  Free Lossless Image Format

### PR DESCRIPTION
**Pull request by JPeterMugaas**
mingw-w64-libraqm - 0.5 - Update that uses new fribidi functionality in 1.x series.
mingw-w64-fribidi-git - git version of Fribidi.  This is temporary because 1.0.1 did not compile here and I wanted new functionality from 1.0x series

### CODE REVIEW

**Comment by Alexpux** [comment]
I will not add fribidi-git package. Wait for stable release.

**Comment by Alexpux** [comment]
Also next time please - 1 commit - 1 package

**Comment by Alexpux** [comment]
squash commits

**Comment by JPeterMugaas** [comment]
I don't know how to squash once things get to github.  Unable.

**Pull request closed without merging**
