### PR TITLE
openssl: Add ca-certificates as optdepends.

### PR DESCRIPTION
**Pull request by fracting**
For https://github.com/Alexpux/MINGW-packages/issues/1086

### CODE REVIEW

**Comment by Alexpux** [comment]
I think the proper will be adding ca-certificates dependency to openssl instead python

**Comment by fracting** [comment]
msys/openssl set ca-certificates as `optdepends`, should we set ca-certificates as `depends` or `optdepends` for mingw/openssl?

**Comment by Alexpux** [comment]
As optdepends

**Comment by fracting** [comment]
I updated the pull request, now ca-certificates is an optdepends of openssl.

Drone CI build passed.

```
New optional dependencies for mingw-w64-i686-openssl
    mingw-w64-i686-ca-certificates
```

However, if it is only optdepends, do we have to manually install mingw-w64-i686-ca-certificates when installing mingw-w64-i686-python2? I'm concerning about our `makepkg --syncdeps` script, will `--syncdeps` automatically install optdepends?

**Comment by fracting** [comment]
mingw-w64-i686-ca-certificates is also needed when calling fossil to fetch https repo. fossil is needed when building mingw-w64-i686-sqlite-analyzer.

Any ideas?

**Comment by DavidEGrayson** [comment]
I'd say that the CI server should just always install the CA certificates packages.   I think of them as an implicit dependency to a lot of things, similar to gcc and make.

**Comment by fracting** [comment]
> I'd say that the CI server should just always install the CA certificates packages. I think of them as an implicit dependency to a lot of things, similar to gcc and make.

This is not a problem for me. I can install that in one command line.

However, for a normal new MSYS2 user, it would be a great pain if s/he run python / fossil / etc to download from https connection and fails everywhere. There is no document saying the user should manually install mingw-w64-i686-ca-certificates. I took a lot of time debugging it, if I didn't luckyly get help from openssl contributors like this time, I guess I'll spend much more time, not to say average users.

At very least, I guess we should add mingw-w64-i686-ca-certificates as a member of mingw-w64-i686-toolchain group. Does that sound reasonable?

**Comment by vszakats** [comment]
I think this package should be part of the base MSYS2 installation, so nobody can miss installing it (but can update it later with the rest of MSYS2). It's a basic requirement for several secure protocols.

**Comment by vszakats** [comment]
If it's part of the base system, it will be automatically installed on any CI that offers MSYS2. No need to open Issues with each.

**Comment by Alexpux** [comment]
Well for downloading sources with pacman used MSYS version of curl with MSYS version of ca-certificates. Do not mix it. Mingw packages will never be in ````base```` group.

**Pull request merged**
