### PR TITLE
Fix crash in _fill_xrgb32_lerp_opaque_spans

### PR DESCRIPTION
**Pull request by bpisoj**

### CODE REVIEW

**Comment by mingwandroid** [comment]
I've merged this as is, but for future reference, we'd prefer if the commit message had been:
"cairo: Fix crash in _fill_xrgb32_lerp_opaque_spans"

Thanks.

**Comment by bpisoj** [comment]
Thank you!
Sorry for that.

**Comment by mingwandroid** [comment]
I merged a bit too hastily, why did you remove the call to "make" from build() {}?

**Comment by Alexpux** [comment]
Calling "make" need to be restored.

**Comment by mingwandroid** [comment]
The make install masked it, but it's clearly not the right thing to do.

I'll do it later Alexey, turn your computer off and enjoy some free time ;-)

**Comment by bpisoj** [comment]
Sorry for the late reply!
I was having build problem (see "CFLAGS" additions) so building with "make -j 1" (instead of changing "makepkg.conf"). After successful build i mistakenly deleted hole line instead "-j 1" part and as you said "make install" masked that.
Thanks for sorting it out!

**Pull request merged**
