### PR TITLE
conemu: Update

### PR DESCRIPTION
**Pull request by Haroogan**
Finally managed to finish with this.  Review, please, and if you have any questions, feel free to ask.

### CODE REVIEW

**Comment by Alexpux** [comment]
Why so many code?
Unify please package procedure

**Comment by Haroogan** [comment]
Nope, this cannot be done in this case.  ConEmu consists of 2 parts the x86 one and the x64 one, and those are optionally dependent on each other.  For instance, if only x64 is installed, then you'd have problems running x86 applications inside of it because it would not be able to inject hooks (since there will be no x86 version of `ConEmuHk.dll`).  If you don't trust me here, then I'd recommend to look at how offiical ConEmu distribution looks like (and it does exactly the way I did it here).

**Comment by Alexpux** [comment]
I don't like this package procs.
Why you write two package procs with the same code in general?
In any case I'm build both packages so it you don't need to create two packages in one

**Comment by Alexpux** [comment]
I can't accept it

**Comment by Haroogan** [comment]
It's not the same code, Alexey.  Did you really review this or just briefly looked over it?  Do you realize that certain DLLs must be x86 and some must be x64 and at the same time both (optionally) need each other to function properly?

**Comment by Alexpux** [comment]
First, Conemu.xml need to be installed into bin folder or etc. Don't create subfolders in bin. It will never be accepted. Don't tell me how consume organized. Fix it to use files in proper places.
Second, placing 32/64 bit binaries in different folders don't help you to fix issue with hooks because this folders not in the PATH at the same time.

**Comment by Alexpux** [comment]
I will update ming-w64-cross runtime to be able build ConEmu

**Comment by Haroogan** [comment]
Alexey, first of all, please, being at your position I would not assert certain things which you simply don't know in this case.  I've tested ConEmu extensively and patched its code, so I know better how it functions and how does it search for its DLLs.  In particular, ConEmu searches for DLLs not only in `PATH` but also in a `ConEmu` directory adjacent to `ConEmu.exe`, which is:
1.  Much better in this case because we don't have to expose its DLLs from `bin` since essentially nobody cares about those except for ConEmu itself.
2.  We can safely keep x86 (32-bit) DLLs inside this `ConEmu` directory, while putting those into `bin` directly would already break the idea of having separate `bin` for 64-bit and 32-bit applications.
Furthermore, `ConEmu.xml` is can be located not only near `ConEmu.exe` but also in adjacent `ConEmu` directory which is also better because `ConEmu.xml` simply does not belong to `bin` directory.

**Comment by Alexpux** [comment]
I prefer to move this package and discussion to MSYS2-packages.

**Comment by Haroogan** [comment]
Moving this one to `MSYS2-packages` is also a possibility.

**Comment by Alexpux** [comment]
And I will not change my position about creating subfolders under ````bin```` folder. Please fix ConEmu to load ````xml```` file from, for example ````../share/conemu/````.

**Comment by Haroogan** [comment]
OK, for example, I fix it to use `../share/conemu/` for `ConEmu.xml`.  But what would we do with a necessity to load DLLs of different architecture?

**Comment by Alexpux** [comment]
Moving this package to MSYS2 packages we be able to build both architectures at one shot like:
https://github.com/Alexpux/MSYS2-packages/blob/master/mingw-w64-cross-zlib/PKGBUILD#L42-L58

We will install ConEmu into /usr/bin and XML into /share/conemu. So relative path to XML will be ../../share/conemu

**Comment by Alexpux** [comment]
Heh in the past we have start work on it:
https://github.com/Alexpux/MSYS2-packages/tree/master/mingw-w64-cross-conemu-git

**Comment by Alexpux** [comment]
As cross-mingw-w64 toolchains are builded with threads=win32 you can simply get binaries that not depends on libwinpthread-1.dll

**Comment by Haroogan** [comment]
Very good, then I just want to summarize what should be the resulting binaries, so that everything works as expected:

-   `ConEmu.exe` (must be x86 for x86 MSYS2 or x64 for x64 MSYS2);
-   `ConEmuC.exe` (must be x86);
-   `ConEmuC64.exe` (must be x64);
-   `ConEmuCD.dll` (must be x86);
-   `ConEmuCD64.dll` (must be x64);
-   `ConEmuHk.dll` (must be x86);
-   `ConEmuHk64.dll` (must be x64).

**Comment by Alexpux** [comment]
As you build ConEmu twice in every package you will install both architectures into /usr/bin with different names.

**Comment by Alexpux** [comment]
Or we can leave installing ConEmu into /opt folder because it will be used from shortcuts I think.

**Comment by sschuberth** [comment]
> We always fix packages to use UNIX-like files layout. Fix it to use files in proper places.

Looks like there's no fixing need in this case: According to [this page](http://conemu.github.io/en/ConEmuFolders.html#MinGW_structure) ConEmu supports an MinGW-style directory structure out of the box. As I understand it you simply need to create a structure like this and ConEmu would still find its files and even use `sh.exe` instead of `cmd.exe` by default.

**Comment by Haroogan** [comment]
Looks interesting indeed.  Actually, I wanted to propose `libexec` myself since, for instance, we already have `emacs` put its run-time files into `libexec` too.  However, the only thing I would argue with is `libexec\conemu\ConEmu.xml`, this one seems unusual to me.  `share/conemu/ConEmu.xml` looks more reasonable.

**Comment by sschuberth** [comment]
> `share/conemu/ConEmu.xml` looks more reasonable.

I tend to agree. Maybe we can convince @Maximus5 to make ConEmu accept that location for `ConEmu.xml`, too?

**Comment by Maximus5** [comment]
OK, `share/conemu/ConEmu.xml` looks nice for me. `libexec` was suggested in the MinGW discussion thread (can't show link at the moment).
Anyway, next ConEmu build (later May I think) will support new path.

**Comment by Haroogan** [comment]
Thanks a lot, @Maximus5!

**Comment by Maximus5** [comment]
So, we put all ConEmu binaries to `/opt/bin` folder?
And I still see the "ignore recommended files warning" patch. Why?

**Comment by Alexpux** [comment]
Let's discuss on 
https://github.com/Alexpux/MSYS2-packages/tree/master/mingw-w64-cross-conemu-git

This packages is not updated for a long time so most patches not needed anymore but this will be start point for ````ConEmu```` package for MSYS2.

**Pull request closed without merging**
