### PR TITLE
vala: Update to 0.36.4 [broken]

### PR DESCRIPTION
**Pull request by lazka**
Already had this open as #2711 which doesn't allow me to reopen. Still not sure what's the problem, maybe it solved itself in the meantime.

### CODE REVIEW

**Comment by mati865** [comment]
Okay, I'm sure it's broken https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libxslt/PKGBUILD#L70

**Comment by lazka** [comment]
Uh, weird, why doesn't it fail on my machine then?

**Comment by mati865** [comment]
Maybe because you have 32 and 64 bit packages installed at same time.
CI removes 64 bit packages after 64 bit build is done and downloads 32 bit packages for 32 bit build.

**Comment by lazka** [comment]
Ah, makes sense. Thanks for helping!

**Comment by Alexpux** [comment]
Now remove debug info

**Pull request merged**
