### PR TITLE
Fix debug build for QScintilla

### PR DESCRIPTION
**Pull request by RobertBColton**
The library is already built with debug symbols, just need to make sure Qt can find it. This enables users of this package to build their apps in debug mode through Qt Creator.

http://pyqt.sourceforge.net/Docs/QScintilla2/
https://www.riverbankcomputing.com/software/qscintilla/download

### CODE REVIEW

**Comment by mati865** [comment]
Try replacing all `make install` with `make DESTDIR="${pkgdir}" INSTALL_ROOT="${pkgdir}" install`.

**Comment by RobertBColton** [comment]
Thanks, I'm trying it, I notice there's two make installs though, one for QScintilla itself and then for the designer plugin. However, the designer plugins for Qt only need the release dll, so I assume you meant for me to do it on the `make install` for QScintilla itself.

**Comment by RobertBColton** [comment]
Eh, looks like that one bit the dust too:
```
make[1]: Leaving directory '/c/M/mingw-w64-qscintilla/src/QScintilla-gpl-2.9/designer-Qt4Qt5'
mv: cannot stat '/c/M/mingw-w64-qscintilla/pkg/mingw-w64-i686-qscintilla/mingw32/lib/*.dll': No such file or directory
==> ERROR: A failure occurred in package_mingw-w64-i686-qscintilla().
```

Any other ideas? 🐈

**Comment by Alexpux** [comment]
@RobertBColton  for me path ````/c/M/mingw-w64-qscintilla/src/QScintilla-gpl-2.9/designer-Qt4Qt5```` looks wrong. I think you build on drive ````M````. Qt's ````INSTALL_ROOT```` cant be used because if you look into Qt specs you will see something like ````C:\${INSTALL_ROOT}\````

**Comment by RobertBColton** [comment]
Thanks, but I am not actually the cause of `/c/M/`. However, now that you pointed it out, it does actually look wrong even if `M:/` was intended? Again, the package was like this when I came in here though.

**Comment by Alexpux** [comment]
Fixed in https://github.com/Alexpux/MINGW-packages/commit/ebcda012fc5feaf529f083eaeea46d46f37e2fd8

**Comment by RobertBColton** [comment]
Thank you so much, I just tested installing the packaging again to upgrade it:
```bash
$ pacman -Sy mingw64/mingw-w64-x86_64-qscintilla
```
Seems to be working great in my own Qt project! Therefore, #3508 is resolved.

**Pull request closed without merging**
