### PR TITLE
mingw-w64-qt5/PKGBUILD: fixed the sql build options for qt 5.8.0

### PR DESCRIPTION
**Pull request by emmenlau**
Fix for the static compile, so currently unused for most people

### CODE REVIEW

**Comment by Optiligence** [comment]
Did this successfully build completely for you because I had to add the following for the docs to build correctly: 
```
--- x86_64/qttools/src/assistant/qhelpgenerator/qhelpgenerator.pro.ori	2017-02-20 04:04:45.433882000 +0000
+++ x86_64/qttools/src/assistant/qhelpgenerator/qhelpgenerator.pro	2017-02-20 03:58:02.115910200 +0000
@@ -1,5 +1,6 @@
 QT += network help-private
 
+QTPLUGIN += qsqlite
 QTPLUGIN.platforms = qminimal
 
 SOURCES += ../shared/helpgenerator.cpp \
```
Do you know of any other unresolved issues with static 5.8?

**Comment by Alexpux** [comment]
I'm plan to build static Qt-5.8 but without Webkit module I  think

**Comment by emmenlau** [comment]
Dear @Optiligence , I test these sql options on the dynamic build, not the static build. So the PR just removes the deprecated sql options and replaces them with the corresponding options for Qt 5.8, but I did not test static. Thanks for the feedback!

**Comment by Alexpux** [comment]
I'm building static Qt5 with legacy Webkit now. Will move to new Webkit when it will be ready

**Comment by Alexpux** [comment]
Right now I cant build Qt5 static due to errros building QtWebkit module.

**Comment by Optiligence** [comment]
webkit was never shipped with qt-static anyways, no?

**Comment by Alexpux** [comment]
Webkit1 was shipped

**Comment by Optiligence** [comment]
Well `pacman -Ql mingw-w64-x86_64-qt5-static | grep -i webkit` gives nothing for 5.6 and I also had in my head that it was a ancient decision of the Qt team to not build WebKit with static Qt.

**Comment by Alexpux** [comment]
@Optiligence look that you not search over yesterdays uploaded Qt 5.8.0 static. It builded without webkit

**Comment by Optiligence** [comment]
It holds true for 5.8 and 5.6 (that there is no webkit), and i’m pretty sure also for releases prior. 
Thanks for uploading 5.8. (tho I still tinker with #1942)

**Pull request merged**
