### PR TITLE
Update wkhtmltopdf to release 0.12.4

### PR DESCRIPTION
**Pull request by dsogari**
- use original setup script (from branch master)
- add patch for the qt4 static dependency
- add patch for library name (prefix "lib")

*note: the version is less because I changed from 0.13 branch (which links with precompiled Qt5) to branch master (which builds and links with a patched version of Qt4)

### CODE REVIEW

**Comment by Alexpux** [comment]
Add replaces entry

**Comment by dsogari** [comment]
I'm not sure how to add the replalces entry in this case, since the package name was not changed. Should it be: `replaces=("${MINGW_PACKAGE_PREFIX}-${_realname}")` ?

**Comment by Alexpux** [comment]
Should be
````
replaces=("${MINGW_PACKAGE_PREFIX}-${_realname}-git")
````

**Comment by Alexpux** [comment]
Also I don't understand line where you clone qt repository. I will not accept it sorry. Instead need fix our Qt4 package and link with it.

**Comment by dsogari** [comment]
I'm sorry. It is part of the build procedure recommended by the authors.
I did try to link against the precompiiled Qt4 from MINGW-packages, but the executable programs did not work as expected.

**Comment by dsogari** [comment]
The previous approach of building their 0.13 branch and linking against Qt5 does not work anymore, since the QtWebkit module was dropped in favor of QtWebEngine

**Comment by Alexpux** [comment]
We provide new QtWebkit module as separate package

**Comment by dsogari** [comment]
That's great news!! I did not know that! Thanks! :)

**Comment by dsogari** [comment]
I tried to compile using Qt5 and the newest QtWebkit, but I get these compilation errors saying that the Qt5WebKit* libraries could not be found:
```
cd src/lib/ && ( test -e Makefile || C:/msys64/mingw64/bin/qmake.exe -o Makefile C:/work/Git/MINGW-packages/mingw-w64-wkhtmltopdf/src/wkhtmltopdf/src/lib/lib.pro -spec win32-g++ ) && make -f Makefile release
make[1]: Entering directory '/c/work/Git/MINGW-packages/mingw-w64-wkhtmltopdf-git/src/build-x86_64-w64-mingw32/src/lib'
make -f Makefile.Release
make[2]: Entering directory '/c/work/Git/MINGW-packages/mingw-w64-wkhtmltopdf-git/src/build-x86_64-w64-mingw32/src/lib'
x86_64-w64-mingw32-g++ -static -static-libgcc -static-libstdc++ -Wl,-s -shared -Wl,-subsystem,console -mthreads -Wl,--out-implib,../../bin/liblibwkhtmltox.dll.dll.a -Wl,../../../wkhtmltopdf/src/lib/lib.def -o ../../bin/libwkhtmltox.dll object_script.libwkhtmltox.Release  -lglu32 -lopengl32 -lgdi32 -luser32 -LC:/msys64/mingw64/lib -lQt5WebKitWidgets -lQt5WebKit C:/msys64/mingw64/lib/libQt5Svg.dll.a C:/msys64/mingw64/lib/libQt5PrintSupport.dll.a C:/msys64/mingw64/lib/libQt5Widgets.dll.a C:/msys64/mingw64/lib/libQt5Gui.dll.a C:/msys64/mingw64/lib/libQt5XmlPatterns.dll.a C:/msys64/mingw64/lib/libQt5Network.dll.a C:/msys64/mingw64/lib/libQt5Core.dll.a 
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5WebKitWidgets
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lQt5WebKit
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile.Release:145: ../../bin/libwkhtmltox.dll] Error 1
make[2]: Leaving directory '/c/work/Git/MINGW-packages/mingw-w64-wkhtmltopdf-git/src/build-x86_64-w64-mingw32/src/lib'
make[1]: *** [Makefile:48: release] Error 2
make[1]: Leaving directory '/c/work/Git/MINGW-packages/mingw-w64-wkhtmltopdf-git/src/build-x86_64-w64-mingw32/src/lib'
make: *** [Makefile:506: sub-src-lib-release_ordered] Error 2
```

Could you give me a hint on how to solve this? Perhaps someone already had this issue...

**Comment by dsogari** [comment]
No matter, I fixed it! Will update soon...

**Comment by dsogari** [comment]
I could not make it build with the conventional "lib" prefix for the dll.
Despite this, it's all working!

**Pull request merged**
