### PR TITLE
enabled opengl support and forced gdi+ graphics context

### PR DESCRIPTION
**Pull request by DoctorWho11**
also added the static build instructions in.

### CODE REVIEW

**Comment by Alexpux** [comment]
We use two spaces in PKGBUILD's instead TAB. Please adjust your changes to it.

**Comment by mingwandroid** [comment]
In case you need it:

Make then changes then:
git add PKGBUILD
git commit --amend
git push origin --force

**Comment by DoctorWho11** [comment]
I'll have that fixed in the morning. Atm in the middle of a computer rebuild.

**Comment by DoctorWho11** [comment]
I fixed the spacing using expand -t 2 PKGBUILD > PKGBUILD.new; mv PKGBUILD.new PKGBUILD so it /should/ be fixed.

**Comment by DoctorWho11** [comment]
Also for the record, I don't use tabs, my editor inserts spaces. I refuse to use hard tabs on my PKGBUILD.

**Comment by DoctorWho11** [comment]
seems my editor was slightly in fault. I'll need to check the space settings.

**Pull request merged**
