### PR TITLE
Inkscape: update dependencies

### PR DESCRIPTION
**Pull request by Ede123**
Inkscape 0.92 has some new dependencies.

We now have libvisio (#2194) and already had potrace for some time.

### CODE REVIEW

**Comment by Alexpux** [comment]
Increase pkgrel

**Comment by Ede123** [comment]
> Increase pkgrel
done.

Should I always increase `pkgrel`?
I didn't do it before because I assume Inkscape was already built with those dependencies (they were just not yet listed) and therefore a rebuilt would not be necessary.

**Comment by Alexpux** [comment]
If dependencies was not listed then after install you will not get all dependencies and users will report about it. So you need to increase pkgrel in cases when package need to be rebuild and reset pkgrel to 1 when new version is out.

**Comment by Alexpux** [comment]
Don't yet see increased pkgrel

**Comment by Ede123** [comment]
> Don't yet see increased pkgrel

Sorry, forgot to stage the change 🤦

**Comment by mati865** [comment]
> Should I always increase pkgrel?

If you make changes that are important (like dependency changes, fixes, rebuilds, etc.) you have to bump pkgrel.
If your changes don't really affect compiled package (like coding style) you don't bump it.

**Pull request merged**
