### PR TITLE
Update fossil

### PR DESCRIPTION
**Pull request by BMBurstein**

### CODE REVIEW

**Comment by elieux** [comment]
@BMBurstein, I'm awfully confused. Can you explain your patch? I'm especially interested in:

- How is this fossil v1.35? The latest version as of 2016-02-06 is v1.34, as can be seen in the [tag list](https://www.fossil-scm.org/index.html/taglist) and on the [download page](https://www.fossil-scm.org/download.html). It seems you're instead pulling a [specific revision from trunk](https://www.fossil-scm.org/fossil/info/ec3dd27f97571cd66a2ac129fce0d0a738d58182).
- Did you test your build before submitting the patch? On both Alexey's and my systems, the package archive ends up being empty due to path mangling issues.
- Why did you remove my patches? Did fossil remove all that Windows-specific non-sense and break backwards compatibility?

Sorry to pour all this on you like this, but I'm hoping at least you can answer my questions, so I know what happened.

**Comment by BMBurstein** [comment]
I tested and it seemed to work on my machine. I don't have much experience
(actually - none) with the pacman/msys build system, so I may have done
something wrong.
The official fossil recommendation is to not wait for an "official" release
but rather use the trunk version at any given point. The fossil website
itself uses a trunk version, updated about once a week, and labels it
"1.35" as can be seen in the footer of any page on that site. The version I
pulled was the one the fossil website was running at the time.
I have been compiling fossli from source without any patches from an msys2
shell for years, so I am not sure why the patches were needed in the first
place, but recent chabges to the default makefile in the fossil source tree
done right before the version I am pulling now allow fossil to compile in
msys2 shell with no more than the standard configure/make.

I am sorry if using a non-official release is not accepted. If that is the
case, I will wait for the official 1.35 release and try again. If this is
ok, I will try to fix my submission so it works on other machines, too.

Either way, I appreciate your work on msys/mingw. I use them more and more.

Baruch

On Sat, Feb 6, 2016 at 11:50 PM, David Macek <notifications@github.com>
wrote:

> @BMBurstein <https://github.com/BMBurstein>, I'm awfully confused. Can
> you explain your patch? I'm especially interested in:
>
>    - How is this fossil v1.35? The latest version as of 2016-02-06 is
>    v1.34, as can be seen in the tag list
>    <https://www.fossil-scm.org/index.html/taglist> and on the download
>    page <https://www.fossil-scm.org/download.html>. It seems you're
>    instead pulling a specific revision from trunk
>    <https://www.fossil-scm.org/fossil/info/ec3dd27f97571cd66a2ac129fce0d0a738d58182>
>    .
>    - Did you test your build before submitting the patch? On both
>    Alexey's and my systems, the package archive ends up being empty due to
>    path mangling issues.
>    - Why did you remove my patches? Did fossil remove all that
>    Windows-specific non-sense and break backwards compatibility?
>
> Sorry to pour all this on you like this, but I'm hoping at least you can
> answer my questions, so I know what happened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexpux/MINGW-packages/pull/1027#issuecomment-180871332>
> .
>



-- 
˙uʍop-ǝpısdn sı ɹoʇıuoɯ ɹnoʎ 'sıɥʇ pɐǝɹ uɐɔ noʎ ɟı

**Comment by elieux** [comment]
Thanks for explaining.

Yes, we prefer packaging releases. Only if the latest release is broken or if it's very old, we package software from trunk.

One of the changes that was needed is to make `make install DESTDIR=...` work. I assume you don't use this command when building yourself. Before submitting a pull request, you should test with `makepkg-mingw` and `pacman -U *.pkg.tar.xz` to make sure the package builds and installs correctly.

In the end, I was able to remove some of the build hacks, but not all of them, and I had to add one more. Also, `win.patch` is there to make our fossil more like the Linux one and I think we should keep that.

I'll try to figure out as many things as I can with upstream (see my message on the mailing list), but until then, this PKGBUILD will probably need to stay complicated.

**Comment by BMBurstein** [comment]
Ok. I would be happy to help with this. I am a committer on the fossil
repo, if that helps get things into upstream fossil, although usually the
mailing list is just as useful in getting changes made.

On Sun, Feb 7, 2016 at 7:36 PM, David Macek <notifications@github.com>
wrote:

> Thanks for explaining.
>
> Yes, we prefer packaging releases. Only if the latest release is broken or
> if it's very old, we package software from trunk.
>
> One of the changes that was needed is to make make install DESTDIR=...
> work. I assume you don't use this command when building yourself. Before
> submitting a pull request, you should test with makepkg-mingw and pacman
> -U *.pkg.tar.xz to make sure the package builds and installs correctly.
>
> In the end, I was able to remove some of the build hacks, but not all of
> them, and I had to add one more. Also, win.patch is there to make our
> fossil more like the Linux one and I think we should keep that.
>
> I'll try to figure out as many things as I can with upstream (see my
> message on the mailing list), but until then, this PKGBUILD will probably
> need to stay complicated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexpux/MINGW-packages/pull/1027#issuecomment-181058334>
> .
>



-- 
˙uʍop-ǝpısdn sı ɹoʇıuoɯ ɹnoʎ 'sıɥʇ pɐǝɹ uɐɔ noʎ ɟı

**Comment by BMBurstein** [comment]
I saw on the mailing list that configure+make didn't work for you. It works
flawlessly for me. Is it something in my setup?

On Sun, Feb 7, 2016 at 10:34 PM, Baruch Burstein <bmburstein@gmail.com>
wrote:

> Ok. I would be happy to help with this. I am a committer on the fossil
> repo, if that helps get things into upstream fossil, although usually the
> mailing list is just as useful in getting changes made.
>
> On Sun, Feb 7, 2016 at 7:36 PM, David Macek <notifications@github.com>
> wrote:
>
>> Thanks for explaining.
>>
>> Yes, we prefer packaging releases. Only if the latest release is broken
>> or if it's very old, we package software from trunk.
>>
>> One of the changes that was needed is to make make install DESTDIR=...
>> work. I assume you don't use this command when building yourself. Before
>> submitting a pull request, you should test with makepkg-mingw and pacman
>> -U *.pkg.tar.xz to make sure the package builds and installs correctly.
>>
>> In the end, I was able to remove some of the build hacks, but not all of
>> them, and I had to add one more. Also, win.patch is there to make our
>> fossil more like the Linux one and I think we should keep that.
>>
>> I'll try to figure out as many things as I can with upstream (see my
>> message on the mailing list), but until then, this PKGBUILD will probably
>> need to stay complicated.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Alexpux/MINGW-packages/pull/1027#issuecomment-181058334>
>> .
>>
>
>
>
> --
> ˙uʍop-ǝpısdn sı ɹoʇıuoɯ ɹnoʎ 'sıɥʇ pɐǝɹ uɐɔ noʎ ɟı
>



-- 
˙uʍop-ǝpısdn sı ɹoʇıuoɯ ɹnoʎ 'sıɥʇ pɐǝɹ uɐɔ noʎ ɟı

**Comment by elieux** [comment]
Hmm. Did you try it with v1.34?

**Comment by BMBurstein** [comment]
No. The configure+make did not work with msys until a few weeks ago (
http://www.fossil-scm.org/index.html/info/a0061bb2ed9b1433). Until then I
would use win/makefile.mingw with "X64=1".

On Sun, Feb 7, 2016 at 10:52 PM, David Macek <notifications@github.com>
wrote:

> Hmm. Did you try it with v1.34?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexpux/MINGW-packages/pull/1027#issuecomment-181114528>
> .
>



-- 
˙uʍop-ǝpısdn sı ɹoʇıuoɯ ɹnoʎ 'sıɥʇ pɐǝɹ uɐɔ noʎ ɟı

**Comment by elieux** [comment]
Okay. That seems to match my observations. I have some time now to describe my patches in more detail. If you look at [my PKGBUILD](https://github.com/elieux/MINGW-packages/blob/ec40fa2f7fcd1f4958b48c7870a4de7dfb52d708/mingw-w64-fossil/PKGBUILD), you'll see:

1. `win.patch`: revert to general Linuxy behavior instead of specific Windows hacks; both for v1.34 and trunk
2. `readline.patch`: fix missing <termios.h> (due to linenoise being compiled); I'm not sure if this is needed for trunk, but if the "fix" in trunk is to disable line editing feature on Windows, then I would like to keep that patch
3. `MSYS2_ARG_CONV_EXCL=--prefix`: fix `make install DESTDIR=...` by not converting `@prefix@` in `Makefile`; that was for v1.34, but I think there's no fix in trunk in this regard
4. `CFLAGS+="-DBROKEN_MINGW_CMDLINE=not_actually_broken"`: define the constant for v1.34; trunk defines it automatically
5. `sed -i '/ENABLE_MINIZ/d' Makefile.in`: remove extra line from `Makefile` because it's not expanded properly

**Comment by BMBurstein** [comment]
Why do I not need any of these to compile? Specifically, your last 2 seem
to be not about "fixing" fossil itself for mingw64/msys, but about "fixing"
the default build system, which works fine for me without the need for
those two fixes.

On Sun, Feb 7, 2016 at 11:36 PM, David Macek <notifications@github.com>
wrote:

> Okay. That seems to match my observations. I have some time now to
> describe my patches in more detail. If you look at my PKGBUILD
> <https://github.com/elieux/MINGW-packages/blob/ec40fa2f7fcd1f4958b48c7870a4de7dfb52d708/mingw-w64-fossil/PKGBUILD>,
> you'll see:
>
>    1. win.patch: revert to general Linuxy behavior instead of specific
>    Windows hacks; both for v1.34 and trunk
>    2. readline.patch: fix missing (due to linenoise being compiled); I'm
>    not sure if this is needed for trunk, but if the "fix" in trunk is to
>    disable line editing feature on Windows, then I would like to keep that
>    patch
>    3. MSYS2_ARG_CONV_EXCL=--prefix: fix make install DESTDIR=... by not
>    converting @prefix@ in Makefile; that was for v1.34, but I think
>    there's no fix in trunk in this regard
>    4. CFLAGS+="-DBROKEN_MINGW_CMDLINE=not_actually_broken": define the
>    constant for v1.34; trunk defines it automatically
>    5. sed -i '/ENABLE_MINIZ/d' Makefile.in: remove extra line from
>    Makefile because it's not expanded properly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexpux/MINGW-packages/pull/1027#issuecomment-181122410>
> .
>



-- 
˙uʍop-ǝpısdn sı ɹoʇıuoɯ ɹnoʎ 'sıɥʇ pɐǝɹ uɐɔ noʎ ɟı

**Comment by elieux** [comment]
1. Not needed to build.
2. It's probably fixed in trunk.
3. I think you don't use `make install DESTDIR=...`.
4. It's fixed in trunk.
5. Doesn't cause any issues AFAIK.

**Pull request merged**
