### PR TITLE
Adding lfcbase, lfcxml and cego packages

### PR DESCRIPTION
**Pull request by bjlemke**
This request adds the following PKGBUILD files to the repository

mingw-m64-lfcbase/PKGBUILD
mingw-m64-lfcxml/PKGBUILD
mingw-m64-cego/PKGBUILD

The build process has been already tested isolated but still not with the contained
dependencies
lfcxml needs lfcbase
cego needs lfcxml and lfcbase

Hopefully, this time the request is fine. Sorry for the confusion !

### CODE REVIEW

**Comment by mingwandroid** [comment]
Hi @bjlemke, you still need to squash all these into either a single commit (or if you prefer, into 3, one for each package).

For a single, commit, the procedure is:

`git rebase -i HEAD~11`, then change each commit after the first to be have `s` in-front (i.e. squ ash), then exit your editor. Git will then bring up another dialog to allow you to edit the commit message. Delete everything and just rewrite, something describing that you added all 3 packages in the subject with a description of them after a blank line in the body:

    lfcbase, lfcxml, cego: New packages

    These packages are from http://www.lemke-it.com/
    Cego is a relational and transactional database system
    using an object oriented software design .. etc etc..

Then, to update *this* pull request without needing to make another, use `git push origin master --force`. You will sometimes see git literature explicitly telling you never to force push published things, but until we merge from your fork it's not been published into our repository yet so that advice doesn't apply and it is exactly this workflow that GitHub excels in for iterating on pull requests.

Many thanks.

**Comment by bjlemke** [comment]
Hi Ray,

thanks for the hint.

I tried the rebase procedure, you described below, but I got an error message from git.
Understand, that I just have to change from the second line.

Git is great, but a little bit complex :)

Best regards,
Björn


Björn Lemke
lemke@lemke-it.com
http://www.lemke-it.com

**Comment by bjlemke** [comment]
Following Rays procedure, hope you can deal with this request now

**Comment by mingwandroid** [comment]
Thanks!

**Pull request merged**
