### PR TITLE
build qt5-static with icu

### PR DESCRIPTION
**Pull request by Optiligence**
remove the s prefix which isn’t present with msys2
remove the d suffix because the debug symbol names are different and it wont link
(probably needs a compile definition to alter the headers)

### CODE REVIEW

**Comment by Optiligence** [comment]
@Alexpux what’s the holdup?

i need this for extended encoding support in qtextcodec in my ci builds.

**Comment by Alexpux** [comment]
@Optiligence I dont have time right now to test it. Next 3 weeks I will be far from my build machine and will not work under MSYS2

**Comment by Optiligence** [comment]
@Alexpux Do you have a proposal/plan on how to reconcile that, now and in general?

**Comment by Alexpux** [comment]
@Optiligence i dont have a plan. Currently 32 bit Qt5 doesnt build becaue of failing qdoc linking with llvm

**Comment by Optiligence** [comment]
@Alexpux thx

**Pull request merged**
